### ISSUE TITLE
Copy in-progress documentation to issues?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#10]
@elijahverdoorn: Would you mind if I copied/moved the documentation on what's in-progress to individual issues, rather than living in the README?

**Comment by elijahverdoorn** [comment]
@hawkrives Let's open an issue for each item, move the details for that into the issue, but keep the highest-level stuff in the README (at least until v1 launches).

**Comment by hawkrives** [comment]
✅

**Comment by hawkrives** [comment]
Alright, I think I've got everything.

I added a new "help requested" label for people to add if they're stuck and want someone to help out.

Of course, there's also the slack channel.

**Comment by elijahverdoorn** [comment]
@hawkrives Slack Channel? I have used slack in my internship this summer, but haven't head about a St. Olaf slack channel! What's the info?

**Comment by hawkrives** [comment]
… you have an account, dude. [aibohphobia.slack.com](https://aibohphobia.slack.com)

That explains why you haven't been active recently 😆 

Edit: It looks like you signed up with your personal Gmail account, if that helps.

**Comment by hawkrives** [comment]
Regarding the Slack channel: It started as Gobbldygook-only, then @drewvolz and I expanded it to be CS-students. I'm hoping that teams and classes can come together to work together, help each other, collaborate, and share resources with it.

It's also been pretty handy for chatting about various extra-curricular projects, like everything under @StoDevX.
