### ISSUE TITLE
Pause calendar causes crash

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1000]
Replicating it each time I load the pause calendar.

**Comment by drewvolz** [comment]
```
Cannot get property 'replace' of undefined

fastGetTrimmedText -- html.js:35
EventRow -- event-row.js:36

event-row.js
  const title = fastGetTrimmedText(event.summary)

html.js
  return str.replace(/<[^>]*>|\s+/g, ' ').replace(/\s+/g, ' ').trim()

```

**Comment by drewvolz** [comment]
The issue is... there is an event with no `summary` key. That means it will not get a title, but we expect it to have the summary data. We need to check if that key is defined before using it.

**Comment by hawkrives** [comment]
@drewvolz Are you handling this?

**Comment by drewvolz** [comment]
it's all yours!
