### ISSUE TITLE
AlphabetListView crashes dictionary search

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1001]
Typing quickly into the search bar causes the AlphabetListView to throw an exception and crash.

<img width="287" alt="screen shot 2017-04-16 at 4 30 01 pm" src="https://cloud.githubusercontent.com/assets/5240843/25074336/7f4aac26-22c6-11e7-9ee7-1c965debb4c8.png">

**Comment by drewvolz** [comment]
This is an issue on both the sims and physical devices.

**Comment by drewvolz** [comment]
https://github.com/sunnylqm/react-native-alphabetlistview/issues/32

**Comment by hawkrives** [comment]
So… debouncing it _at all_, even with a debounce of 0, solves the issue. Something something microtask queue? Idk.

I'll make a quick PR to resolve this.
