### ISSUE TITLE
Call button prompts twice

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1007]
I am unsure what the result is on Android, but the prompt to make a phone call from the Important Contacts double-prompts the call/cancel options after hitting call the first time.

**Comment by drewvolz** [comment]
https://github.com/anarchicknight/react-native-communications/issues/46

**Comment by drewvolz** [comment]
This is a "note/known issue" with openURL in iOS 10.3

> When a third party application invokes openURL: on a tel:/ facetime:/, or facetime-audio:/
iOS displays a prompt and requires user confirmation before dialing.

**Comment by hawkrives** [comment]
… so it's an os bug, no?

**Comment by drewvolz** [comment]
Seems to be.

**Comment by hawkrives** [comment]
So do we want to do anything about it?

**Comment by drewvolz** [comment]
We could hide our custom prompting and use the official prompt as-is? If Apple changes the behavior, then we can switch back? I'm wondering if this is simply a beta issue that will resolve itself, or if the protocol is changing in favor of always prompting. Let's keep platform independence in mind.

**Comment by hawkrives** [comment]
We could just check for platform === iOS, but that doesn't help with iOS < 10.3.

**Comment by hawkrives** [comment]
@drewvolz I'm going to close this, and if the "known issue" makes its way into a released version of iOS then we'll revisit?
