### ISSUE TITLE
Making a scrolling gesture while swiping back from any WebView continues to scroll

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1050]
> This is not a v2.2 blocker.

You shouldn't be able to scroll the detail view while you're swiping backwards.

**Comment by hawkrives** [comment]
(This problem has been around as long as News has. I'm only now filing it.)

**Comment by drewvolz** [comment]
To clarify, this happens on the news detail view rather than the list of stories. Depending on how many touches you're willing to make, it's possible to perform this on the safari webviews with two fingers, too. We should look into disabling scrolling when the component will unmount.

**Comment by hawkrives** [comment]
Yes, but that's only if you've already started scrolling. I definitely prefer that. (the way that SFWebView works, instead of our own WebViews.)

**Comment by hawkrives** [comment]
I haven't even found anyone complaining about this yet. I do know that RN's ability to disable scrolling on a webview is limited to iOS.

**Comment by hawkrives** [comment]
This still happens with React Navigation.

Not that I was expecting it to be fixed; just noting it.
