### ISSUE TITLE
Campus Map

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#11]
- The iOS version of this is easy, there is a built-in component
- Android version could be harder, find an existing component?

---

IIRC, when I last looked at this, I came to the conclusion that we'd need to get a Google Maps API key for Android, at least.

**Comment by elijahverdoorn** [comment]
I have a google maps key that I registered for as a student, so I get 500,000 requests per day for free. We could use that? It's under the same account as the key that I'm using for the calendar API, so that'd keep things consistent.

**Comment by hawkrives** [comment]
Sounds good to me!

**Comment by hawkrives** [comment]
OH OH OH OH OH

@elijahverdoorn if you haven't seen the new campus map

look at https://www.myatlascms.com/map/index.php?id=294#!ct/14990,14877,15145,15789,14884,14882,14874,14889,15142?ce/14889

**Comment by elijahverdoorn** [comment]
Let's use that!

**Comment by hawkrives** [comment]
I will point out that we have a url for it in https://github.com/StoDevX/AAO-React-Native/blob/master/data/map.json, and coordinates for various houses and buildings (probably useless now) in https://github.com/StoDevX/AAO-React-Native/blob/master/data/map-coordinates.json.

Just go ahead and `import` the json files for now; we'll figure out how to load and cache them later.

**Comment by drewvolz** [comment]
I'm torn on whether we should make use of the web view map or overlay the coordinates.

**Comment by hawkrives** [comment]
I vote to start with the webview version

**Comment by drewvolz** [comment]
Okay. I also remember you had a working native map implemented. I am agreeing that we can use the web view for the accessibility, searching, and extreme detail that it provides, but it would put me at ease to have a backup switch in place. 

And here is why that would make me comfortable -- when I put up the web view of SIS that was not publicized (at mobile.stolaf.edu - now defunct), IT noticed increased web traffic to that subdomain. They eventually voted to take that mobile website down, one that provided a quick look at schedules, grades, finances/account balances, and more via the official website. It was a student project through IT that they deemed no longer necessary, coincidentally after we started using it more. Correlation is not causation, though.

So I love the web view idea. It's easy and already functions. But for the pure sake that we have a backup already generated in RN and for the sake of websites being changed or removed completely as often as they are, perhaps after we simply add the web view, the switch to the native could be put into place sometime after that.

I'm not trying to be a pain and voice concerns or cry foul. I believe my focus is on providing a fluid and functional experience for the user, and thinking ahead on these things is my way of doing that.

I can agree to getting the web view out the door in the first version as it was mentioned in a previous comment is ideal. I hope we then can think about how to better serve-up that information, if we conclude that we are willing and able.

**Comment by hawkrives** [comment]
If I recall correctly, I never did get a good map working on Android.

Also, I can't get my copy of the project to build if I include the native maps component, so I'm in favor of taking that out 👐

But that's a good point about them taking things down. Grumble.

**Comment by drewvolz** [comment]
Alright that's fair

**Comment by elijahverdoorn** [comment]
I also tried to build an Android native maps view, and couldn't get it. I
vote the Web view.

**Comment by hawkrives** [comment]
Great. I'll probably submit a PR for it tonight my time.
