### ISSUE TITLE
SIS double room listings

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#110]
Double room listing needs alignment adjustment. It is understood that multiple room listings appear, but we must have a way to present it without hiding overflow.
<img width="360" alt="screen shot 2016-08-20 at 2 34 19 pm" src="https://cloud.githubusercontent.com/assets/5240843/17833166/367ffed2-66e3-11e6-8812-26dacef2a476.png">

**Comment by hawkrives** [comment]
I've actually accounted for that in the current design. The problem is that my current parsing strips out the `<br>` tag they they use to separate multiple times / locations. 

I'll fix that today.

**Comment by hawkrives** [comment]
Fixed locally.

**Comment by drewvolz** [comment]
This is closed by #121
