### ISSUE TITLE
ListViews need a fallback

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#112]
If we do not render anything, we should provide text and/or an image to provide context.

## A List of ListViews:

- [x] ~~Hours~~ (static data source)
- [x] ~~Webcams~~ (static data source)
- [x] Calendar (https://github.com/StoDevX/AAO-React-Native/blob/master/views/calendar/calendar.js#L169-L171)
- [x] Menus (https://github.com/StoDevX/AAO-React-Native/blob/master/views/menus/components/menu.js#L85-L87)
- [x] News (https://github.com/StoDevX/AAO-React-Native/blob/master/views/news/news-container.js#L110-L112)
- [x] Orgs (https://github.com/StoDevX/AAO-React-Native/blob/master/views/student-orgs/list.js#L158-L160)
- [x] SIS/Courses
- [x] Oleville

**Comment by hawkrives** [comment]
I'll take this one.

**Comment by drewvolz** [comment]
Bump. This has now reached the Oleville calendar.

<img width="361" alt="screenshot of Oleville latest" src="https://cloud.githubusercontent.com/assets/5240843/18684907/f7de49e4-7f43-11e6-9aa5-5c6db4d93616.png">

**Comment by hawkrives** [comment]
Grumble de grumble grump.

**Comment by hawkrives** [comment]
We should re-evaluate this issue on current `master` /slash/ the android/common-lists stuff I'm working on.

**Comment by hawkrives** [comment]
I think this is now completed – I just checked off SIS/Courses, because we disabled it, and I checked off Oleville, because it's been merged with News.

**Comment by hawkrives** [comment]
@drewvolz I'll let you close it / provide an update if we're not done with this.

**Comment by drewvolz** [comment]
Looks good to me.
