### ISSUE TITLE
[iOS] Fix keyboard showing up over Orgs detail

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1141]
The keyboard consistently appears over the detail view of a student org with these steps:

1. Open student orgs list
2. Search for org with website in detail (Agnes A Cappella, GLOW, etc)
3. Tap on result and go to detail
4. Tap link to open browser
5. Go back, notice the keyboard on the detail view

Something something resign first responder.

**Comment by hawkrives** [comment]
@drewvolz Is this still an issue?

**Comment by drewvolz** [comment]
Yes

**Comment by drewvolz** [comment]
If I manually dismiss the keyboard before visiting the 2 detail views, this issue goes away.
