### ISSUE TITLE
Move to react-navigation

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1146]
From the release notes for https://github.com/facebook/react-native/releases/tag/v0.44.3:

> Navigator has been deprecated in favor of [React Navigation](https://reactnavigation.org/). If you wish to continue using Navigator, you can install the [react-native-deprecated-custom-components](https://github.com/facebookarchive/react-native-custom-components) package which provides the legacy Navigator component.

I have a local branch that I'll push soon that starts us down this road. It accidentally grew into a "let's rework News to use redux" branch too, so I'll try to remove that and just make a "replace Navigator with React Navigation" branch. (pushed at [`react-navigation`](https://github.com/StoDevX/AAO-React-Native/tree/react-navigation))

<details><summary>current status</summary> 

![image](https://user-images.githubusercontent.com/464441/26861232-2a43b92e-4b08-11e7-9cb1-cb323d151868.png)

note the lack of toolbar buttons
</details>
<br/>

IIRC, the current status is:

- no nav buttons on the toolbar on the homescreen
    - the Edit button is doable, but I don't think it supports left-side custom components. We'll have to investigate that.
- It's a pretty major departure from the old navigation style, but I think I can take what I learned from that branch and make a less invasive change PR.
    - namely, when I started that migration I didn't think you could pass objects to child routes, which we rely on heavily for e.g. News stories; I later figured out how to pass objects. That's why I started moving more stuff into Redux, but I should be able to separate those two changes now.

**Comment by hawkrives** [comment]
Other benefits of react-navigation: drop shadows when wiping back on iOS, better platform defaults, text size in the navbar isn't affected by accessibility customizations (which is what the native apps do).

So by changing to React Navigation, we'll be able to close https://github.com/StoDevX/AAO-React-Native/issues/590.

**Comment by elijahverdoorn** [comment]
this sounds awesome.

**Comment by rye** [comment]
FWIW, this (and #1160) improved the UI a lot for me. Here's a peek at it on my device. Pretty!

![screenshot_20170615-172140](https://user-images.githubusercontent.com/1566689/27204224-80779d90-51ef-11e7-9f0f-6e94fdafea0a.png)

**Comment by hawkrives** [comment]
@rye Woot!
