### ISSUE TITLE
LaunchScreen's status bar coverage is iPhone-width on iPad

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1186]
I'll try to get a screenshot later.

The toolbar goes the full width, but the status bar is less than half the width of my iPad's screen.

**Comment by hawkrives** [comment]
<img width="576" alt="screen shot 2017-06-14 at 10 58 51 pm" src="https://user-images.githubusercontent.com/464441/27164769-1bbbfaee-5155-11e7-93cb-0f81c6ecba20.png">

**Comment by drewvolz** [comment]
Wow. Good catch.

**Comment by hawkrives** [comment]
It helps that my iPad is really slow :)
I get to see the launchscreen for a few seconds.
