### ISSUE TITLE
Bus map sometimes opens completely zoomed out

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1187]
I thought I'd fixed it, but I'm seeing it on my iPad at least.

Screenshot to come later.

![img_0003](https://user-images.githubusercontent.com/464441/27164436-ee624afa-5152-11e7-849e-a53032f716cb.PNG)

**Comment by drewvolz** [comment]
I would have never known what continent I was on if it hadn't been for this bug.

**Comment by hawkrives** [comment]
If I can't figure something out about this by ship time, I will disable the entry point.

**Comment by drewvolz** [comment]
https://github.com/airbnb/react-native-maps/issues/919

**Comment by drewvolz** [comment]
https://github.com/airbnb/react-native-maps/issues/964#issuecomment-272701240
https://github.com/airbnb/react-native-maps/issues/964#issuecomment-320142430

**Comment by drewvolz** [comment]
~I'm thinking we should try changing `onRegionChange` to `onRegionChangeComplete`~ this simply resets the view _back_ to what it was originally...
