### ISSUE TITLE
Report Hours Issue screen "welcome" text is not padded

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1188]
yeah yeah. I can't believe I didn't fix it before I merged it.

![img_0004](https://user-images.githubusercontent.com/464441/27164443-fb9fa758-5152-11e7-82b6-9dde3803428d.PNG)

**Comment by drewvolz** [comment]
This one isn’t on you entirely. You mentioned that I should poke at this before it was merged. I’ll see what I can do.

**Comment by hawkrives** [comment]
That was just because I was feeling too lazy to do it ;)

Don’t we have this somewhere else in the app? Worst case, you can probably pull the padding numbers from, say, Credits.

**Comment by drewvolz** [comment]
Does wifi reporting have it? I’m not incredibly concerned about replicating something but if we do have something we like, we’ll use it.

**Comment by hawkrives** [comment]
… I think Wifi reporting uses the card from Important Contacts.

**Comment by hawkrives** [comment]
Closed by #1220

**Comment by hawkrives** [comment]
Letting Drew close this

**Comment by drewvolz** [comment]
Closing!
