### ISSUE TITLE
Report Hours screen's Delete Schedule buttons have no top border and a double bottom border

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1190]
as it says in the title

![img_0004](https://user-images.githubusercontent.com/464441/27164443-fb9fa758-5152-11e7-82b6-9dde3803428d.PNG)

**Comment by drewvolz** [comment]
The divider oddly enough shows up on a “new” instance of those schedules from the “Add new schedule” button.

**Comment by hawkrives** [comment]
Bizarre. 

Usually when tableview-simple does a double border, it’s because we have a `null` in the Section (since the borders are controlled by Section, not Cell.)

However, I looked here and couldn’t find any null cells. So I’m not sure what’s going on.

**Comment by hawkrives** [comment]
The no-top-border appears to come from the positioning in the list; if you add a new Schedule, you never get the border under the third set of hours. 

Screenshots incoming.

**Comment by drewvolz** [comment]
We’ve made progress on finding out how the divider gets drawn. Tracking the issue over at https://github.com/Purii/react-native-tableview-simple/issues/32

**Comment by drewvolz** [comment]
Closed by #1441
