### ISSUE TITLE
Calendar detail view's description should be multi line

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1192]
It's currently restricted to a single line. 

![image](https://user-images.githubusercontent.com/464441/27166703-307d1e24-5162-11e7-810c-cdb2c6fff90d.png)

**Comment by drewvolz** [comment]
It also strips out the HTML for descriptions that are “see more detail” links and removes the URLs. Probably should turn those into linkable rows, too.
