### ISSUE TITLE
Settings crashes from old navigation calls

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1195]
Need to replace the last of the  `this.props.navigation.push` calls with `this.props.navigation.navigate`. Found rows that push new views in Settings that are still referencing the old navigator calls which causes the app to hang and crash in the beta.

**Comment by hawkrives** [comment]
Which rows? I swear I got them all…

**Comment by hawkrives** [comment]
(Or just fix them and show me that way :))

**Comment by drewvolz** [comment]
FAQ, credits, privacy, and legal.

**Comment by hawkrives** [comment]
Dang. Thanks.

**Comment by hawkrives** [comment]
Bad flow. You should catch these things lol.
