### ISSUE TITLE
Add "Powered By …" text to each remote data source's list's detail view

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1217]
Like the calendar, Student Orgs, dictionary, building hours.

Ideally with a link so the user can at least have some inkling of who’s responsible for each kind of data. 

- [x] Building Hours detail
- [x] Important Contacts detail
- [x] Bus routes list
- [x] Student Orgs detail
- [ ] Calendar detail
- [x] Dictionary
- [ ] Student Work detail
- [x] "Other Modes" list

---

-  ~~Streaming~~
-  ~~Menus?~~
-  ~~News?~~

I removed Streaming, Menus, and News because their either don't have a detail view or it's so different from the others that I believe it should be handled separately (news).

**Comment by elijahverdoorn** [comment]
Like as the last item in the list? I'd be down for that.

**Comment by hawkrives** [comment]
This will be much easier once the SectionList/FlatList PRs are merged.

**Comment by hawkrives** [comment]
I added a checklist to the OP
