### ISSUE TITLE
Call buttons work but do not prompt

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#124]
3 out of 4 of the Contact resources are fairly important numbers that we don't want to spam with accidental dials, so I believe we should add a confirm (yes/no) modal popup alert that asks if they really want to dial the number.

I am speaking from experience -- I have received a lot of blank support emails because it does not ask if you want to send the email or not -- it simply sends. Let me know your thoughts.

**Comment by drewvolz** [comment]
This is fixed by #125.

**Comment by elijahverdoorn** [comment]
Closing as fixed. Thanks @drewvolz.
