### ISSUE TITLE
Navigation bar buttons too small

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#126]
@hawkrives and I agree that we need to adjust the sizes of the navigation buttons, both icons and text. The target is too small to hit perfectly every time.
- [x] Adjust size of navbar buttons and icons
- [x] Align navbar buttons and icons

---

testing auto-checking of issues
- [ ] Android (#151)
- [ ] iOS (#148)

**Comment by elijahverdoorn** [comment]
Agreed, especially the alignment part. This is important enough for me to add to v1.

**Comment by elijahverdoorn** [comment]
I'll look at this one.

**Comment by hawkrives** [comment]
Good luck!

**Comment by elijahverdoorn** [comment]
Aannnddd.... I give. I'm terrible at CSS on the web, RN layout is no different. I'd love if someone better gave it a try. I did not, however, try importing something like this: https://github.com/react-native-community/react-native-navbar, which might be a good idea.

**Comment by hawkrives** [comment]
I'll … put some time into it tonight. It's frustrated me for long enough. Please expect it to be fixed tomorrow.

**Comment by hawkrives** [comment]
actually I really like that component. I may well end up using it / something similar. Thanks for finding it!

**Comment by elijahverdoorn** [comment]
If that's the solution that we want to use, I can do that if you'd rather put time in elsewhere.

**Comment by hawkrives** [comment]
nah, I'll just fix things there tonight. There are some other small improvements I want to make to the navigation at the same time – like having "Back" say where it will go, instead of always saying Back. Shouldn't take too long.

ex. 
in any of the sections, "< Back" becomes "< Home".
in News, "< Back" becomes "< News".

**Comment by elijahverdoorn** [comment]
This should be closed by #151 and #148

**Comment by elijahverdoorn** [comment]
Done!
