### ISSUE TITLE
Do we use the Important Contacts images in the app anywhere?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1294]
Wondering.

**Comment by drewvolz** [comment]
We don’t use them from what I can see.

**Comment by drewvolz** [comment]
I’m wanting this view to transition into having less walls of text in favor of a more navigable directory.

**Comment by elijahverdoorn** [comment]
Currently I don't think we use them.

If I'm correct, this is the only view that has survived since 2.0 without major changes to the UI, so it's probably due for a change. 😄

**Comment by drewvolz** [comment]
I'd say we nix the photos.
