### ISSUE TITLE
Important Contacts should hyperlink hyperlinks

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1297]
![image](https://user-images.githubusercontent.com/464441/28349058-247ff24a-6c06-11e7-839f-f550f6ffe592.png)

**Comment by hawkrives** [comment]
Work on this is happening in the `linkify-urls` branch.

![image 2017-08-05 00 06 59](https://user-images.githubusercontent.com/464441/28993058-015fc99c-7972-11e7-8247-39d1caa95ee4.jpg)

**Comment by drewvolz** [comment]
Closed by #1358

**Comment by hawkrives** [comment]
Closed by #1357 / #1356
