### ISSUE TITLE
Transportation "Open Map" is broken (Android, 2.4β11)

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1299]
See [the error in BugSnag](https://app.bugsnag.com/gobbldygook/all-about-olaf-1/errors/596edfe4a83b40001b21319b) for crash logs.  Seems to be something up with `react-native-maps`.

**Comment by hawkrives** [comment]
![img_0408](https://user-images.githubusercontent.com/464441/28367497-ccfced56-6c56-11e7-8acc-d0ad79519abc.PNG)

Another view of the error.

**Comment by drewvolz** [comment]
Something something update google play services in `build.gradle`? 

https://github.com/airbnb/react-native-maps/issues/1051
https://github.com/airbnb/react-native-maps/issues/1408
https://github.com/airbnb/react-native-maps/issues/1028

**Comment by hawkrives** [comment]
The maps are disabled, yeah? (Yeah.)

I'm going to push this back to v2.6; it's a bug, but I'm fine shipping without fixing it since there's no way to trigger it that I know of.

**Comment by hawkrives** [comment]
I'm going to close this; we'll run into it again when we actually enable a map somewhere.
