### ISSUE TITLE
SIS

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#13]
> Low priority for v1, since it is rather complex.
- ~~Course searching~~ (v2)
- [x] Browsing of current enrolled courses
- [x] Card balances
  - [x] Flex dollars
  - [x] Ole dollars
  - [x] Copy/print
- [ ] Meal Plan
  - [ ] Daily meals left
  - [ ] Weekly Meals Left

**Comment by elijahverdoorn** [comment]
I'm looking to @hawkrives or @drewvolz for this one, since they are the ones that started it and might have some experience? Guessing here, but I know that I know nothing about it.

**Comment by hawkrives** [comment]
~whee

(just fyi - leaving it to us is kinda dangerous. you never know what we'll come up with around the SIS. you might want up one morning to find Gobbldygook shoved in there 😉)

Sure, we've got it.

**Comment by elijahverdoorn** [comment]
If this becomes the deployment platform for Gobbldygook, I'd be honored.

**Comment by hawkrives** [comment]
I've thought about it. I could at least integrate it with GB's course data tools, and GB also has a lot of the parsing stuff for SIS's course views… perhaps it's time to break that stuff out so other projects can use it.

Hmm.

If I do decide to go forward with that, I'll file an issue here first, or at least talk about it in Slack.

**Comment by hawkrives** [comment]
Questions (@drewvolz @elijahverdoorn):
- [ ] Do we want course searching? I can do at least as much as https://stolaf.edu/sis/public-aclasslab.cfm can.
- [x] We want enrolled courses for at least the past year (feature parity)
  - [x] Enrolled courses since college enrollment?

(Looking for thoughts for / reasons not to do these things.)

**Comment by elijahverdoorn** [comment]
Course searching is a must have.
Past year is a must have.
Since college enrollment is something that I'd consider to be targeted for
version 2, I'd prefer to put time into other areas.

**Comment by hawkrives** [comment]
I will begin thinking about how to do a mobile search interface then.

**Comment by drewvolz** [comment]
I think we will need some form of persistent local storage equivalent of Objective-C's NSUserDefaults for storing user information securely. OBJ-C AAO stored the user's username, password, student id, their 'logged-in/out' status, and financial data (ole/flex/print) in that storage. We will also need to think about where to save the user's other important data -- their term courses (as JSON or something else), meals left, etc. 

There are a few options: [react-native-keychain](https://github.com/oblador/react-native-keychain) may replicate the functionality of NSUserDefaults for secure storage, and [AsyncStorage](http://facebook.github.io/react-native/docs/asyncstorage.html) could be used for not-so-secure items.

**Comment by hawkrives** [comment]
We'll probably want to start with keychain. Adding AsyncStorage for other app settings wouldn't be bad though

**Comment by hawkrives** [comment]
passcode https://github.com/naoufal/react-native-passcode-auth
touchid: https://github.com/naoufal/react-native-touch-id
1password: https://github.com/DriveWealth/react-native-onepassword

keychain: https://github.com/oblador/react-native-keychain

storage:
- https://github.com/wkh237/react-native-fetch-blob
- https://github.com/tradle/react-native-level-fs
- https://github.com/lwansbrough/react-native-multipeer
- https://github.com/llanox/react-native-assets
- ? https://github.com/wwayne/react-native-user-defaults

stuff: https://github.com/gcanti/tcomb-form-native

better list view: https://github.com/sghiassy/react-native-sglistview

**Comment by drewvolz** [comment]
With your handy list of things that we should implement, I never realized how many components make up that module until now.

Cool list!

**Comment by drewvolz** [comment]
Was the [third link](https://github.com/lwansbrough/react-native-multipeer) under `storage` meant to be a package for chatting? App-wide chat would be neat, though.

**Comment by drewvolz** [comment]
Check this [campus-guide](https://github.com/joseph-roque/campus-guide) out. might be useful for SIS-related functionality? As well as the [UCSD](https://github.com/UCSD/now-mobile) one for the sake of  react-native campus apps

**Comment by drewvolz** [comment]
Following up here with an update... I have tabs in-place, and a few views on the Balances screen in place. This is in the spirit of [Hawken's mockup](https://github.com/StoDevX/AAO-React-Native/pull/30#issuecomment-238126633).
<img width="375" alt="sis" src="https://cloud.githubusercontent.com/assets/5240843/17761420/fd5a2a70-64d4-11e6-8b3a-415c24649308.png">

**Comment by hawkrives** [comment]
We're working on loading financial data into the view in the [`moar-sis`](https://github.com/StoDevX/AAO-React-Native/tree/moar-sis) branch. That part's almost ready.

Then we'll move on to meal plans, and finally enrolled courses. It's coming along!

**Comment by drewvolz** [comment]
If we are really ambitious, we could refresh the data with [tween animations](https://www.npmjs.com/package/react-native-tween-animation)

**Comment by hawkrives** [comment]
ⓝⓞ

good idea though

**Comment by drewvolz** [comment]
<img width="375" height="690" alt="sis-bad" src="https://cloud.githubusercontent.com/assets/5240843/17829527/60df469c-667f-11e6-89cb-4139afd750d8.png">
