### ISSUE TITLE
Catch network errors when loading data

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#131]
Currently, network errors just kinda bring the whole app to a halt. We should catch the errors and either return cached data, or switch to an offline view, depending on the data.

**Comment by hawkrives** [comment]
I'm also thinking about adding caching functionality to the news and calendar views. It's not hard, and it'd speed them up.

**Comment by drewvolz** [comment]
Excellent idea. Any way to make it a component that can be included in every view that fetches data? Some universal way to display a notification that we have had network errors without interrupting the flow of the app?

**Comment by hawkrives** [comment]
… Maybe. I don't think there's a NetworkError type, but I'll look around for something. 

I've been thinking that it'd just go in the "catch" clauses of the data fetching functions, which I'm trying to pull out of the components anyway. 

See the SIS fetching stuff.

**Comment by drewvolz** [comment]
I get that. I meant a visual component on our end to consistently display a view or notification as a result of the catch.

**Comment by hawkrives** [comment]
I'm going to close this, as there's nothing actionable here. Future discussion should go in a new issue.
