### ISSUE TITLE
Don't release new nightlies if nothing has changed 

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1313]
Travis currently is releasing new nightly builds every night, even if we haven't committed that day. 

I would like to figure out how to avoid that. 

I'm not sure if we can, though; on hockey, I did this via the changelogs, but I don't think I have access to old TestFlight changelogs.

**Comment by hawkrives** [comment]
My current idea for this is to check the git log to see if any commits were made in the 24 hours prior to the build's start time. We can get the start time with the travis API, https://docs.travis-ci.com/api#builds

```http
GET /repos/sinatra/sinatra/builds HTTP/1.1
User-Agent: MyClient/1.0.0
Accept: application/vnd.travis-ci.2+json
Host: api.travis-ci.org
```
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "builds": [
    {
      "commit_id": 6534711,
      "config": { },
      "duration": 2648,
      "finished_at": "2014-04-08T19:52:56Z",
      "id": 22555277,
      "job_ids": [22555278, 22555279, 22555280, 22555281],
      "number": "784",
      "pull_request": true,
      "pull_request_number": "1912",
      "pull_request_title": "Example PR",
      "repository_id": 82,
      "started_at": "2014-04-08T19:37:44Z",
      "state": "failed"
    }
  ],
  "jobs": [ ],
  "commits": [ ]
}
```

**Comment by rye** [comment]
Superseded by #2584.  (This issue is older, but the new issue doesn't concern Travis—it's a separate more philosophical issue.)
