### ISSUE TITLE
Build for production

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#134]
This looks like a useful resource for building for production (note: haven't read it yet)

https://medium.com/android-news/preparing-a-reach-native-android-app-for-production-f063413d5633

Also, the actually useful official docs: http://facebook.github.io/react-native/docs/signed-apk-android.html

and for iOS: http://facebook.github.io/react-native/docs/running-on-device-ios.html#building-your-app-for-production

**Comment by hawkrives** [comment]
ok so building for iOS boils down to "build Release, not Debug".

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Build-for-production).
