### ISSUE TITLE
Prevent duplicate sections in student work list

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1343]
We need to group items into case-agnostic sections. So we either need to toUpper or toLower the data and the section header comparison. This is currently visible in the student work list with one item which has a lowercase header.

The problem is illustrated below:

**o**n-campus non-work study
**O**n-campus non-work study

This would create two different sections for the same group.

**Comment by hawkrives** [comment]
so we actually do that

[`views/student-orgs/list.js#L104`](https://github.com/StoDevX/AAO-React-Native/blob/master/source/views/student-orgs/list.js#L104):
```js
          $groupableName: head(startCase(sortableName)),
```

https://lodash.com/docs/#startCase

**Comment by hawkrives** [comment]
but good catch

**Comment by drewvolz** [comment]
You are referencing Student Orgs, and I am referencing Student Work.

**Comment by hawkrives** [comment]
oops
