### ISSUE TITLE
Open job postings

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#135]
I am not completely sure if this would fit into the spectrum of functionality we would like to provide, but I know finding student job opportunities can be a bit of pain. What if we made that easier, too?

I am imagining we could add a `student work` component to the app with two tabs. The first tab would be the Time Entry System that is being discussed in #74, and the second tab could be an optimized view of St. Olaf's [Student Employment job search tool](https://www.stolaf.edu/apps/stuwork/index.cfm?fuseaction=Search).

I cannot imagine it being too difficult to scrape the data from the dropdowns (job type, office, hours per week) and then to take input from the user for job title. Constructing the search query from this, we could perfrom a POST query, fetch the results, and display them in a ListView.

This would be a nice future addition to the proposed TES component.

**Comment by hawkrives** [comment]
I don't know if it would be used enough to be a full-fledged tab component, but we could possibly … ooh. 

What if the TES view started out with a list of jobs, and said list included an option for, like, "find a new job" or something - which would then open this view.

**Comment by drewvolz** [comment]
I like that idea, a lot actually. Could even take it as fas as presenting two buttons

[ ] I have a job
[ ] I am looking for a job

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Open-job-postings).
