### ISSUE TITLE
KSTO view crashes on iOS

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1376]
To reproduce: open the Ksto view on iOS, wait about 10 seconds.

Something in here is requesting data over the network, as I can see the network spinner spinning.

**Comment by drewvolz** [comment]
I'd say the network request is a correlation... just because we ripped out the uplink checking. I'm clueless as to what else could be causing the crash... something in `react-native-video`?

**Comment by hawkrives** [comment]
… can we just embed a WebView that iframes the player? would that work? would it play in the background?

**Comment by drewvolz** [comment]
`react-native-video` merged the fix for this a minute ago. Let's hope for a version bump, or else we'll fork it until then.
