### ISSUE TITLE
Organize data files by API version

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1383]
We should copy all the current api files into a `data/v1` folder, so we can make backwards-incompatible data changes in the future if we need to.

**Comment by elijahverdoorn** [comment]
Should we semantically version these, so that each release gets a new folder name? I picture a global function `getDataFolder()` or similar so that we don't have to keep track of the mapping between app version and data api version.

**Comment by hawkrives** [comment]
I mean, I don't see a need for anything other than major versions in an api contract

**Comment by hawkrives** [comment]
But yes, breaking changes would be a new major version increment in the api version

**Comment by hawkrives** [comment]
Closing, since our API data now comes through ccc-server (as of v2.6), which is versioned.
