### ISSUE TITLE
Landscape alphabetlistview is cut off

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1393]
I think we were thinking about replacing this component.

<hr>

**Orgs alphabet list**

<img src="https://user-images.githubusercontent.com/5240843/29055374-26ce64cc-7bca-11e7-81ce-cc81a042cc39.PNG" />

**Dictionary alphabet list**

<img src="https://user-images.githubusercontent.com/5240843/29055375-26cedf9c-7bca-11e7-82c6-446d8b693001.PNG" />

**Comment by hawkrives** [comment]
What does Apple do here? I think they start skipping every second letter or something when there's not enough space.

**Comment by hawkrives** [comment]
This isn't going to make 2.4.

**Comment by drewvolz** [comment]
Closed by #3987
