### ISSUE TITLE
Landscape building hours images are not wide enough

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1395]
They do not expand to the full width of the view. Calculation bug with the parallax view?

<img src="https://user-images.githubusercontent.com/5240843/29055563-239d6b1c-7bcb-11e7-84bc-a679bdf64ec7.PNG" />

**Comment by hawkrives** [comment]
It's probably caching the width of the device at startup time… that's going to be my go-to explanation for a while I think.
