### ISSUE TITLE
Oleville

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#14]
> Display content from Oleville. Currently targeting reading posts for v1, will expand for future versions.

**Comment by elijahverdoorn** [comment]
I'm taking care of this one.

**Comment by elijahverdoorn** [comment]
Development happening on branch [oleville-view](https://github.com/StoDevX/AAO-React-Native/tree/oleville-view)

**Comment by hawkrives** [comment]
Closed by #96.
