### ISSUE TITLE
Weekly Movie Info

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#141]
Pull it + display it.

**Comment by elijahverdoorn** [comment]
Moving this one back to a later version. If it makes this version, great, but it's not a priority.

**Comment by drewvolz** [comment]
Where would we "pull" the data from? Oleville API? Static JSON url updated on github in our `data` folder?

**Comment by elijahverdoorn** [comment]
There is usually a post on Oleville about the movie, that post will show up in the Oleville view. As for pulling it separately, I guess I could do some stuff with categories and tags on the server, then pull from that.

**Comment by drewvolz** [comment]
Right -- the latter answer is what I was going for. Figuring out a method to query Oleville for the data.

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Weekly-movie-views).
