### ISSUE TITLE
SIS username/password labels

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#145]
Need dynamic positioning of these. This was my bad way of doing it.

<img width="349" alt="screen shot 2016-08-23 at 8 30 18 am" src="https://cloud.githubusercontent.com/assets/5240843/17891817/1ef9e522-690c-11e6-9816-d07d6bdf3a5d.png">

**Comment by hawkrives** [comment]
Closed by 2e6938d. (github will auto-close when #148 lands)

**Update:** Or maybe it won't.
