### ISSUE TITLE
Strange keychain bug

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#146]
I would expect the keychain to not fail. This came from entering an incorrect username/password into the Settings login, submitting, and then changing to correct credentials and trying to login.

<img width="361" alt="screen shot 2016-08-23 at 8 34 41 am" src="https://cloud.githubusercontent.com/assets/5240843/17891939/a814ae14-690c-11e6-82c8-96200be1a9f0.png">

**Comment by drewvolz** [comment]
After downloading iOS 9.3 and adding a new simulator, I can confirm this is only reproducible on iOS 10.0. Thanks @hawkrives for the idea.

This does not make sense, as we can run it on the physical device running iOS 10.0 but the simulator cannot?

**Comment by hawkrives** [comment]
We're going to have to figure this one out for v2, since iOS 10's due for release in Sept.
