### ISSUE TITLE
Strange padding with ListView and TabbarIOS

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#147]
- [ ] Transportation/Transit
- [ ] Webcams

We've noticed that our solution of bumping up the margin/padding on the ListView seems to backfire in two known-instances. The scrollbar and content do not agree. 

We thought we could fix it using [this explanation](url) which suggests using this to fix the ListView

`<ListView
  contentInset={{bottom:49}}
  automaticallyAdjustContentInsets={false}
`

But that did not work. It's not above the bottom, but it's at the bottom. And adding padding brings us right back where we started.

**Comment by hawkrives** [comment]
Closed by #168.
