### ISSUE TITLE
Unknown building hours should be obvious

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1470]
If we are unsure of building hours, we default to closed. We could be more clear about them by removing the open/closed badge from them.

**Comment by hawkrives** [comment]
Or we could just remove them from the list. What use cases do they serve by being there otherwise?

**Comment by drewvolz** [comment]
The case where someone who knows them can hit the "edit" button and suggest them.

**Comment by hawkrives** [comment]
What about for offices that we don't have an entry for?

I would argue that we should solve that problem, and then remove the unknown building hours. 

(Also, what buildings do we have with unknown hours? I thought we got them all?)

**Comment by drewvolz** [comment]
There’s quite a few that lack them
