### ISSUE TITLE
Loading screen's storyboard doesn't landscape

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1476]
<img width="667" alt="screen shot 2017-08-27 at 10 02 47 pm" src="https://user-images.githubusercontent.com/464441/29757727-9e5e378e-8b73-11e7-930b-ec26bcd9839b.png">

**Comment by drewvolz** [comment]
I’ve seen that before but didn’t attribute it to the loading screen. Good catch.

**Comment by hawkrives** [comment]
This also exhibits itself when you reload the app, but I believe that they are separate causes.

**Comment by hawkrives** [comment]
meh. Bug, but "just" graphical; I'm going to push it back, but I'd accept a fix into 2.5.

**Comment by drewvolz** [comment]
I don't see this as an issue any longer. The bar is taller than what gets rendered, but I no longer see what was in the screenshot above.

**Comment by hawkrives** [comment]
I can no longer reproduce this. @drewvolz, can you?

**Comment by drewvolz** [comment]
Closing.
