### ISSUE TITLE
Remote news css is not applying

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1493]
Introduced in #1490, a remote stylesheet is supposed to be injected from github pages.

**Comment by drewvolz** [comment]
The link to the styles is incorrect. It expects a CSS file, but I’ve produced a JSON file. The current data is https://stodevx.github.io/AAO-React-Native/news-styles.json.

**Comment by hawkrives** [comment]
Oh, riiiight. We'll want to generate two files from the single input file - a css file, for remote loading, and a json file, for local inclusion.
