### ISSUE TITLE
Transportation

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#15]
> This will just be a list of options, with it calculating and displaying time until the next bus (when the busses are running)

**Comment by hawkrives** [comment]
@elijahverdoorn:

> […] I intentionally want this view to be really simple, since we can't possibly cover all the modes of transport and we don't want to cover others. The biggest thing is the bus schedule and VanGo. We're not adding the Northfield Lines schedule, since they are not St. Olaf affiliated. Same for the rental cars and any kind of taxi.

**Comment by elijahverdoorn** [comment]
See the transportation branch's JSON for the latest bus data. I'm thinking that if we displayed a list of the transportation options, as in the transportation.json file, and the next bus at all locations (as found in bus-times.json) we'd be good for v1.

**Comment by drewvolz** [comment]
And as far as the transportation view for buses, I was thinking that the bus schedule data could be represented in a "tube" schedule progress view? If either of you have ideas that differ, let me know. But I envisioned a progress bar status with stops along the way and a blinking rectangular bar indicating what percentage of the way the bus is supposedly at between the two points. Just the first idea to come to mind. I'll include a mockup in the near future.

There is also this [bus-follower](https://github.com/clayton-shopify/bus-follower-react) which could be cool, as well as the [react-native-bus-query](https://github.com/siger-young/react-native-bus-query).... and finally, there is [this](https://github.com/UCSD/now-mobile/blob/dev/app/views/ShuttleStop.js).

**Comment by drewvolz** [comment]
In light of doing something with simplicity in mind, [this one](https://github.com/marcin-mazurek/pocketable) strikes me as pretty close to ideal.

**Comment by elijahverdoorn** [comment]
I agree that simple is good, but I am a little afraid of using a component that seems inactive. For now, if it's not hard, let's go with it, we can redo later if we have to. (Also - how would that look on iOS?)

**Comment by drewvolz** [comment]
Currently cannot get it to build, so I will see what I can do to extract the view components into our own app.

**Comment by hawkrives** [comment]
Speaking of Pocketable, should I contribute a TravisCI config?

**Comment by elijahverdoorn** [comment]
I'm going to work on this while I wait for advice on the push notifications.

**Comment by hawkrives** [comment]
Sounds good.
