### ISSUE TITLE
Manual dictionary differ

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#150]
Need a simple script to notify AAO developers/support that words have been modified on the following pages. This way we can keep our dictionary data up-to-date without spending time on it.
- [A-G](http://wp.stolaf.edu/sa/a-g/)
- [H-O](http://wp.stolaf.edu/sa/h-o/)
- [P-Z](http://wp.stolaf.edu/sa/p-z/)

**Comment by hawkrives** [comment]
Happening in https://github.com/StoDevX/stolaf-dictionary-definitions.

**Comment by hawkrives** [comment]
mwahahaha https://github.com/StoDevX/stolaf-dictionary-definitions/pull/1

**Comment by hawkrives** [comment]
(that's an automated update.)

The thing is done. It will run once a day and look for updates to the html. If it finds any, it'll submit a PR to github.com/StoDevX/stolaf-dictionary-definitions with the changes.

**Comment by drewvolz** [comment]
Thank you @hawkrives !
