### ISSUE TITLE
Add Northfield News

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1514]
Sadly it is not `https`

**Site:**
http://www.southernminn.com/northfield_news/

**Feed:**
http://www.southernminn.com/search/?f=json&t=article&c=northfield_news&l=50&s=start_time&sd=desc

**Comment by drewvolz** [comment]
On the fence with this. It has _some_ good stories... finding out the Reub is closing, a new clinic is opening, etc. I dunno. Thoughts? I thought it would be an interesting parallel because we include a northfield calendar, so why not a northfield news.

**Comment by hawkrives** [comment]
I will note that they appear to sell subscriptions with a "10 article per period" limit, so…

**Comment by drewvolz** [comment]
It seems we can request 3,093 entries from their JSON feed, and anywhere from 1 - 100 articles at a time before pagination.

**Comment by hawkrives** [comment]
I'm talking about philosophical/ethical objections, not technical, here.

![screen shot 2017-09-06 at 1 46 05 pm](https://user-images.githubusercontent.com/464441/30128865-bef388d0-9309-11e7-8d09-252b427bd92c.png)

**Comment by drewvolz** [comment]
Abstaining.

**Comment by hawkrives** [comment]
Perhaps we should reach out to them and see about integrating their site into the app – either free for all (last 10 articles or something) or allowing the user to log in.

In the future, of course.
