### ISSUE TITLE
Add "Building hours subject to change without notice" to detail screens

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1517]
I'm just envisioning it in the footer, like the footer text on the list views.

We should put this here, in part because we're usually late with the updating of the hours, and in part because the college puts this notice on most of the printed hours sheets that it has.

I'd like this to make 2.4, so that it's out in the wild sooner.

**Comment by drewvolz** [comment]
Do you feel that covers the issue of break hours?

**Comment by drewvolz** [comment]
https://github.com/StoDevX/AAO-React-Native/pull/1505#pullrequestreview-60466311

**Comment by hawkrives** [comment]
No, I do not.
