### ISSUE TITLE
Remove the menus filterbar and add a "Filter" button to the toolbar

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1522]
The toolbar began life because we couldn't add buttons to the toolbar easily. 

Now, we can!

So it should go away.

**Comment by drewvolz** [comment]
Right. And we discussed that information the toolbar displays (date, menu) can be moved underneath the current title. I think this is a good compromise to cut down on the amount of toolbars.

**Comment by hawkrives** [comment]
Right, so I'm envisioning something like Telegram does, where we'd move the information from the toolbar into a second line beneath the title.

**Comment by hawkrives** [comment]
I think this can be closed, now that we have a very fancy Filter toolbar! (Introduced in #2744)
