### ISSUE TITLE
Event detail view's title is "See more details"

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1526]
![e9020deb-b15e-4cbc-92d4-fdfce419969f](https://user-images.githubusercontent.com/464441/30214554-893b3408-9472-11e7-9421-a173ca337d16.png)

**Comment by drewvolz** [comment]
Only for the St. Olaf Calendar. I’ll fix that.

**Comment by drewvolz** [comment]
The fix for this is to _not_ use `event.summary` and instead use `event.title`.
