### ISSUE TITLE
Express Bus schedule for Sunday is incorrect

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1538]
For reference, this is the proper schedule linked on the website as of 2017-09-10: ![[Bus Schedule]](https://wp.stolaf.edu/sa/wp-content/blogs.dir/78/files/2012/08/Express-Bus-2016.jpg)

[data/bus-times/express.yaml](https://github.com/StoDevX/AAO-React-Native/blob/a1a9776a3847a0c46464f1431376f35497e9efe8/data/bus-times/express.yaml) is the file affected.  It appears that the times shifted forward two hours from what is currently reflected.

**Comment by hawkrives** [comment]
Wow, they sure did! Thanks!

**Comment by rye** [comment]
PR is up in #1539.

**Comment by drewvolz** [comment]
Great catch @rye
