### ISSUE TITLE
Filter bar view lacks view title

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1549]
The view for filtering has a blank title on menus

**Comment by hawkrives** [comment]
It's probably, add `navigationOptions` to https://github.com/StoDevX/AAO-React-Native/edit/master/source/views/components/filter/filter-view.js, then add a new "title" option or something to the `.push` in fancy-menu.js

https://github.com/StoDevX/AAO-React-Native/blob/3eb588c8a6cc616d038bbd55828a2056636979ce/source/views/menus/components/fancy-menu.js#L73-L78

Then edit the navigationOptions in filter-view.js to use the new option to set the title.

**Comment by drewvolz** [comment]
Thanks for the hints, @hawkrives
