### ISSUE TITLE
Settings button can be pushed multiple times

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#155]
> It is weirdly possible to hit the settings button quickly enough to summon multiple instances of the settings menu. They appear to be pushed onto the view stack. I can mash the mutton 4 or 5 times, and  become stuck in that state and cannot pop-back. If you push another view (credits/privacy/legal) you can get it to let you pop the settings view.

I'm thinking … disable the settings button after a tap?

But why does it take so long to open?

Hmm.

(oh lol drew suggested disabling the button too. it's a stopgap fix, at least.)

**Comment by drewvolz** [comment]
I wonder if there is a prop to speed up the animation of this menu. Investigate [this demo](https://rnplay.org/apps/HPy6UA) to see if we can apply this configuration to our transition.

**Comment by hawkrives** [comment]
This is happening again. I don't know why; the current solution _should_ work – it's global variables, c'mon!

**Comment by drewvolz** [comment]
Being worked on in [`fix-buttons-again-again`](https://github.com/StoDevX/AAO-React-Native/tree/fix-buttons-again-again)

Edit: this branch got deleted...?

**Comment by drewvolz** [comment]
- Can confirm that rapidly tapping edit or settings pushes multiple views
- Can confirm that sequentially tapping edit and settings pushes multiple views
- Can confirm that sequentially tapping any of the home buttons pushes multiple views

**Comment by hawkrives** [comment]
@elijahverdoorn Can you replicate this?

**Comment by hawkrives** [comment]
Fine, I can replicate. 

We are doing better than we did before, though; pushing multiple views doesn’t let you go back to a blank screen anymore.

**Comment by hawkrives** [comment]
@drewvolz Yes, the branch was deleted, because nothing was happening and master had changed drastically.

**Comment by drewvolz** [comment]
@hawkrives can we close this? I think we agreed that opening things multiple times is FAD.

**Comment by hawkrives** [comment]
fear, anticipation, and doubt?

**Comment by drewvolz** [comment]
Functions As Designed

**Comment by hawkrives** [comment]
ah.

Yes.

I've only managed to trigger it twice out of the last ~18 tries, and that's me tapping as quickly as I can attempting to trigger this.

I don't think it's worth the effort to fix, I suppose. I am in favor of closing.
