### ISSUE TITLE
Change streaming tab order?

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1550]
I’m thinking webcams or streaming events should appear before KSTO.

1. - Webcams
    - Streaming
    - KSTO
2. - Streaming
    - Webcams
    - KSTO

**Comment by drewvolz** [comment]
Thoughts? @hawkrives @rye @elijahverdoorn @mattk410 @erichkauffman

**Comment by rye** [comment]
Since "streaming" actual events seems like it might be one of the more important things to users, that'd be my guess, so option 2 (Streaming, Webcams, KSTO) seems the best option to me personally.

**Comment by hawkrives** [comment]
I'll second @rye's opinion.

**Comment by elijahverdoorn** [comment]
Agreed.
