### ISSUE TITLE
iOS Heroku onboarding link broken 

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1554]
https://boarding-aao.herokuapp.com/ 

> **Application error**
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by hawkrives** [comment]
Fixed.

It had the old iTC credentials, and I wound up with a new iTC user just for that app, as I can't use my credentials – `boarding` doesn't support 2fa currently.

and it's arguably better to have a separate user anyway.
