### ISSUE TITLE
Bus list UI not auto refreshing 

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1563]
The bus lists are not updating the UI automatically.

**Comment by hawkrives** [comment]
Define "not updating the UI". Just times, just the dot, anything?

**Comment by hawkrives** [comment]
Well, darn. it's really not updating anything.

I did confirm last night that the building hours list does work.

**Comment by hawkrives** [comment]
I think it's that I set the `setInterval` back to 5000 accidentally, instead of 1000.

https://github.com/StoDevX/AAO-React-Native/blob/cd024d356ae855d2c242891a6b58aa778594b267/source/views/transportation/bus/bus-view.js#L36

**Comment by drewvolz** [comment]
Changing the interval did not fix this issue.

**Comment by hawkrives** [comment]
Sigh.

**Comment by drewvolz** [comment]
I believe the problem is within the return. Setting it to `true` fixes the UI update issue @hawkrives 

https://github.com/StoDevX/AAO-React-Native/blob/cd024d356ae855d2c242891a6b58aa778594b267/source/views/transportation/bus/bus-line.js#L103-L113

**Comment by hawkrives** [comment]
Oh. Yes.

**Comment by hawkrives** [comment]
Lets play a game - can you find the bug of what's not changing there?

**Comment by drewvolz** [comment]
All three comparisons are constantly returning false, so I'm going to blame something in `nextProps` or `nextState`.

**Comment by hawkrives** [comment]
`currentMoments` is the list of time strings. When the minutes change, the list of times won't always change – it'll only change when an iteration of the bus' route is complete.

I'll add another check to the busLine shouldComponentUpdate.
