### ISSUE TITLE
Metadata and contact info

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1568]
I think metadata and contact info within the app needs to be updated. I think I found them all, but someone should double-check.

1. Information related to @elijahverdoorn needs to be switched to @hawkrives
2. Information related to `sgawebmaster@stolaf.edu` needs to be switched to @hawkrives or `allaboutolaf@stolaf.edu`
3. Information related to `odt@stolaf.edu` needs to be switched to `allaboutolaf@stolaf.edu`

**Support URL**
* [x] [http://oleville.com/support](http://oleville.com/support)
  * please switch this to email `allaboutolaf@stolaf.edu` if it is not already

**Fastlane App Info**
* [x] [fastlane/**Appfile**](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/Appfile)
  * `odt@stolaf.edu` should reference `allaboutolaf@stolaf.edu` or @hawkrives 
* [x] [fastlane/metadata/en-US/**marketing_url**)](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/metadata/en-US/marketing_url.txt)
  * Change to github repo. We already list it for contributing in the app, so why not?

**Fastlane Release Notes**
* [x] [fastlane/metadata/en-US/**release_notes.txt**](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/metadata/en-US/release_notes.txt)
  * `odt@stolaf.edu` should reference `allaboutolaf@stolaf.edu` or @hawkrives 

**Fastlane Review Info**
* [x] [fastlane/metadata/review_information/**first_name.tx**t](https://github.com/StoDevX/AAO-React-Native/blob/2116f398dfbac6190b038ca48b5c939a5bdae991/fastlane/metadata/review_information/first_name.txt)
* [x] [fastlane/metadata/review_information/**last_name.txt**](https://github.com/StoDevX/AAO-React-Native/blob/2116f398dfbac6190b038ca48b5c939a5bdae991/fastlane/metadata/review_information/last_name.txt)
* [x] [fastlane/metadata/review_information/**email_address.txt**](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/metadata/review_information/email_address.txt)
* [x] [fastlane/metadata/review_information/**phone_number.txt**](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/metadata/review_information/phone_number.txt)

**Fastlane Trade Representative**
* [x] [fastlane/metadata/trade_representative_contact_information/**address_line1.txt**](https://github.com/StoDevX/AAO-React-Native/tree/master/fastlane/metadata/trade_representative_contact_information/address_line1.txt)
* [x] [fastlane/metadata/trade_representative_contact_information/**email_address.txt**](https://github.com/StoDevX/AAO-React-Native/tree/master/fastlane/metadata/trade_representative_contact_information/email_address.txt)
* [x] [fastlane/metadata/trade_representative_contact_information/**first_name.txt**](https://github.com/StoDevX/AAO-React-Native/tree/master/fastlane/metadata/trade_representative_contact_information/first_name.txt)
* [x] [fastlane/metadata/trade_representative_contact_information/**last_name.txt**](https://github.com/StoDevX/AAO-React-Native/tree/master/fastlane/metadata/trade_representative_contact_information/last_name.txt)
* [x] [fastlane/metadata/trade_representative_contact_information/**phone_number.txt**](https://github.com/StoDevX/AAO-React-Native/tree/master/fastlane/metadata/trade_representative_contact_information/phone_number.txt)
* [x] [fastlane/metadata/trade_representative_contact_information/**trade_name.txt**](https://github.com/StoDevX/AAO-React-Native/tree/master/fastlane/metadata/trade_representative_contact_information/trade_name.txt)
* [x] [fastlane/metadata/en-US/**privacy_url.txt**](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/metadata/en-US/privacy_url.txt)

**Comment by hawkrives** [comment]
Can't remove the - SGA from the app name.

I think the release notes are for the already published release notes, so we won't change those.

**Comment by hawkrives** [comment]
A lot of the others would be fixed if I could figure out how to pull them down again.

**Comment by hawkrives** [comment]
`Appfile` already references me.

**Comment by drewvolz** [comment]
> I think the release notes are for the already published release notes, so we won't change those.

A copy-paste might cause that again, so that's why I noted it.

**Comment by hawkrives** [comment]
Speaking of the NoticeView… we should probably make that markdown-enabled so we can have clickable links in it. But that could come later.

**Comment by drewvolz** [comment]
> Appfile already references me

Please read my comment again.

```
# Contact odt@stolaf.edu or another admin if you need access.
```

**Comment by drewvolz** [comment]
> Can't remove the - SGA from the app name.

You can. It is the "localizable" name that is updated on each new version of the app. It is set each time the app updates, and that is why I linked to the place we're setting it inside of [fastlane/metadata/en-US/**name.txt**](https://github.com/StoDevX/AAO-React-Native/blob/master/fastlane/metadata/en-US/name.txt).

**Comment by hawkrives** [comment]
> https://github.com/StoDevX/AAO-React-Native/issues/1568#issuecomment-328996002

Sorry, I misread the email you linked as "sgawebmaster", which I did remove when I took over the account.

**Comment by drewvolz** [comment]
Bump?

**Comment by hawkrives** [comment]
You can PR the text files, @drewvolz :p

**Comment by hawkrives** [comment]
What do we actually need to do here, @drewvolz ?

**Comment by drewvolz** [comment]
I will take charge of updating these
