### ISSUE TITLE
Text in Important Contacts should be centered

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#158]
like in Transportation.

**Comment by elijahverdoorn** [comment]
Would we rather do that, or left justify the text in transportation? I think that it's easier to read if it's left justified.

**Comment by elijahverdoorn** [comment]
We also have the expandable lists in Dictionary left justified, I'd rather keep them all the same.

**Comment by hawkrives** [comment]
Ok. I'll revert the change in Transportation.

**Comment by hawkrives** [comment]
I'll do that on `master` after #148 is merged.

**Comment by elijahverdoorn** [comment]
Thank you.
