### ISSUE TITLE
Discussion: Think about how to pull more URLs from Github

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1588]
After the last three main views go to being pulled from github (see #1562, #1585, and #1586), our next challenge will be to pull even more stuff from Github.

Stuff like:
- the URLs that we use in the tabbed views (think News' feed URLs, or calendar)
- the cafe ids used in the Menus view
- the URLs for the link-type homescreen buttons

---

Before any of that happens, though, I'm going to insist that we figure out how to cache these requested items offline, so that the cached version takes precedence over the bundled version in an offline situation.

---

Looking through the app, I think the next challenge isn't pulling just the URLs for resources from Github.

It's essentially pulling app configuration.

Take News, for example. 

https://github.com/StoDevX/AAO-React-Native/blob/fea68224abd9e184ac231363e92419013adc62ad/source/views/news/index.js#L19-L26

https://github.com/StoDevX/AAO-React-Native/blob/fea68224abd9e184ac231363e92419013adc62ad/source/views/news/index.js#L52-L58

We have two types of News tabs: RSS and WordPress. 

We need to not only configure the endpoint, but also the props that are sent to that tab. Or, take the Calendar; in a few weeks, the Olaf calendar will have a more detailed non-Google calendar that I'll write an adapter for, and we'll want to be able to switch that out for the Google version if needed.

---

Potentially, we could even configure the tabs that are shown within a screen, remotely. Take the stuff in News at https://github.com/StoDevX/AAO-React-Native/blob/2a8a33369410a3ce8893f6ae63b0e9ee9b7c198e/source/views/news.js, for example – we could pretty much configure the entire app remotely, just changing what we show in the tabs and screens that are bundled with the app.

This is something to think about, but who knows if it'll go anywhere.

**Comment by drewvolz** [comment]
> Potentially, we could even configure the tabs that are shown within a screen, remotely.

Yes!

**Comment by hawkrives** [comment]
Most of this has been solved by moving to ccc-server (in v2.6).

The rest of the _title_ of this issue is tracked in https://github.com/frog-pond/ccc-server/issues/46.
