### ISSUE TITLE
Add the Flaten Art Museum?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1593]
https://wp.stolaf.edu/flaten/visit/

> Monday–Wednesday, Friday: 10 a.m.–5 p.m.
> Thursday: 10 a.m.–8 p.m.
> Saturday–Sunday: 12 p.m.– 4 p.m.
> Closed during the summer, holidays, and college breaks.

**Comment by drewvolz** [comment]
Sure
