### ISSUE TITLE
Request iOS Background Audio permission

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1597]
for playing KSTO in the background

Or we should ensure that we can play it in the background.

**Comment by hawkrives** [comment]
Apparently … we don't need this.  At least, I get audio (well, white noise) in the background on iOS, both with rn-video and WebViews.

**Comment by hawkrives** [comment]
we already had it

thanks @drewvolz 

https://github.com/StoDevX/AAO-React-Native/commit/a78938ea433bb39cfeaf7e5814742d1cb49dadfa

which was part of https://github.com/StoDevX/AAO-React-Native/pull/1285

**Comment by drewvolz** [comment]
Thanks for checking.

**Comment by drewvolz** [comment]
The current implementation is not backgrounding audio. Probably because we're not using a native streaming library?

**Comment by hawkrives** [comment]
That should be filed as a new issue; the fade-out at the end of the music makes me believe that it's a problem with how we handle the webview, not an inherent limitation of the approach.
