### ISSUE TITLE
KSTO streaming not working over http

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#162]
Loading the `https` version of the KSTO streaming service does _not_ work. It loads over `http`.

**Comment by hawkrives** [comment]
Oh for the love of… Fix it! 😜

**Comment by hawkrives** [comment]
(Because you're the old webmaster.)

**Comment by drewvolz** [comment]
Okay, I fixed it by logging into KSTO and changing the link to request the `https` resource.

As a followup, perhaps we would want to load _just_ the stream from [https://www.stolaf.edu/multimedia/play/embed/ksto.html](https://www.stolaf.edu/multimedia/play/embed/ksto.html). It loads better into a responsive view for the time being. I was tasked to provide a new theme to KSTO, but the media plugin on the new theme that plays on every page does not support our HLS stream from streamguys. So we're stuck with the one we have for now.

That being said, let's _actually_ change links to the one hosted by www.stolaf.edu

**Comment by drewvolz** [comment]
Also, should we talk with KSTO before including this in here?

**Comment by hawkrives** [comment]
… It uses flash, doesn't it.

**Comment by hawkrives** [comment]
I would like to load as small a page as possible.

**Comment by hawkrives** [comment]
Which links are on www.stolaf.edu?

**Comment by drewvolz** [comment]
The one I listed that we switch to. https://www.stolaf.edu/multimedia/play/embed/ksto.html

**Comment by hawkrives** [comment]
oh. Does that play anything on your computer at the moment?

**Comment by drewvolz** [comment]
The station is currently silent. No shows are happening at this moment and the computer DJ isn't playing.

**Comment by hawkrives** [comment]
ok
