### ISSUE TITLE
Draft final 2.4 release notes

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1638]
I've been taking notes per each beta in the Releases tab.

**Comment by hawkrives** [comment]
First draft

---

Hi Oles! Wow, it's been a while.

First off, we haven't fixed the SIS balances yet – we're working together with the college to make sure it's correct before it turns on again.

NEW FEATURES
- Building Hours editor! If you see some hours that are wrong, let us know!
- Full size iPad app! It's really just the iPhone one, stretched out, but it's a lot nicer.
- A calendar detail view! And, sharing events from the calendar! And, adding events from the calendar to your phone!
- KSTO Radio???
- A Streaming Events list!
- A list of student work positions!

BUG FIXES
- Webcams work again!
- Bus schedules are correct again! We've also made it so we can update them separately, so they shouldn't be out of date for so long in the future.

CHANGED
- Redesigned the Important Contacts page!

**Comment by rye** [comment]
@hawkrives, do you prefer people to edit the draft?  Or copy/paste a new version?  Is there someplace better?  (E.g. Wiki?, or are we able to see other people's draft release notes?)

**Comment by drewvolz** [comment]
Sometimes we use [the wiki](https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes)...

**Comment by hawkrives** [comment]
Wiki is fine
