### ISSUE TITLE
Can't scroll on home edit screen

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1641]
Since there's more tiles to sort through than just one screen's worth, I'd like to be able to scroll through the list in the Home Edit view and move tiles at the bottom of the list.  But, it seems like the tile grab happens if you touch _anywhere on the tile_, not just on the location where I'd expect to grab on the right-hand side.  Since the touch event gets stolen by the tile mover, the view is unable to be scrolled.  Is anyone else having this issue?  Is there any way where we could either (i) set up margins on the sides so that we can scroll the list from outside of the tiles, or (ii) only make tiles move around when they're grabbed on the bit on the right?

(I'm on Android `2.4.0-beta.14+4186`)

Edit: Here's some screenshots for proof:

| Grabbing anywhere on the tile | Grabbing on the right side of the tile |
| --- | --- |
| ![screenshot_20170917-152513](https://user-images.githubusercontent.com/1566689/30524649-6f92ad04-9bbd-11e7-914b-9367814b350b.png) | ![screenshot_20170917-152631](https://user-images.githubusercontent.com/1566689/30524650-6f935312-9bbd-11e7-9508-791f708a1a5b.png) |

**Comment by hawkrives** [comment]
… you used to be able to scroll unless you long-pressed. I'll investigate later today.

**Comment by rye** [comment]
Oh, you still can.  Now that you mention it, I can scroll if I flick the screen.  Can we increase the timeout on the long press?  It doesn't feel long enough to me. (>1 second is what I would expect)

**Comment by rye** [comment]
Poking it further, it seems like sometimes I neither scroll nor move a tile, too.  (After a successful scroll down I have to try multiple times to get it to scroll up.)

**Comment by drewvolz** [comment]
I'm sure we could adjust what is considered flick vs grab target territory...

**Comment by hawkrives** [comment]
I've got a new suggestion: what if, for the sake of expediency, we replaced the drag and drop behavior on Android with up/down buttons per row?

@rye / @elijahverdoorn how bad of an idea is that? I know it's not terribly consistent with the platform, but it'd be simple to do, and we don't know what's going on with the current implementation.

**Comment by elijahverdoorn** [comment]
@hawkrives It would be better than broken functionality, but *really* inconsistent with the rest of what the platform expects. We should find another package to replace it, or find a more permanent solution quickly.

This page describes what material design says about list controls: https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by hawkrives** [comment]
@elijahverdoorn I knoooooow… 

The only other reputable-ish package that I've found is that one that @drewvolz PR'd a few days ago and recommended that we not use. 

I'm only suggesting up/down buttons because I don't know what else to do…

**Comment by rye** [comment]
Do we really have to ditch it for something else?  If only I could get the app to build on my laptop, maybe I could troubleshoot...

See, [react-native-sortable-list](https://www.npmjs.com/package/react-native-sortable-list) (which is what we use for the Sortable List on the HomeEditView) has a `rowActivationTime`. (which defaults to 200 ms)  My guess is that this is all some issue with this parameter.

**Comment by rye** [comment]
It's also worth noting that [react-native-sortable-listview](https://www.npmjs.com/package/react-native-sortable-listview) which is the other major option available to us, has less overall parameters available.  I'd much rather work with the existing solution—if necessary, I could try forking and PRing upstream.

**Comment by elijahverdoorn** [comment]
Forking the current package would be an ideal solution, @rye.

@hawkrives I agree, you asked what I thought as an Android person. I understand the realities of our situation, it's not a very highly-used feature so I'm not *super* concerned about it.

**Comment by hawkrives** [comment]
@rye We actually use a fork of the package, currently – I guess you could also try upstream again, but IIRC whenever we try upstream, even more things break. Things like scrolling. On both platforms.

**Comment by rye** [comment]
Um... Yeah, looks like we're using [hawkrives/react-native-sortable-list](/hawkrives/react-native-sortable-list).  Which is... 76 commits behind upstream?

Looks like you just added `prop-types`-related stuff, right, @hawkrives?  If so, should that get PR'd upstream?  Or can we PR upstream into your fork?  Something so we have the latest version of `react-native-sortable-list` in the wild, with perhaps some work on top of that?

I have created a branch locally for testing related to this, both using vanilla upstream RNSL and I have also created [a fork of @hawkrives' RNSL](/rye/react-native-sortable-list) that updates to match the latest.

**Comment by drewvolz** [comment]
@rye something something we've had a bad experience using the latest version of that component, so we forked and left it in a "stable" state. The last I checked, there was an issue when moving items around. Items would be shuttled downwards/upwards when pressing and holding on a row. We felt the issue was big enough to pin the repo to our forked version. _Even if that thing was "resolved", I think I found it still happening._

I'm absolutely open to reevaluating which source we use if that has changed.

**Comment by drewvolz** [comment]
Here's what happens on the latest `react-native-sortable-list` when it's not pinned to 76 commits behind upstream.

<img height=700 src="https://user-images.githubusercontent.com/5240843/31041871-6bc65516-a56a-11e7-8726-47999e522e61.gif" />
