### ISSUE TITLE
Home screen has less padding beneath the buttons than on the sides

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1651]
I’ll attach a screenshot in a bit.

**Comment by drewvolz** [comment]
@hawkrives can we see a screenshot, please?

**Comment by hawkrives** [comment]
<img src="https://user-images.githubusercontent.com/464441/30671157-1ad3e646-9e2b-11e7-8fda-0e3293a37b6b.jpeg" width=400>
