### ISSUE TITLE
Markdown list items’ bullets aren’t centered vertically 

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1652]
Screenshot to follow.

**Comment by drewvolz** [comment]
@hawkrives can we see a screenshot, please?

**Comment by hawkrives** [comment]
<img src="https://user-images.githubusercontent.com/464441/30671175-2f9312f0-9e2b-11e7-9e7e-b2cfe0914ede.jpeg" width=400>

**Comment by hawkrives** [comment]
By adding `alignItems="baseline"` to the ListItem class, I've achieved the following:

<img width="319" alt="screen shot 2018-01-14 at 4 03 28 pm" src="https://user-images.githubusercontent.com/464441/34921197-848e5ef8-f944-11e7-891a-bebceb47ed4e.png">

**Comment by hawkrives** [comment]
@drewvolz How's this look?

<img width="320" alt="screen shot 2018-01-14 at 4 48 53 pm" src="https://user-images.githubusercontent.com/464441/34921625-d9145a3a-f94a-11e7-8333-d6e607208797.png">

**Comment by hawkrives** [comment]
Closed by #2132
