### ISSUE TITLE
Parse orgs descriptions for emails, in addition to links

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1653]
Example screenshot incoming.

**Comment by drewvolz** [comment]
Might as well do that in student work openings, too.

**Comment by drewvolz** [comment]
@hawkrives can we see a screenshot, please?

**Comment by hawkrives** [comment]
<img src="https://user-images.githubusercontent.com/464441/30671168-2614e06e-9e2b-11e7-8a9b-9a676a49a73d.jpeg" width=400>

**Comment by drewvolz** [comment]
Closed by #2401
