### ISSUE TITLE
Implement Native KSTO view

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#167]
Instead of loading the KSTO website, we should implement something along the lines of the KSTO app inside this view. (Because interacting with webviews kinda sucks, and it really _kills_ our memory usage.)

I don't think it'll take much to make a native view, but I want to push it back from v2. Either v2.1 or v2.2. I'd be willing to either take this, with Drew, or your team could build up their skills until they're comfortable tackling it.

But, we need something for v2.0. Here's what I'm thinking:

From Drew:

> KSTO already has the shared URL scheme information in it’s plist to be opened by the current AAO. And since we’re not changing app identifiers… it would work to just “open” it from iOS.

So. Since KSTO currently has an app, until we develop a nice native, streaming equivalent for AAO, I think we should put in a nice advertisement for the KSTO app on iOS. We would query the system to figure out if the app is installed; if it is, we show a button to open it. If it's not, we show two links: one to the app store page, and one to the web site (opens in Safari).

Since there's no KSTO app on Android, I think we should only add a link to the website (opens in Chrome).

Thoughts, @elijahverdoorn, @drewvolz?

(Supercedes #162.)

**Comment by elijahverdoorn** [comment]
I'm going to talk to KSTO about what they want from their app, and if they would be interested in coming under the AAO banner. I had some meetings with SGA leadership and they're interested in that idea. We have some sway since SGA funds KSTO. For the mean time, I like the above plan, but would also be ok with the current webview... (even though it kinda sucks.)

**Comment by hawkrives** [comment]
I would _very much prefer_ to not have the webview. If Drew and I can't get it working without, we'll ship with the webview. We'll won't put this ahead of fixing the other outstanding issues, but we'll work on it on the side.

**Comment by elijahverdoorn** [comment]
A little bit of this is done in #176, mostly as a holdover in place of the webview.

**Comment by elijahverdoorn** [comment]
I talked to KSTO and have confirmed their desire to have this done. Once AAO has feature parity with the KSTO app, we have permission to get rid of the KSTO app entirely and direct people to AAO.

**Comment by hawkrives** [comment]
@drewvolz found some neat stuff:

[http://stolaf-flash.streamguys.net:8091/radio](http://stolaf-flash.streamguys.net:8091/radio)

---

|status|returned condition|
---|---|
**UP** | `json.uplink` is true && `json.msgrate` > 25
**UP*** | `json.uplink` is true
**DOWN** | `json.uplink` is false
**# of listeners** | `json.counts.total`

**Comment by hawkrives** [comment]
I guess we'd also want to add the Background Audio permission for iOS at some point.

**Comment by hawkrives** [comment]
This has been implemented-ish.

Enough that I'm going to close it.
