### ISSUE TITLE
Rename and update Green Bikes to Ole Bikes

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1683]
🚲

**Comment by rye** [comment]
I can take this one if nobody else has started on it.

**Comment by hawkrives** [comment]
Go ahead!

**Comment by rye** [comment]
[The "Green Bikes" page](https://wp.stolaf.edu/sa/transportation/greenbikes/) should probably get updated to reflect the change in naming?  In any event, I'm working on this right now.

**Comment by hawkrives** [comment]
@rye It probably should.

**Comment by drewvolz** [comment]
It also shouldn't instruct to "search The Bridge” over on bridge.carleton.edu
