### ISSUE TITLE
Add disclaimer to SIS balances screen about the app not being the source of truth

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1692]

**Comment by drewvolz** [comment]
I want a disclaimer in the form of an Alert. Should also have a navigation button item to trigger the Alert.

**Comment by hawkrives** [comment]
Why? What does an alert get us over a small ListFooter at the bottom of the screen?

**Comment by drewvolz** [comment]
I think it makes a world of difference. I don’t want to treat this like a “Terms of Use” section that people don’t read. I want to be clear as can be to let people know this might not be correct info and any academic office is not to be blamed or contacted for it.

**Comment by hawkrives** [comment]
I strongly believe than a button you have to push to show an alert will be read less than a constantly present short notice.

**Comment by drewvolz** [comment]
An alert should appear the first time, regardless of text being in the footer or presentable from the nav bar.

**Comment by drewvolz** [comment]
> a button you have to push to show an alert will be read less than a constantly present short notice.

You can’t guarantee someone will even make it to the bottom of a list. It’s only present if someone even makes it to the end. That is not a fair assessment against the navigationbar button.

**Comment by hawkrives** [comment]
I'm talking about the Balances screen – the only device that it lets you scroll on is a 4s.

I'll agree with an alert the first time.

**Comment by hawkrives** [comment]
(New idea: use ARKit/ARCore to present a 3d alert dialog over a live camera feed in the background of the view.)

**Comment by rye** [comment]
For SIS balances, I feel like having a disclaimer at the bottom similar to the building hours is a good idea.  But there should probably be a one-time alert when users first open that view after the update, to let people know what's up with their SIS balances?  I'd forego the alert if, post-#1696, we no longer have data de-sync problems.
