### ISSUE TITLE
Enzyme 3 for React 16 is out - integrate it and use it in tests

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1693]
- https://github.com/airbnb/enzyme
- https://www.npmjs.com/package/jest-enzyme
- react-native-mock

**Comment by hawkrives** [comment]
No - yes to testing, no to enzyme.

**Comment by rye** [comment]
Yes, `react-test-renderer` works for this?

**Comment by hawkrives** [comment]
Yeah
