### ISSUE TITLE
Building Hours text background is not transparent

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1694]
This behavior is not the same on other views, just this one.  Tapping and holding causes the container for the white text background to be shown in contrast with the darkened background.

| ~ | ~ |
|---|---|
| ![screenshot_20170926-072810](https://user-images.githubusercontent.com/1566689/30860395-9924fec6-a28c-11e7-9ceb-9ebb275f8712.png) | ![screenshot_20170926-072819](https://user-images.githubusercontent.com/1566689/30860405-a29aafaa-a28c-11e7-9858-6671b23d768d.png) |

**Comment by hawkrives** [comment]
I _think_ that reverting https://github.com/StoDevX/AAO-React-Native/commit/9e7d0070c98af5bd9d7af47a4f0afe6faf31e8af should fix this. 

We don't need it anymore, either; I only needed the list to not have a background when there was a footer, but the footer is gone now.

**Comment by rye** [comment]
Unfortunately, I haven't been able to get a simulator up and running, so I can't verify if this is the case, but I could branch to do this.

**Comment by hawkrives** [comment]
I've tested; that does fix it. Pushing branch now.

I can't quite get a screenshot, though, so no screenshots.
