### ISSUE TITLE
Remove the nested navigator from the Carleton menus screen

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1695]
- Having a nested stacknavigator within a tabnavigator results in confusing back-button names on iOS 
- also there's a problem with the view titles, maybe?

We should just let a tap on a Carleton row push a new view as normal, instead of trying to keep it within the tabnavigator.

**Comment by drewvolz** [comment]
We could change the titles to say the menu name. That would be a welcomed change on all of the menus, calendars, news feeds, etc.

The back button is a problem, tho, as it says “Home” when it will not take you back home. That’s where the nested navigator is an issue.

**Comment by hawkrives** [comment]
The titles should change when you change tabs, yes, but that is a separate issue to be filed.
