### ISSUE TITLE
Settings keyboard dismissal

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#170]
The keyboard for logging in to SIS does not dismiss if the Login button is tapped instead of the Done button on the keyboard.

<img width="361" alt="screen shot 2016-08-23 at 8 34 41 am" src="http://i.imgur.com/LFXqEWc.jpg">

**Comment by hawkrives** [comment]
No longer an issue, now that we're getting rid of the login fields entirely.
