### ISSUE TITLE
Student orgs uses LoadingView for the refresh spinner

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1711]
Should be a one-line change.

**Comment by hawkrives** [comment]
Orgs should, because there's no local data.

**Comment by drewvolz** [comment]
I'm saying `LoadingView` ... the whole view that says "Loading..." is being used as the refresh indicator Does that make sense?

**Comment by hawkrives** [comment]
There is no refresh indicator; the view uses the LoadingView to handle both "loading" and "refreshing" states. 

Yes? That is a bug.
