### ISSUE TITLE
Reset everything on Android does not restart the app

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1730]
Found thanks to https://github.com/StoDevX/AAO-React-Native/pull/1728/ when trying to see the SIS disclaimer. Not sure what's going on but iOS does not need to be refreshed.

**Comment by hawkrives** [comment]
To be clear – Pressing "Refresh App" in settings won't clear the Redux state on Android. 

You can replicate this by refreshing the app, properly (just quit it and relaunch it), then approving the SIS ack, then refreshing the app again (just with the button this time) and see that the SIS message thinks its still approved.

The Refresh App button still clears AsyncStorage and the keychain / keystore, on both platforms.
