### ISSUE TITLE
Minify data files

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1735]
This would have two key benefits:
- Resource requests would end up faster, which would make us and users happier.
- Network requests for our resources would take less data, which makes everyone involved in networking happier, not to mention costing our users less money.

I think this is a thing that definitely needs to get done, especially as we rely more and more upon network requests to update things in the wild with v2.4.  We should keep both un-minified and minified JSON around, but throw in an additional step of minifying our JSON files when we're done processing our data inputs.  Then, we can slowly or all-at-once transition to loading this data minified.

**Comment by hawkrives** [comment]
What point is there in keeping the un-minimized json? Why wouldn't we just generate minified json, so that all the app versions can take advantage of it right away?

**Comment by rye** [comment]
@hawkrives this is a good idea, and as I look into implementing this it seems more and more like it's better just to generate minified. (3 line change vs many more than that)

**Comment by rye** [comment]
Since this was such an easy change, I can put this in v2.4 instead.
