### ISSUE TITLE
Set our own custom User-Agent string

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1757]
We should do this.  This is a good way of telling what versions our users are using, among many other things.

**Comment by hawkrives** [comment]
I'd like to set it to `AllAboutOlaf/2.4.0 (Darwin; iOS 11.0.2; Build/4381)`, I think.

`AllAboutOlaf/{version} ({kernel}; {platform} {plat_ver}; Build/{build})`

I took that from the string "Mozilla/5.0 (Linux; Android 5.1.1; LGL44VL Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.116 Mobile Safari/537.36".

**Comment by rye** [comment]
How about something more like:
```
AllAboutOlaf/{version}+{build} ({kernel}; {platform} {plat_ver})
```

Couple of differences here:

- [RFC 7231 (HTTP) § 5.5.3](https://tools.ietf.org/html/rfc7231#section-5.5.3) says:

  > A sender SHOULD NOT generate information in product-version that is not a version identifier (i.e., successive versions of the same product name ought to differ only in the product-version portion of the product identifier).
  - So, when we do build nightlies and betas, I'd say that the `+{build}` number should be put together with the version number; the stuff in the parentheses is then just platform data.
- As a corollary, `+{build}` should only be appended for prereleases for distinguishing between alphas/betas; [SemVer says we shouldn't modify AAO after a release](http://semver.org/spec/v2.0.0.html#spec-item-3).)
  - Thus, we would be assuming that `{version}` is the fundamental unit of change, and subsequent `{build}` versions are just intermediate checkpoints.

**Comment by hawkrives** [comment]
that's actually easier to do, as the build number is appended and saved in the bundled package.json – so we've got one easy source for that info.

**Comment by rye** [comment]
React-Native doesn't give us much access to Platform information besides which version and what it is, but I'll have a PR soonish for this.

**Comment by hawkrives** [comment]
We probably don't need kernel anyway lol
