### ISSUE TITLE
Incorrect "Powered By" message on Oleville & Northfield calendars

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1774]
The "powered by" message on Oleville and Northfield calendars says it is provided by the St. Olaf Calendar. These two sources do not come from that calendar. I think we need to pass a prop into the calendar views to set that message.

**Comment by hawkrives** [comment]
lol. Whoops.

**Comment by hawkrives** [comment]
I agree with Drew's assessment.
