### ISSUE TITLE
Red/Blue lines run on weekend

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1780]
PR #1771 removed Saturday and Sunday from the Red/Blue lines. I think that is incorrect according to every schedule I can find for those routes.

**Comment by hawkrives** [comment]
@hannesmcman Thoughts?

**Comment by drewvolz** [comment]
I am unsure if it runs by request on Saturday/Sunday, or not at all.

**Comment by hawkrives** [comment]
You can't request the red and blue lines.

**Comment by drewvolz** [comment]
Alright, I’m wrong.

**Comment by hawkrives** [comment]
Looking at http://threeriverscap.org/transportation/hiawathaland-transit, it says that the Northfield routes are "Monday - Friday, 6:00 am - 6:00 pm". I'd agree that the routes are M-F.
