### ISSUE TITLE
SIGABRT in TCPIOConnection::_tlsProcessValidateServerCertificates(nw_tls_context*)

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1789]
## Error in all-about-olaf

**SIGABRT** in **TCPIOConnection::_tlsProcessValidateServerCertificates(nw_tls_context*)**

[View on Bugsnag](https://app.bugsnag.com/gobbldygook/all-about-olaf-1/errors/59e6145737450d0017104ff1?event_id=59e6145737450d0017104ff0&i=gh&m=ci)

## Stacktrace

    /usr/lib/system/libsystem_kernel.dylib:0 - ___pthread_kill

[View full stacktrace](https://app.bugsnag.com/gobbldygook/all-about-olaf-1/errors/59e6145737450d0017104ff1?event_id=59e6145737450d0017104ff0&i=gh&m=ci)

*Created by Frog Pond via Bugsnag*

**Comment by hawkrives** [comment]
Oh, thank you, Bugsnag, for that useful stack trace.

If any of you can't log in, let me know and I'll send you the login info.

**Comment by hawkrives** [comment]
This happened on 2.4.0, btw.

**Comment by rye** [comment]
I'm thinking this is an internal network-related TLS issue?  We probably should handle these kinds of exceptions, I suppose, if not just with a retry.

**Comment by drewvolz** [comment]
There have been major changes to the TLS subsystem in iOS 11. I wouldn't sweat it on our end.

**Comment by hawkrives** [comment]
Okay.
