### ISSUE TITLE
Android Tab Layouts Crashing

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#179]
Every time I switch to the second or third tab of a view on Android, the app crashes. 
_This is a urgent fix needed for 2.0.0._

**Comment by elijahverdoorn** [comment]
Can someone reproduce this issue? I have tried it on two separate emulators, same issue, but need to reconfigure my physical device so that I can test it on there.

**Comment by hawkrives** [comment]
I will attempt to reproduce.

**Comment by elijahverdoorn** [comment]
I have now reproduced this issue on all my possible testing devices. Investigating.

**Comment by elijahverdoorn** [comment]
I also deleted `node_modules` ran `npm i` and rebuilt the entire project, same result.

**Comment by elijahverdoorn** [comment]
@hawkrives Were you able to reproduce this?

**Comment by hawkrives** [comment]
My android phone was hiding all weekend. I just found it. (One would think that I would have learned to look in my backpack for missing things, but I digress.)

I'm at work right now, so I won't be able to try it until tonight.

**Comment by elijahverdoorn** [comment]
@hawkrives Alright, thanks for the update.

**Comment by elijahverdoorn** [comment]
I've done some digging with logcat and other android tools, came across an issue in the interaction between the tab-layout component and the react system. On a hunch I reverted out commit 2b85dc03725077157482af8d3bcc3b39ba1a1304, the merge of #171, deleted `node_modules`, ran `npm i` and rebuilt the project. It works for me now. I'm thinking that for v2.0.0 we should keep that revert, fix it on master, and move on. Thoughts @hawkrives @drewvolz?

**Comment by hawkrives** [comment]
Seems like it's that, or rework every screen to only have two tabs.

I guess we should file an issue on his repo and see if we can help fix it, too.

We should also try installing an RC on our devices and using it for a few days. My iPhone seems to have a tendency to not want to open the app after a few days.

**Comment by elijahverdoorn** [comment]
The second tab also crashes the app for me on the current version of RC here on github. I'll push the revert for us to test as well.

I agree that we can help him fix it.

I've been using it on a ipad for a few days now, no issues here thusfar, but I agree that testing it is super important. I _have_ to have a version up by Wednesday.

**Comment by hawkrives** [comment]
don't forget about app store review times: http://appreviewtimes.com/

**Comment by elijahverdoorn** [comment]
Nice site! I'm hoping that we can all test and be on board for a release sometime tomorrow, but I marked the submission deadline on #177 to account for the review times.

**Comment by hawkrives** [comment]
This is probably fixed by #294.
