### ISSUE TITLE
New OleCard balances data fetching API

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1792]
I just made a JSON endpoint for the OleCard check balances screen.

No longer will we suffer under the tyrrany of parsing HTML on it!

*cough*

Anyway.

Hitting https://www.stolaf.edu/apps/olecard/checkbalance/, logging in, and then `GET`ing https://www.stolaf.edu/apps/olecard/checkbalance/api.cfm will return a response that matches the following typedef:

```typescript
type MealPlanInfo = {
	plan: ?string,
	leftDaily: ?string,
	leftWeekly: ?string,
}

type AccountBalance = {
	account: string,
	numeric: number,
	formatted: string,
}

type OleCardBalances = {
	data: {
		accounts: Array<AccountBalance>,
		meals: ?MealPlanInfo,
	},
	error: ?string,
}
```

As an example, here is what I get when I open that page:

```json
{
  "data": {
    "accounts": [
      {
        "account": "STO Ole Dollars",
        "numeric": 3150,
        "formatted": "$31.50"
      }
    ],
    "meals": null
  },
  "error": null
}
```

**Comment by hawkrives** [comment]
I'd really like to get this in to 2.next, but I'll completely understand if we want to push it to 2.next+1.

If someone wants to do this this afternoon, I can cut an RC this evening, we can test, and then we can submit the build later tonight and hopefully have it approved tomorrow.

**Comment by rye** [comment]
I feel like this could go to 2.5 or 2.6, seems suitable.  Along with platform changes like RN upgrades, this'll give us a hearty amount of stuff to do.  But yeah, a JSON API beats HTML parsing any day.
