### ISSUE TITLE
Catch "cannot open mailto: urls" errors and alert the user

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1799]
## Error in all-about-olaf

**Error** in **main.jsbundle:17**
Unable to open URL: mailto:***@stolaf.edu

[View on Bugsnag](https://app.bugsnag.com/gobbldygook/all-about-olaf-1/errors/59e7c555be71a6001a70fef1?event_id=59e7c5af29fa37001a743db9&i=gh&m=ci)

## Stacktrace

    main.jsbundle:17 - l

[View full stacktrace](https://app.bugsnag.com/gobbldygook/all-about-olaf-1/errors/59e7c555be71a6001a70fef1?event_id=59e7c5af29fa37001a743db9&i=gh&m=ci)

*Created by Frog Pond via Bugsnag*

**Comment by hawkrives** [comment]
where ***@stolaf.edu == "rives@stolaf.edu", for example

This in on 2.4.0 as well.

**Comment by hawkrives** [comment]
I think we should add a try/catch somewhere (in openUrl, I guess) to check for these errors and ignore mailto:-caused errors.

**Comment by drewvolz** [comment]
Does the action happen, or does the app crash? What is the outcome of a failed `openURL` with a `mailto`?

**Comment by rye** [comment]
To me, it seems like this is something that we don't need to worry about; a failed `openURL` would result in the user not... getting any result from their action?  We could throw an alert in the UI.

It seems as though the result is a crash:

```js
{
  "code": 0,
  "exception_name": "EXC_CRASH",
  "subcode": 0,
  "exception": 10
}

// [...]

{
  "name": "SIGABRT",
  "signal": 6,
  "code": 0
}
```

My guess is that this crash is just because this exception bubbles up and ends up unhandled.

**Comment by hawkrives** [comment]
We should handle it and alert that the mailto link couldn't be opened, IMHO

**Comment by hawkrives** [comment]
I believe that our next step is to create a "sendEmail" function like our "openUrl" function; it should handle our common use cases (namely, a single author), and provide a central place to handle errors (such as showing an alert when the user can't handle `mailto:` URLs, or copying the email address to the clipboard, or something.)

Here are the places where we call the `email` function of `react-native-communications`. I don't think that we need to build our generic solution around that library.

```
source/views/settings/sections/support.js
29:    email(

source/views/student-orgs/detail.android.js
116:                onPress={() => this.openEmail(c.email, orgName)}
135:                onPress={() => this.openEmail(c.email, orgName)}

source/views/sis/student-work/detail.android.js
65:        onPress={() => email([job.contactEmail], null, null, job.title, '')}

source/views/building-hours/report/submit.js
17:    return email(
```

These spots use `openUrl(mailto:)`:

```
source/views/student-orgs/detail.ios.js
132:                  onPress={() => openUrl(`mailto:${c.email}`)}
```

These spots use `Linking` directly instead of going through `openUrl`:

```
source/views/student-orgs/detail.ios.js
3:import {ScrollView, Text, View, StyleSheet, Linking} from 'react-native'
117:                  onPress={() => Linking.openURL(`mailto:${c.email}`)}
131:                  onPress={() => Linking.openURL(`mailto:${c.email}`)}
```
