### ISSUE TITLE
Building Hours

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#18]
- [x] Move the label for what the location is inside the picture
- [x] Change the border color to Yellow when the building will close in 20 min.
- [x] Add the rest of the images
  - [x] @elijahverdoorn is going to Campus on 8/5 and will get them at that time.

**Comment by elijahverdoorn** [comment]
See PR 21

**Comment by drewvolz** [comment]
Hustad Science Library could be potentially disappearing soon. It is rumored to become the new Nursing department. But that really does not change anything right now as that is listed in the modifiable JSON. Yet another location added to the AAO space-hours graveyard. The current count is 2 (norway valley cafe in regents, and the old poetry spot in the bottom of Larson).

**Comment by hawkrives** [comment]
Wait, what happened to the International Coffee House?

**Comment by drewvolz** [comment]
If that was something, I was unaware of it. I'm referring to something that stopped before our freshman year that I discovered through the Ole Dictionary that failed to exist.

**Comment by elijahverdoorn** [comment]
Yeah, I heard about Sci Lib maybe going away, but as you said it makes no difference for this JS work.

**Comment by hawkrives** [comment]
The blue room in the bottom of Larson has a little sign over it's door that says "International Coffee House".

Apparently, it once actually sold coffee, kinda like Norway Valley. I have no idea when it closed down.

**Comment by elijahverdoorn** [comment]
Merged PR.
