### ISSUE TITLE
Send screen navigations to BugSnag as "breadcrumbs"?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1800]
Because our breadcrumb trail looks a little empty most of the time right now.

**Comment by rye** [comment]
This would be nice.  In general, logging navigations properly to analytics might also be nice.

**Comment by rye** [comment]
Seems like we can just do something like `bugsnag.leaveBreadcrumb`.  Read [here](https://docs.bugsnag.com/platforms/react-native/#logging-breadcrumbs) and [here](https://docs.bugsnag.com/platforms/react-native/customizing-error-reports/#adding-detailed-breadcrumbs).
