### ISSUE TITLE
KSTO for Android is stuck while starting the stream

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1805]
It does not go past the button message of "Starting". Works on iOS.

**Comment by drewvolz** [comment]
@hawkrives 
> It's never leaving "checking" means that the embedded webview is never emitting … anything. Checking is only set while the view is waiting for the <audio> tag to start doing something.

**Comment by hawkrives** [comment]
still an issue for Android

**Comment by rye** [comment]
With the ringer switch on silent, stream is "playing" (button says "pause") but with the ringer switch set to play audio, stream is stuck in "starting."

**Comment by drewvolz** [comment]
Should we hide the KSTO view from Android if we can't fix it?

**Comment by hawkrives** [comment]
_If_ we can't fix it, we should make the Play button open the website, I think

**Comment by rye** [comment]
@hawkrives and I poked around with this just now.  Seems like a good solution for the long term is just going to be to load the player in the background and forward events on through to the `<audio>` element that that player holds.  Should be minimal overhead.
