### ISSUE TITLE
Greenkeeper still not updating lockfile

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1817]
I'm suspicious of our decision to only build PR's and not Branches.  It makes sense, but it seems like it might be causing problems.  Here's why:

On the most recent Greenkeeper PR, #1816, which was built on [Travis:4556](https://travis-ci.org/StoDevX/AAO-React-Native/builds/293062277), the [.1 (JS-only)](https://travis-ci.org/StoDevX/AAO-React-Native/jobs/293062278) build passed, but [the relevant line in the build log](https://travis-ci.org/StoDevX/AAO-React-Native/jobs/293062278#L721) shows `greenkeeper-lockfile-update` complaining with:

```console
This build should not update the lockfile. It could be a PR, not a branch build.
```

Later on in the build, after the JS tests have passed, [when `greenkeeper-lockfile-upload` gets called](https://travis-ci.org/StoDevX/AAO-React-Native/jobs/293062278#L1733), it also fails with:

```console
'master' is not a Greenkeeper branch
```

Note that Travis _is_ set to building branch updates and pull requests at the moment.  However, I fear this might be something to do with our [branch build selector](https://github.com/StoDevX/AAO-React-Native/blob/978df27581ee14de20fdc6f0a77f9f21423d4907/.travis.yml#L69-L76): https://github.com/StoDevX/AAO-React-Native/blob/978df27581ee14de20fdc6f0a77f9f21423d4907/.travis.yml#L69-L76

I'm going to try enabling branch builds for `greenkeeper/` branches and seeing if that gives any success.  We could also try disabling PR builds for those branches as well.

**Comment by hawkrives** [comment]
You are correct that greenkeeper-lockfile checks for "not a PR build":

https://github.com/greenkeeperio/greenkeeper-lockfile/blob/94c544afa5546ba09735fb6ad15c5b57295a761a/ci-services/travis.js#L14

**Comment by rye** [comment]
Sure enough, I think that's what led me to believe that I should do #1818.
