### ISSUE TITLE
Leverage Build Stages to Pipeline the build

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1819]
Our CI build times are friggin' long.™

Not only are we at the whims and mercy of Travis' build infrastructure stability, (wherein a short outage can cause hours of slowdown) but MacOS build queue lengths are a serious problem across the platform, and the MacOS backlog regularly grows to ~800 builds during the day, so it takes at least a little while to build our app.  Meanwhile, Travis' Linux backlog is almost always hovering around zero.

I blame the fact that we're doing a lot of stuff in one big stage.  Travis' new Build Stages thing is nice, and we should use it to establish a pipeline.

Check out #1818 for some commentary by @hawkrives and @rye (me) about this.

**Comment by rye** [comment]
One con of this is that JS has to run before Android and iOS take off, but the pro to counter that is that Android and iOS _won't run unless JS passes_, which can save a lot of time in less certain circumstances.

**Comment by hawkrives** [comment]
Closed by #1820
