### ISSUE TITLE
SIS switched to Google OAuth

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#182]
SIS login is broken, we cannot login at the moment with OAuth being the authentication method. This is a shipping issue for the SIS functionality. #177 

How do we make sure the user can login with OAuth? 
- [The link that contains the link below](https://www.stolaf.edu/sis/login.cfm)
- https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fas%3Da97492d886b731b%26scope%3Dhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%2Bemail%26response_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2Fwww.stolaf.edu%2Fsis%2Flogin.cfm%26state%26hd%3Dstolaf.edu%26from_login%3D1%26client_id%3D368607578799-f5geh8k6l3km5et1ufbtusikso5sb7rj.apps.googleusercontent.com&btmpl=authsub&hd=stolaf.edu&sacu=1&scc=1&rip=1#identifier

**Comment by elijahverdoorn** [comment]
See #184

**Comment by hawkrives** [comment]
#184 is almost all of this. We still need two things:
1. [ ] The SIS view needs to handle the case where the token is revoked between requests. All invalid token errors (we know because we'll get the login page again) should result in the user being shown the Login screen again.
2. [ ] We need to investigate how long it the token lasts for. It's a `session` cookie, but I don't know what `session` means outside of the context of a web browser.

**Comment by hawkrives** [comment]
Ideally, we could get an OAuth token for the SIS itself (ish), which wouldn't expire until the user changed their password or revoked the token, but that's going to need to wait until we (Elijah) talks to IT.

**Comment by elijahverdoorn** [comment]
I have had users report the crash that we are working to fix. Just posting that here so that we know that users are noticing.

**Comment by drewvolz** [comment]
Hah yeah. They're definitely all going to notice because their cookie expires and then the SIS tab crashes

**Comment by hawkrives** [comment]
I'm reasonably sure that #192 is complete and working now.

**Comment by drewvolz** [comment]
I will defer my judgement to @elijahverdoorn if we would like to test this secondhand before integration. I'm currently without computer for the Labor Day weekend.
