### ISSUE TITLE
"You called setState() on an unmounted component."

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#183]
Loading a module of the app and then pressing back before the data loads causes this warning.

<img width="361" alt="screen shot 2016-08-23 at 8 34 41 am" src="http://i.imgur.com/9GSXIoL.jpg">

**Comment by hawkrives** [comment]
Whee. 

I'm honestly not sure how to deal with this. Just putting an isMounted check would still be subject to race conditions, and you can't cancel a promise. 

I'll do some research today.

**Comment by hawkrives** [comment]
btw this is why an `isMounted` check isn't enough: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

**Comment by hawkrives** [comment]
this is probably what I'll end up using – bluebird's promise cancellation and some code to cancel promises in `componentWillUnmount` – http://bluebirdjs.com/docs/api/cancellation.html

I'll take a stab at this after the SIS Oauth stuff

**Comment by hawkrives** [comment]
https://github.com/facebook/react/issues/2787#issuecomment-304485634

**Comment by hawkrives** [comment]
I'd like to close this – it's not really actionable, as stands, and I think that as we slowly refactor things to take advantage of hooks we will cause this less often.

**Comment by drewvolz** [comment]
I still see this issue, and I think we could solve it.

**Comment by drewvolz** [comment]
But alright. Closing.
