### ISSUE TITLE
News Tabs don't change content on Android

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#187]
In some of the limited tests that I have done, the news tabs don't change what content is shown in the list on android. It just stays at the first tab's content.

**Comment by hawkrives** [comment]
@elijahverdoorn Is this still a problem, with the new android tab component?

**Comment by hawkrives** [comment]
I believe that this has been resolved; see the attached GIF.

![out_small](https://cloud.githubusercontent.com/assets/464441/20233849/e6ba78d0-a839-11e6-9c79-9bfb8340fd38.gif)

**Comment by elijahverdoorn** [comment]
Yup, this works now. Nice GIF.
