### ISSUE TITLE
Forgot to update version number

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#188]
I forgot to update the version number in the settings menu, it still says "beta"

**Comment by drewvolz** [comment]
Speaking of versioning, the Android version on Google Play reports a version of 1.0. That's okay, right?

![image](https://cloud.githubusercontent.com/assets/5240843/18141941/70a3707c-6f89-11e6-9c10-5ec1caf8ea8f.png)

**Comment by elijahverdoorn** [comment]
I'll have to change that too - that's in `AndroidManifest.xml`

**Comment by hawkrives** [comment]
I'm going to tag this as #134, although it should be fixed separately. Are you keeping notes of how you're building and releasing these? I'm still interested in automating the release process as much as possible.

**Comment by elijahverdoorn** [comment]
@hawkrives Yes, I have a few notes about the process. It's not hard, but there are a bunch of steps, I'm interested in the release automation as well.
