### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#19]
> Minor UI Changes only.

**Comment by hawkrives** [comment]
I just committed some cleanups on `master`:
- I copied over the styles from Drew's ListView in News.
- I removed an extra View that just wrapped the ListView.
- I remove a view that wrapped the EventView, and let EventView take a set of styles.
- I turned EventView into a function component and removed all use of state
- I hid the time and location when they weren't available

**Comment by elijahverdoorn** [comment]
That was all I was going to do here for version 1, thanks. Closing.

**Comment by hawkrives** [comment]
lookit that progress bar go
