### ISSUE TITLE
Automate New Releases

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#190]
Not to the extent of #whatever, but to the point of "Eli can run a single terminal command to submit new builds to the Play Store and the App Store" would be wonderful.

We'd want two commands: 
- [ ] submit a new _release_ to the Play Store / App Store
- [ ] submit a new _beta_ to the Play Store / Testflight

The scripts should:
- ask for a new version number / type: `new version (major|minor|beta):`
- copy that version number into the appropriate places (package.json, Info.plist, manifest.xml)
- make a `git tag` for the release
- generate production builds for Android and iOS
- upload the builds to the appropriate stores

The scripts should not:
- handle creation of a `git branch` – that responsibility lies with the human
- handle CHANGELOG / release notes creation
- touch Codepush – that'd be separate set of scripts

**Comment by hawkrives** [comment]
Helpful resources for accomplishing this: 
- [playup](https://github.com/jeduan/playup) is a npm package for uploading `apk` packages to the Play Store

**Comment by hawkrives** [comment]
OH MY GOD

We need to use https://fastlane.tools

Like, yesterday.

**Comment by elijahverdoorn** [comment]
Things to consider here:
- Code signing - we need the keys for both iOS and Android
- Zipalign - This needs to be done and VERIFIED for Android only.

I'm sure that there are more things that I'll think of.
