### ISSUE TITLE
Webcam tiles show highlight on touch (again)

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1905]
Another introduction of #1648 reintroduced by #1901.

On press, the webcam thumbnails show a box around the rounded images. This is most likely from moving the padding and border-radius to the image instead of the touchable? Most likely fallout from some recent refactoring.

<img src="https://user-images.githubusercontent.com/5240843/32988824-680ef3d4-ccc9-11e7-95b6-b86a8767b89d.gif" width=350>

**Comment by hawkrives** [comment]
The padding isn't on the image though. The only margin/padding is on the touchable.
