### ISSUE TITLE
SIS login does not provide login feedback

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1907]
It appears to be stuck on “Logging in to St. Olaf” with incorrect credentials, not that I can test with anything other than that.

<img src="https://user-images.githubusercontent.com/5240843/32988762-f447a9ba-ccc7-11e7-926f-8bc510838a0c.jpeg" height=250>

**Comment by hannesmcman** [comment]
Closed by #2019
