### ISSUE TITLE
News detail not respecting viewport

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1909]
Looks zoomed out. Maybe the viewport is being ignored? Happens to more than just this screenshot.

<img src="https://user-images.githubusercontent.com/5240843/32988854-f99e281a-ccc9-11e7-811e-4152d3561f7d.png" width=350>

**Comment by hawkrives** [comment]
For me, it fixed itself when I opened another news story. I haven't figured it out yet.

**Comment by drewvolz** [comment]
It seems to work 40-50% of the time?
