### ISSUE TITLE
Pause Online Ordering

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#196]
This is a giant app within itself and a stretch/long term goal according to @elijahverdoorn. 

Something along the lines of React Native would probably be the right way to go. An online ordering experience that is closely tied or fully integrated with All About Olaf that provides a way to order items off of the Pause menu and place orders without calling or walking to the Pause first.

Need to check with future Pause Executives to see if they are willing or interested in online ordering. The first go-around with WPPizza caused headaches and didn't fit the kitchen's workflow.

Ideas:
- [Restaurant app template (for sale)](https://codecanyon.net/item/restaurant-app-template-react-native/17652082)
- [Indendent restaurant app skeleton](https://github.com/rnagella/HyderabadPalace?files=1)

**Comment by hawkrives** [comment]
Dup of #195.
