### ISSUE TITLE
Mess Articles only showing preview

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#198]
The mess tab of the new section only shows a part of the article, not the whole thing. If possible, we want to show the entire article, if that's not possible we should have a way to view the full story, either in a `webview` or using `linking` to open the whole thing.

**Comment by drewvolz** [comment]
We've asked Omar to provide the whole content.

**Comment by hawkrives** [comment]
Do we have any confirmation that Omar saw our message, @drewvolz?

**Comment by drewvolz** [comment]
Not that I can think of. I may have seen him online at the time we asked... so we need to ask again.

**Comment by elijahverdoorn** [comment]
Mentioning @OmarShehata

**Comment by OmarShehata** [comment]
Oh, I just saw this. (I think Slack would be an easier way to reach me? I've been keeping up with the conversation in Slack but have not seen this at all)

How/where do you need me to provide the full article? Where are you pulling it from?

**Comment by drewvolz** [comment]
Pulling the RSS from http://manitoumessenger.com/feed

**Comment by OmarShehata** [comment]
So all I need is to make the `description` tag just contain the full body of the article, and that will work for you guys, is that right?

Or maybe it'd be better to add a new tag for the full content.

**Comment by OmarShehata** [comment]
I'm kind of having trouble adding a custom RSS field, but I did put the full plain text article body in the description field, if that helps for now.

**Comment by hawkrives** [comment]
Sure, we'll check it out.

**Comment by hawkrives** [comment]
It works!

(I didn't even need to change anything 😁 – here's the release version.)

<img width="400" src="https://cloud.githubusercontent.com/assets/464441/18414952/ff21c324-7819-11e6-9afc-99ede64a5fdf.PNG">

**Comment by hawkrives** [comment]
We can probably close this – if you add HTML instead of plain text, we'll pick that up and use its formatting instead.

Thanks, @OmarShehata!

**Comment by elijahverdoorn** [comment]
Cool, Thanks @OmarShehata
