### ISSUE TITLE
Pressing keyboard "search" button on orgs / dictionary crashes app

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2039]
I was able to crash the latest beta on iOS

1. Open up student orgs or dictionary
2. Type something into the search bar
3. Hit the “search” button on the keyboard (notice keyboard doesn’t hide?)
4. Either swipe to dismiss keyboard or tap a search result
5. App crashes

**Comment by hawkrives** [comment]
Wonderful.

**Comment by hawkrives** [comment]
I need to update my fork of the package: https://github.com/umhan35/react-native-search-bar/commits/master
