### ISSUE TITLE
Ensure app doesn't crash when location is denied / after 5 seconds delay

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2053]
in the WiFi Reporting screen

**Comment by drewvolz** [comment]
I just ran it and did not see it crash after letting the prompt sit on my screen.

**Comment by hawkrives** [comment]
I just denied the app permission to have my location and it didn't crash.

I'll close this.

**Comment by rye** [comment]
Side note, @hawkrives, we/you should clear out the DB prior to the launch of this feature.

**Comment by hawkrives** [comment]
once the darn thing gives me access again, yeah

**Comment by hawkrives** [comment]
Your heatmap will also want to exclude things reported from prerelease versions (anything with a `-` in the version) as well as anything reported off-campus. Idle thoughts.
