### ISSUE TITLE
"Report a Problem" screen tweaks

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2054]
- rename to "Help"?
- add two more cards – maybe how to report something to the helpdesk, and to facilities?
- visual tweakses

suggestions welcome

**Comment by rye** [comment]
Sounds good.

Maybe we could also put text on the card, above the button?  A short description of what we're doing, why we need location access, etc.?

**Comment by drewvolz** [comment]
I'm addressing some of those things in a PR. One sec.

**Comment by drewvolz** [comment]
Feel free to add-on to that PR or suggest changes.

**Comment by drewvolz** [comment]
Would we consider what was done in #2061, #2063, and #2065 satisfactory? I think @rye was playing around with cards for helpdesk and facilities.

**Comment by hawkrives** [comment]
I'm working on those, as well as as remotely disabling / configuring the tools.
