### ISSUE TITLE
iOS EditHomeView rows can hide themselves

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2059]
There seems to be issues when moving around the rows on EditHome for iOS.

- The row can land in an "active" state (which looks strange)
- The row can hide beneath other rows (which is just not right)

This screenshot hopes to demonstrate both issues. This all takes place after having interacted with the screen — no finger is touching the screen in the image below.

<img src="https://user-images.githubusercontent.com/5240843/34641877-b5b04a88-f2c7-11e7-96e4-8e29197daddb.png" width=314 />

**Comment by hawkrives** [comment]
The "row hiding underneath another row" is not fixable by us in our timeframe; it's a problem with the underlying library.

The "toggle acts as drag handle" we should be able to fix.

**Comment by hawkrives** [comment]
Explore cherry-picking https://github.com/gitim/react-native-sortable-list/commit/83133563da84e9d3fbfbad83f499cbde836b03c1 onto my fork, and see if we can manually activate the row hover state when touching either the title or the drag handle, but not the switch.

**Comment by hawkrives** [comment]
I'm moving this to 2.6 because I now believe that both of the issues mentioned by @drewvolz in the OP are caused by the underlying library, and I don't have the energy to fix them.

**Comment by drewvolz** [comment]
Closing as this has been removed from the app.
