### ISSUE TITLE
react-navigation broke lazy tab loading on iOS and Android

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2093]
@drewvolz:

Going thru all of the tabs this morning, I get a strange feeling that News and Calendar (and maybe others) are loading all of their data for every tab once the component is pushed onto the stack.

v1.0.0-beta.23 has a breaking change noted: “Drop the lazy option for TabNavigator” https://github.com/react-navigation/react-navigation/pull/3064

**Comment by drewvolz** [comment]
@hawkrives mentioned that if there is an error in one tab, it could crash the app. That is not ideal if the user has not pressed the tab causing the error.

**Comment by drewvolz** [comment]
Do we risk crashing without lazy loading, or should we roll back to the previous version of this package?

**Comment by hawkrives** [comment]
Er. My mention was on _this_ version of react-navigation.

**Comment by drewvolz** [comment]
Yes. Should we go back a version to regain lazy load?

**Comment by rye** [comment]
From [that PR](https://github.com/react-navigation/react-navigation/pull/3064):

>I understand that it's still desirable to lazily load tabs, so I think it's time we implement focus events so that this can be implemented in userland.

Grumble grumble... [insert something Linus Torvalds-y about breaking userspace]

It sounds like they haven't... added an alternative for us to use?  So... yeah.  Downgrade sounds like the likely solution until they figure it out.

**Comment by rye** [comment]
[react-navigation@v1.0.0-beta.22](https://github.com/react-navigation/react-navigation/tree/v1.0.0-beta.22) does not have this issue.  It sounds like they plan on adding the feature later, but they went ahead and released this beta to drop it.

PR incoming to downgrade.

**Comment by drewvolz** [comment]
https://github.com/react-navigation/react-navigation/pull/3538
