### ISSUE TITLE
Prevent selected icon from resetting

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2094]
We should find a way to prevent the currently checkmarked row from resetting its icon if it’s already that icon. Pass this.state.iconType and see if it’s a checkmark like we do for accessory. 

https://github.com/StoDevX/AAO-React-Native/blob/master/source/views/settings/icon.js

**Comment by hawkrives** [comment]
I'd just not call this.setIcon if we're on the active icon.
