### ISSUE TITLE
Change duplicated home button gradients

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2139]
- `yellowToGoldDark` -> Moodle and SIS
- `lightBlueToBlueDark` -> Building Hours and Student Orgs
- `purpleToIndigo` -> News and Help

We should also add these hex values to the colors payload, too:

![sto colors](https://user-images.githubusercontent.com/464441/34950584-2d59d7b2-f9d9-11e7-8e74-f169e4a68fe6.png)

**Comment by drewvolz** [comment]
Thanks 🙏
