### ISSUE TITLE
Dictionary pronunciation guides

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#214]
@hawkrives had a nice thought. We should include pronunciation guides as a third item to dictionary entries that are formal nouns, or flat-out hard to pronounce. Some of our entries already include the pronunciation in the definition, but a lot of these words could still be difficult words to figure out.

**Comment by elijahverdoorn** [comment]
@ekmanzu is going to look into this one.

**Comment by hawkrives** [comment]
What format would we like? I'm partial to [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet), which is what dictionaries use as well.

We can probably find or write something to automatically pronounce IPA strings, too, since the symbols have a defined sound (see f.ex. [ipachart.com](http://www.ipachart.com)).

**Comment by elijahverdoorn** [comment]
I'm ok with whatever. I don't think we need to have it for all of the items, just the hard to pronounce ones (ytterboe, anyone?). Could we do a text-to-speech thing in addition to the pronunciations?

**Comment by hawkrives** [comment]
Drew and I have been researching this for the past half-hour… what we've found is that there's no good way to automatically pronounce an IPA string.

https://encrypted.google.com/search?hl=en&q=define%20hello has the IPA string underneath the definition, which I think would be all we'd need for the first effort.

Most places don't need a pronunciation, either, but I'm thinking Stav, Christiansen, and Ytterboe would be good places to start.

The IPA can just be shown; that's what paper dictionaries do, after all. I was hopeful when I wrote the first comment that there was something we could just include and do, like, `speak(str, {lang: 'ipa'})` when the user tapped a button, but nothing we've found so far can pronounce IPA strings.

So for now, let's just match paper dictionaries and include the IPA string? If Rika Ito is on campus, she's a linguistics prof; I think we have three linguistics profs. They can help you with IPA if you get stuck. Also the ipachart.com is helpful, once you've got the basics of IPA down.

<img width="658" alt="screen shot 2016-11-11 at 3 16 17 pm" src="https://cloud.githubusercontent.com/assets/464441/20230473/d0d7b57c-a821-11e6-91e8-002a2f3f90df.png">

**Comment by elijahverdoorn** [comment]
Sounds good, this is good information.

**Comment by hawkrives** [comment]
https://news.ycombinator.com/item?id=14651734 - someone made an IPA pronouncer for Wikipedia. That might have some useful stuff for this effort.

**Comment by drewvolz** [comment]
What about recording the pronunciations ourselves? The IPA pronouncer seems to have a base of an English TTS library. Maybe it wouldn’t be too difficult to get them into a github repo of our own.
