### ISSUE TITLE
SIS refreshing issue

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#215]
After being logged in for a few hours, I tried to pull down and refresh the financials view.

<img width="361" alt="" src="https://cloud.githubusercontent.com/assets/5240843/18282078/73ed1b22-742d-11e6-9a28-bb17bf9dfdf8.PNG">
<img width="361" alt="" src="https://cloud.githubusercontent.com/assets/5240843/18282080/7424142e-742d-11e6-86a5-acb4ac75961c.PNG">
<img width="361" alt="" src="https://cloud.githubusercontent.com/assets/5240843/18282079/74234e22-742d-11e6-81a2-db14e038336b.PNG">

**The full stack trace for financials:**

```
JSON value '<null>' of type NSNull cannot be converted to NSString

+[RCTConvert NSString:] + 244
    RCTConvert.m:56
__RCTConvertArrayValue_block_invoke + 128
<redacted> + 132
<redacted> + 208
RCTConvertArrayValue + 372
+[RCTConvert NSStringArray:] + 68
__RCTConvertArrayValue_block_invoke + 128
<redacted> + 132
<redacted> + 168
RCTConvertArrayValue + 372
+[RCTConvert NSStringArrayArray:] + 68
__41-[RCTModuleMethod processMethodSignature]_block_invoke.173 + 160
-[RCTModuleMethod invokeWithBridge:module:arguments:] + 1408
-[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 696
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.457 + 1128
<redacted> + 24
<redacted> + 16
<redacted> + 928
<redacted> + 652
<redacted> + 360
<redacted> + 572
<redacted> + 124
_pthread_wqthread + 1288
start_wqthread + 4

```

**Comment by drewvolz** [comment]
I may have old code. This may or may not be a problem.

**Comment by hawkrives** [comment]
That's a sign that the token has expired. 

Are you using the stuff from fix-sis, which is merged into master?

**Comment by drewvolz** [comment]
Pulling the PR once again into a clean branch, I noticed the error still. However, after signing out and back in, I cannot get the error to resurface. So it's still a bug, but it's not preventing me from using the view again. **I would call this a shipping issue**

**Comment by drewvolz** [comment]
One additional detail I did notice, though. If you load the Financials and Courses views while the view ErrorView is present, then your view of either the Courses or Financials view is blocked after you log-in by the ErrorView. That state/view never gets refreshed after logging in -- only the view that we log-in on is loaded. The user has to pop the navigator and return back to the SIS view if they would like to see and update that view. 

This is unaffected by actually heading to Settings and logging in. It is only caused by adding the ErrorView to the stack on both views before logging-in.

This is now issue #220

**Comment by drewvolz** [comment]
This might still be an issue in 2.0.1. I let my token expire, tried to refresh SIS, and the app crashed.

**Comment by hawkrives** [comment]
Can confirm. It's still an issue.

**Comment by hawkrives** [comment]
I think that this will be resolved in the next release with some of the stuff I did on fix-things? We should check again.

**Comment by elijahverdoorn** [comment]
I've closed and opened the app a bunch of times over the last day or so on an iPhone simulator, and I  think we're good!

**Comment by hawkrives** [comment]
> I wish there was a "close issue in X days button". Since there's not…

I'm going to close this issue. If any of us see it crop up again (or hear about it), we'll either re-open this or file a new one.
