### ISSUE TITLE
Be sure that the Help screen looks good when all tools are hidden

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2157]
I've a nagging fear that I left it with a little message with no margin/padding.

**Comment by drewvolz** [comment]
The IT Helpdesk Card has an interesting flow to it right now. All buttons are disabled, and the disabled reason reads “disabled because reason”

**Comment by hawkrives** [comment]
Yes. That's because I have disabled them, to show off what the remote configuration is capable of.

**Comment by drewvolz** [comment]
I'm more commenting that we should change the reason being "reason"

**Comment by hawkrives** [comment]
It will be enabled before release, but that's a separate issue that needs to be filed. 

It's all remotely configurable from GitHub pages, that screen is. Card titles, card hidden or just disabled, why it's disabled, the card body, the url / phone number that the button triggers, the email address / subject / body template, button state, and button text.

**Comment by drewvolz** [comment]
Yeah. I just thought it was relevant because this issue was about making sure it looked good, and I thought that message, being that it is disabled, would apply to this issue.

**Comment by hawkrives** [comment]
Ah sorry, let me update this title.

**Comment by hawkrives** [comment]
A tool can be _disabled_, or it can be flat-out _hidden_. The latter case is what I'm concerned with here.

**Comment by hawkrives** [comment]
Current appearance:

<img width="320" alt="screen shot 2018-01-20 at 1 09 22 pm" src="https://user-images.githubusercontent.com/464441/35187032-24a427ea-fde3-11e7-9d10-cef6be6fd10e.png">
