### ISSUE TITLE
Student org database

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#216]
Thoughts on either importing the existing student organization database hosted on Oleville (not sure if that is up-to-date), or creating a mirrored copy of [St. Olaf's student org list](https://www.stolaf.edu/orgs/list/index.cfm) and descriptions?

I am thinking if Student Orgs are incorporated into the app, we might be able to get away with creating another scraper (akin to the dictionary scraper) that collects the data and notifies on change.

**Comment by elijahverdoorn** [comment]
We are in the process of converting org management to http://www.checkimhere.com/, after that the student org database will be retired. I'm currently talking to IT about getting access to the checkimhere API so that we can use the data.

**Comment by hawkrives** [comment]
This has been resolved in #439, with the addition of the Student Orgs view.
