### ISSUE TITLE
Credits view lacks bottom padding

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2160]
The view cuts off the bottom on a smaller sceeen size (6s for instance) and I am unable to scroll and stay down at the bottom of the page. It will rubber band back up.

I think we need to add more padding to the bottom of that view (again).

**Comment by drewvolz** [comment]
Perhaps this is a result of the font size changes around the app

**Comment by hawkrives** [comment]
No. It's because of the safe area view things.

**Comment by drewvolz** [comment]
Ah, okay...

**Comment by hawkrives** [comment]
Folding this into #2044
