### ISSUE TITLE
Week One (new student orientation)

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#217]
Thinking far into the future, we should consider a Week One portion to the app.

Something I have discussed in-depth with Chris George, Dean of Admissions and Financial Aid, is the need to provide specific and targeted information for new students. Admissions wanted a designated app to serve up this information, so they made use of Guidebook, an app that provides a simple way to develop an app for events, schools, places and companies. St. Olaf provides the data, and Guidebook displays it.

So we end up with this.
- [Guidebook (web)](https://guidebook.com/guide/75008/)
- [Guidebook (iOS/Android) (stolafweekone2016)](https://guidebook.com/g/stolafweekone2016)

> We are excited for you to join the St. Olaf community and look forward to your arrival. Get easy access to this week’s schedule, resources, a map, and more.
> 
> All new students at St. Olaf College participate in Week One 2016 — the college’s orientation program September 3–7 (classes begin Thursday, September 8). This comprehensive program will cover what you need to know to get off to a great start as an Ole.
> 
> In addition to the information found here (this site will be updated throughout the summer), new students will receive a final detailed schedule upon arrival on move-in day.
> 
> We're glad you're an Ole! Welcome to St. Olaf College and the beginning of a new chapter in your academic career. 
> 
> This guide covers: Week One Schedule, Family Schedule for Saturday, Sept. 3rd, Transfer and International Students' events, Local eating options, Campus resources and people here to help you be successful, Social Media connections, and a little bit more...

Maybe it might be worth our time and effort to develop very specific and detailed [Week One information](http://wp.stolaf.edu/weekone/) into All About Olaf, so that we really help integrate the next class of students. 

Possible resources for a detailed Week One component:
- http://wp.stolaf.edu/reslife/for-new-students/
- http://wp.stolaf.edu/destination/timeline/
- http://wp.stolaf.edu/weekone/
- I guess what is inside of their Guidebook? https://guidebook.com/guide/75008/

**Comment by OmarShehata** [comment]
I like this idea a lot. It would make a lot of sense to have the week one inside AAO, to get new students on it during their first week, but then they also have access to all these resources from then on.

I feel like a big part of this is that it would have to be easy for reslife to edit and update the content to get them to switch away from Guidebook. Has the dean expressed any interest in having AAO fulfill this need? Do they have any gripes with Guidebook that maybe AAO can alleviate or do better?

**Comment by elijahverdoorn** [comment]
They're pretty stuck on guidebook, and honestly I don't really want to get involved with it. They are CONSTANTLY changing information, and the people that are doing the updating are NOT technical people, so we'd have to build a web console for them. Additionally, if there were any problems that would likely spell the end of the institution's support for AAO, which would be really sad. We can think about it, but need to know the risks if we do get into it.

**Comment by drewvolz** [comment]
Sounds good @elijahverdoorn I will close this.
