### ISSUE TITLE
Fix circleci logic for deploying nightlies

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2174]
The stage:

1. Circle doesn't provide the name or trigger of the running workflow, but they do provide a UUID. 
2. That UUID seems to change, maybe?
3. I encoded an uuid into fastlane last night, but there's a different one today. 
4. I'd like to update to today's uuid and see that fixes the nightly. 
5. I submitted a feature request to expose the workflow name; we'll have to see where that goes.

**Comment by rye** [comment]
>4. I'd like to update to today's uuid and see if that fixes the nightly.

If that doesn't solve it, we should probably use an env variable until the Workflows API gets more solidified.  I doubt they'll expose the workflow name by this evening.

Also, we should try releasing a new beta and make sure that that works.  (We can use that in lieu of working nightlies.)

**Comment by rye** [comment]
Closed by #2175.
