### ISSUE TITLE
Add course search functionality to SIS module

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2178]
I know this has been on the backburner for a while, so any and all input on what people think this should look like is very welcome!

**Comment by hawkrives** [comment]
So the canonical course search interface is https://www.stolaf.edu/sis/public-aclasslab.cfm.

I've got another search interface in Gobbldygook: https://gobbldygook.site/ (there may be an infinite redirection bug, beware.)

Gobbldygook's is primarily a keyword search of course descriptions / notes / titles / names, which I think is helpful.

I almost think that we want two primary interfaces, "search" and "browse". Search would be the keyword-based search, and Browse would let you delve into "okay, I want to look for courses with X" (a GE, a time, a place, etc).

// to be continued
