### ISSUE TITLE
Fix Manitou Messenger news tab loading

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2182]
Part of 2.5

**Comment by drewvolz** [comment]
The error that appears:

> Error: undefined is not an object (evaluating 'i.toLowerCase')

**Comment by hawkrives** [comment]
I believe this is https://github.com/Leonidas-from-XIV/node-xml2js/issues/411; our stack trace looks similar, at least:

```
main.jsbundle:1022:18864 j	
main.jsbundle:1022:8746 write	
main.jsbundle:1021:5449 parseString	
main.jsbundle:1026:538	
main.jsbundle:35:201 s	
main.jsbundle:35:1508 y
```

Additionally, I can only replicate this in release mode, which minifies the js bundle.

I will attempt to see where the code is minified and try to change the version of the minifier used.

**Comment by hawkrives** [comment]
(Edited the title because it's not a problem with the featured images, but with the xml parser)
