### ISSUE TITLE
Fix helpview with tools enabled

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2185]
It's, er, broken on today's nightly.

**Comment by drewvolz** [comment]
The simulator reveals an issue with that view

<img width="333" alt="screen shot 2018-01-21 at 11 42 11 am" src="https://user-images.githubusercontent.com/5240843/35197694-50b02556-fea0-11e7-900b-6aa76b3131fc.png">

**Comment by hawkrives** [comment]
lol @ myself

or cry

😭
