### ISSUE TITLE
Discussion about "help" view

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2199]
I feel that we should open up the discussion on where "help" things live.

The help section contains Wi-Fi Reporting, Help Desk, and Facilities. I've noticed that we include other help-like resources embedded into other views. Settings contains a Contact Us and FAQ section. Building Hours has Suggest an Edit as an option.

Should they be peppered in throughout the app, in one location, or in some unifying format? Is the current state navigable right now? What happens when someone looks to report a problem about the app in the Help component and it's not there?

Thoughts?

**Comment by hawkrives** [comment]
I don't think that it makes sense to move "suggest an edit" out of the contextual location that it lives now.

I could see adding a card to Help to email us.

**Comment by drewvolz** [comment]
I would be ecstatic if we made a Help card to email us. I think that would supplant the help row in Settings.

Would you be open to also listing FAQs in there, too?

**Comment by hawkrives** [comment]
I suppose we could, although we should potentially rename it to "Known Issues"

**Comment by hawkrives** [comment]
They're all configured via YAML files in /data/help.
