### ISSUE TITLE
Radio streams can be played at the same time

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2206]
I’m guessing we don’t want this to be a feature... probably should limit playing of KSTO and KRLX to one or the other.

**Comment by hawkrives** [comment]
I don't not want this to be a feature

**Comment by drewvolz** [comment]
It feels broken.

**Comment by hawkrives** [comment]
It feels like a lot of trouble to "fix"

**Comment by hawkrives** [comment]
I actually really like this.

I don't want to remove it.

**Comment by drewvolz** [comment]
I will say that undefined behavior is not a desirable feature, but if you want to keep it, okay. I will note that we are able to only pause the last active stream from the lock screen... but I guess we're going to ship it. :shipit:

**Comment by hawkrives** [comment]
yolo
