### ISSUE TITLE
KSTO radio stuck on starting until paused/played again

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2207]
I’m having an issue where I must start the KSTO stream twice for the stream to play.

**Comment by hawkrives** [comment]
I am not having this issue, fwiw

**Comment by drewvolz** [comment]
I've tried restarting, reinstalling, rebooting. It's definitely an issue for me.

**Comment by hawkrives** [comment]
As in, you can no longer replicate it, or it happens repeatedly for you?

**Comment by hawkrives** [comment]
I can now replicate this. 

It only occurs on a fresh launch, and not after unloading the Streaming module and reopening it.

**Comment by hawkrives** [comment]
I'm just not looking forward to attempting to fix this. There's nothing obvious in the logic that could be failing the _first_ time you push the button.

**Comment by hawkrives** [comment]
I cannot replicate this on my simulator; I got it the first time I launched it, but I haven't been able to since. (I even relaunched the simulator entirely.)

Edit: I think I can now reproduce this.

**Comment by drewvolz** [comment]
@hawkrives We can close this because we moved away from starting the stream in the app?

**Comment by hawkrives** [comment]
True!
