### ISSUE TITLE
Shared events are missing description

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2214]
Would it be helpful to add description to the events we’re sharing from the share sheet?

**Comment by drewvolz** [comment]
They’re also missing when they’re added to the device calendar

**Comment by hawkrives** [comment]
Yeah, we probably should

**Comment by hawkrives** [comment]
The relevant file is `source/views/calendar/calendar-utils.js`, namely the `shareEvent` and `saveEventToCalendar` functions.
