### ISSUE TITLE
Investigate why Play Store is eating ARM builds

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2216]
From my chat with support, it seems like it might be due to out-of-order Android build numbers.  Maybe we should change the ordering?

**Comment by hawkrives** [comment]
I'd actually be down to remove the Intel builds for a while. We could see if it solves the problem.

**Comment by hawkrives** [comment]
From my research last year when I set this up, it wasn't clear how else to run two APKs for different archs. This seemed to be best practice then; I believe I took it directly from some set of android docs.

**Comment by hawkrives** [comment]
We have agreed to disable x86 builds on nightlies for now, to see if the ARM builds stop disabling themselves.

**Comment by hawkrives** [comment]
Here's an interesting thing: I'm playing around the Android Studio 3.1-alpha something, and it says

> Error:Conflicting configuration : 'armeabi-v7a,x86' in ndk abiFilters cannot be present when splits abi filters are set : x86,armeabi-v7a

**Comment by hawkrives** [comment]
For reference, this is the doc I was read to get our current versioning on Android: https://developer.android.com/studio/build/configure-apk-splits.html#configure-APK-versions

**Comment by rye** [comment]
Got the nightly just fine this morning.  We can try doing a beta sometime today to see if it works.

**Comment by rye** [comment]
Beta just installed fine, so if it was an issue with ISSUE_DOWNGRADE getting thrown on installation, that's definitely fixed.  I'll still wait for 24 hours + after 2.5 gets released and rolled out without Play Store gobbling it up to call this one resolved.

**Comment by rye** [comment]
Okay, so it seems as though we are pretty close to confident that this thing is no longer happening.  Closing this issue.
