### ISSUE TITLE
Enable ripple effect on Android homescreen buttons

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2220]
currently, the touchable renders behind the gradient, so you can't see the ripple.

if we move the touchable in front, and set it to absoluteFill, it'll fit, cover the whole button, and show the ripple

**Comment by drewvolz** [comment]
The `<Touchable />` looks to be in front of the `<LinearGradient />` as the code stands

**Comment by hawkrives** [comment]
It's behind, because the Gradient is rendered within the Touchable. We need to reverse them.
