### ISSUE TITLE
Extra space at top of SettingsView

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2237]
This is on `2.5.0-beta.5+7505`

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/1566689/35346676-7c8c9812-00f8-11e8-9467-98980c19e130.jpg" width=350 />
</details>

Not sure if it's an issue produced by recent changes to that view or not.  Just opening this for tracking.  Mind you, this is on my phone with ultra-high non-standard DPI settings.

**Comment by hawkrives** [comment]
That's been there since v2.0.0. It's present on every Android phone. 

The problem is that TableviewSimple imposes a custom background color.

**Comment by hawkrives** [comment]
Thank you for filing an issue so that it's logged …

**Comment by hawkrives** [comment]
Apparently Section accepts a `sectionTintColor` prop to change the background:

https://github.com/Purii/react-native-tableview-simple/blob/06cc426f5a92133589cfd7a1ace125bc7c4ccd1b/components/Section.js#L202
