### ISSUE TITLE
Tracking: Push Notification Ideas

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2244]
## Use cases

- get the cage to post the after dark special somewhere and then notify students what it is
- SGA election time
- pause specials
- pause order ready (requires pause online ordering system, oh odt)
- building closure
- bus arrival time
- bus schedule change (no buses, f.ex.)
- class starting (if we add a full calendar [see JWZ's law])

## Feature Requirements
- in-app "channels" of notifs that can be toggled
    E.g. I want cage and nothing else

## Implementation Thoughts
- Remote web interface to add new notifications
- Behind Google Oauth w/ whitelist of accounts
- Server creates PRs with content of push, starts branches with `push/` so Circle can run a custom build on it 
    - need to make sure no two notifications are too close in time
    - check spelling / grammar
- PR'd file includes notification time/date?
- Other service checks for new notifications on master every $interval; adds/removes them from queue and sends at requested time

Ye.

**Comment by drewvolz** [comment]
[gitreports](https://github.com/schneidmaster/gitreports.com) might be close to what we're looking for. A form hosted on Heroku that submits a github issue.

**Comment by hawkrives** [comment]
We don't want an issue for this IMHO; for minimum friction, which we want here, we'll need to submit a PR

**Comment by drewvolz** [comment]
I'm not saying use gitreports verbatim. It could be a place to start, unless we'd rather do it from scratch.

**Comment by hawkrives** [comment]
I'm just thinking that it won't be that helpful as a base, since creating an issue can just use the API, while making a PR effectively requires a copy of git or libgit2.

**Comment by drewvolz** [comment]
Closed by #2988

**Comment by hawkrives** [comment]
Is it? I think we could add a checklist to the OP, but I feel that this is a valuable list that we will forget about if it's closed. 

Perhaps the list should move to the wiki? Idk. But I'd completely forgotten about, say, the classes starting soon local notification.

**Comment by drewvolz** [comment]
Would you prefer this be reopened or moved?

**Comment by hawkrives** [comment]
Either.

**Comment by hawkrives** [comment]
closing due to lack of interest in push notifications :)
