### ISSUE TITLE
Reset everything not working on android

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2246]
Seems to work on iOS.

**Comment by drewvolz** [comment]
@rye noticed that restarting the app shows the reset changes

**Comment by hawkrives** [comment]
This was fixed by https://github.com/StoDevX/AAO-React-Native/pull/2240

**Comment by hawkrives** [comment]
The reset process goes like this:

1. Clear all data
2. Reset the app icon
3. Restart the app

The last version of the icons library would throw an error when you reset the icon on Android; #2240 fixed that.
