### ISSUE TITLE
Release 2.0.1

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#226]
Release Commit: aee60be35a6b85dfa4964d1d95582f11237a3210

Target Submission Date: 9/12/16

Publication Deadline: None

**Comment by hawkrives** [comment]
Just tag master this time, instead of branching off? We don't need to make multiple release branches- not big enough for that. 

**Edit:** Thanks.

**Comment by elijahverdoorn** [comment]
Android Status: ~~Testing in progress~~ ~~Testing Passed~~ ~~In Review~~ New APK needed
iOS Status: ~~Testing not started~~ ~~Testing Passed~~ ~~In Review~~ ~~Passed~~ Released

**Comment by elijahverdoorn** [comment]
Ok. I've hit release on iOS and it should be out by end of day.

Android, as usual, is a bit more interesting. Google Play is telling me that I need a new binary, so I tried to make one. I go into the Android directory and run `./gradlew assemblerelease`, which returns an error on executing `aatp.exe`. When I get more debugging info, the build system tells me that the issue is duplicate files in the system images, specifically the back button. Can anyone build the android apk? Send it to me, I'll sign it and upload that for the time being while I fix my build system.

**Comment by elijahverdoorn** [comment]
![screen shot 2016-09-20 at 1 39 03 pm](https://cloud.githubusercontent.com/assets/12042702/18683872/a14a541c-7f37-11e6-870e-de775b009ad9.png)

**Comment by elijahverdoorn** [comment]
Closing this in favor of releasing a new version soon.

**Comment by drewvolz** [comment]
@elijahverdoorn will this be an issue for the next release? We have not updated Android as of yet.

**Comment by elijahverdoorn** [comment]
@drewvolz Not sure really, I've been doing my work on OSX and iOS for the majority of the school year. I'll look into it.
