### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#23]
Working on a basic settings view. It will have a spot for system-wide credentials (username/password for SIS and off-campus directory). An about page and licensing info can be stored here as well.
- [x] Credentials
- [x] Contact
- [x] Legal
- [x] Credits
- [x] Privacy

**Comment by drewvolz** [comment]
Could make use of this if we wanted [react-native-settings-list](https://github.com/evetstech/react-native-settings-list/blob/master/README.md)

**Comment by elijahverdoorn** [comment]
I like the settings idea, and have a sketch of what I want on the about page. I'd be curious about how the package that you linked would function on Android. If it works and looks ok I say use it, if not I'd find another way.

**Comment by hawkrives** [comment]
We're not going to find identical packages for Andoid/iOS – at least, not according to my experience earlier this summer. That might at least let us only build one custom screen, and might inform us building the android screen.

**Comment by hawkrives** [comment]
also – post mockups! Maybe we need a #mockup label.

**Comment by elijahverdoorn** [comment]
My mockup at this point is really just the text... Not worth posting, I'll just make changes to the code. As for the package, I'm ok with using it assuming that we can replicate the patterns on Android. I like the idea of keeping the app feeling native, but I prioritize features over look and feel, so spending too much time re-implementing feels counter-productive to me.

**Comment by drewvolz** [comment]
The settings view should hopefully not be too complicated to design, so perhaps it does not need "react-native-settings-list" as I suggested.

**Comment by hawkrives** [comment]
If it looks that much like a UITableView, I want to use it everywhere!

I've had so much trouble reproducing normal list views.

**Comment by hawkrives** [comment]
Or maybe there's something else that just does nice lists.

**Comment by drewvolz** [comment]
These, maybe? I know there are a plethora of options out there already. How do we pick the best one is the problem. I like what @elijahverdoorn  implemented for the Contacts view.
- [listview](https://facebook.github.io/react-native/docs/listview.html)
- [tableview](https://github.com/aksonov/react-native-tableview)

**Comment by hawkrives** [comment]
https://github.com/APSL/react-native-item-cell maybe

**Comment by hawkrives** [comment]
Tableview maybe. List view just gives you the list behavior. I've been struggling with the iOS styles (see: dictionary)

**Comment by drewvolz** [comment]
Nothing I have found can capture the flexibility that Obj-c/Swift offered with tableviews. This needs more research.

**Comment by hawkrives** [comment]
Drew, was it you that was telling me about how the iOS Mail.app dev didn't like the search box he'd built?

Because https://github.com/umhan35/react-native-search-bar still looks cool.

**Comment by drewvolz** [comment]
That sounds like something I would say. I like the `react-native-search-bar` a lot, and it could find its way into the app.

**Comment by hawkrives** [comment]
react-native-tableview looks like what we need for some things.

**Comment by elijahverdoorn** [comment]
I used react-native-card-view for the contacts view. It was super easy and pretty flexible.
I'm not against the idea of a tableview component.

**Comment by drewvolz** [comment]
Starting to make use of [react-native-tableview-simple](https://www.npmjs.com/package/react-native-tableview-simple) as it provides the styling of iOS tableviews. Trying to work EditableText into it at the moment, but it looks beautiful. Hoping it will work.

![settings](https://cloud.githubusercontent.com/assets/5240843/17463961/4cc572e0-5ca1-11e6-8462-9aa6d2822c0d.png)

**Comment by drewvolz** [comment]
This is a pretty "out-there" idea, but what would prevent us from finding the user's SIS profile photo once they are signed-in? It would make a nice icon at the top of settings, maybe? Definitely not a feature for immediate release.

**Comment by drewvolz** [comment]
Another change -- I want to replace the way that the username and password are saved. Currently they are both saved when the keyboard's `Done` button is pushed on the password text. That is not ideal, as the username could have updated and not the password. What I am imagining as the fix is a `Save` button the width of the screen below the two inputs on the settings view, so that we do not rely on either of the text fields to determine whether we save or not.

**Comment by hawkrives** [comment]
Shouldn't we add a login button to the screen? So we can check thet they're valid?

**Comment by drewvolz** [comment]
That's exactly what I'm referring to.

**Comment by drewvolz** [comment]
I added a login button to the view in my last commit to the `settings` branch.

**Comment by elijahverdoorn** [comment]
I started working on adding the legal, credits, and privacy views. They should be really simple and pull from JSON data. PR coming sometime today.

**Comment by hawkrives** [comment]
I want to see if I can make these read from text files, instead of JSON. JSON's kinda … not great for multi-line data, as you can see.

**Comment by hawkrives** [comment]
Nope. Not doing that for v1.

**Comment by elijahverdoorn** [comment]
It's fine, JSON multi-line editing isn't that bad in vim.

**Comment by hawkrives** [comment]
I don't think we have anything else to do for v1 in Settings? Specifically.

I do want to make the icon to get into it bigger.
