### ISSUE TITLE
Course Search: initial loading screen should have paragraphs not line breaks

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2332]
By the title, I mean that the no-network case should use two newlines instead of one to further distinguish the two paragraphs.

**Comment by hannesmcman** [comment]
As simple as just adding another new line?
```javascript
PROMPT_TEXT.concat(`\n${NETWORK_WARNING}`)
``` 
to
```javascript
PROMPT_TEXT.concat(`\n\n${NETWORK_WARNING}`)
```

**Comment by hawkrives** [comment]
Yup

**Comment by rye** [comment]
I was thinking that when I saw the screenshots.  This would be a good addition.
