### ISSUE TITLE
Search courses by short/long title, description

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2341]
I think we’re only searching by short title right now. Use:

Algorithms and Data Structures reveals that “Algorithms/Data Struc” is searchable but the long title containing “Structures” is not

**Comment by hannesmcman** [comment]
Should we add "search by course description" to this as well?

**Comment by drewvolz** [comment]
Sure

**Comment by drewvolz** [comment]
Professor name causes me a problem. Searching for “Olaf Hall-Holt” does not return anything because it matches on “Olaf A. Hall-Holt”

**Comment by hawkrives** [comment]
Pull up a node repl and see if https://github.com/bevacqua/fuzzysearch handles that match

**Comment by drewvolz** [comment]
Ran
```js
const fuzzysearch = require("fuzzysearch")
fuzzysearch('Olaf Hall-Holt', 'Olaf A. Hall-Holt')
```
Returns
```bash
true
```

https://runkit.com/drewvolz/5a873ff54612ac00128e7682

**Comment by rye** [comment]
Fuzzy is probably better, IMHO.  People are more likely to make mistakes or be lazy on mobile.
