### ISSUE TITLE
Remove buildsize until further notice

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2379]
As of now, it is not possible "to only report the build sizes when the entire workflow has completed, or to progressively update the comment as the jobs complete"

> I have a number of jobs in a CircleCI "workflow", four of which store artifacts. BuildSize currently updates the comment after each "build" completes, but it only only checks the artifacts for that build event, so when the workflow has completed only a single job's worth of sizes are reported.

I would like to disable it until that is solved.

**Comment by hawkrives** [comment]
Disagree :p

**Comment by drewvolz** [comment]
No use doing this if it behaves correctly behind the scenes.
