### ISSUE TITLE
ListView auto-refresh spinners are invisible

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#239]
In iOS 10, the loading spinner at the top of our refreshable ListViews is invisible, but still works.
- [ ] Calendar
- [ ] News

**Comment by drewvolz** [comment]
I do not notice this any longer. I am considering this fixed.

**Comment by hawkrives** [comment]
We think it's fixed on master

**Comment by elijahverdoorn** [comment]
Agreed, thanks for cleaning up.
