### ISSUE TITLE
Ideas for bottom 3/4 of course search view

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2407]
I have a few ideas for what to put under the search bar when there isn't a search in progress, but I can't decide which one is best/most useful...help me!

- [x] "Recent Searches" (similar to Apple Music type thing, which was the inspiration for the style of the search bar in the first place) (see #2427)
- [ ] "Saved Courses" section. This could be a list of saved courses or a way to navigate to a list of saved courses.
- [x] "Quick Search." This idea has been brought up before, and would basically entail the user selecting a few filters and pressing a button that would bring them to the search view and display all results matching those filters. (see #2459)
- Any combination of these
- More ideas?

**Comment by drewvolz** [comment]
These sound good. I'd advocate for recent searches, or a top-level way of searching by department.

**Comment by drewvolz** [comment]
I think we can close this?

**Comment by hannesmcman** [comment]
Closing this until we get around to creating some sort of scheduling assistant.

**Comment by hawkrives** [comment]
I think that such a thing belongs in a new issue, anyway. 👍
