### ISSUE TITLE
SIS ListView padding issues

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#241]
@hawkrives and I have noticed there seems to be a strange amount of padding at the bottom of the course view. 

I thought we fixed this before by explicitly defining the amount of inset to raise the list above the tabs at the bottom...

<img width="361" alt="screenshot of Oleville latest" src="http://i.imgur.com/ToMeRoO.jpg">

**Comment by hawkrives** [comment]
Is this fixed now?

**Comment by hawkrives** [comment]
It appears to be solved on my iPhone 7 simulator.

**Comment by drewvolz** [comment]
I hope it is fixed, but I tested this on my physical device (iPhone 6s). If we see it, I guess we can reopen this.

**Comment by hawkrives** [comment]
I can't test on my phone right now, since stable Xcode + beta iOS don't like each other. Yeah, reopen if you see it.

I know that this used to be kinda intermittent, but I haven't seen it once since the `rn@0.36` upgrade.
