### ISSUE TITLE
SGA integration idea: senate agendas / notes

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2410]
I don't know what happens in senate or what anything does in there, but I just passed a board with a thick agenda tacked onto it. 

I think this should be a new top-level module.

**Comment by drewvolz** [comment]
Might as well go all-in.

* Calendar
* Link to[ live stream](https://oleville.com/senate/live/) of meetings
* Link to [archive](https://oleville.com/senate/video-archive/) of meetings
* Agenda
* Minutes
* News
* Directory (find your senator)
* Ask-a-senator(?)
* Contact SGA
* Surveys
* Elections(?)

**Comment by hawkrives** [comment]
For news: does that live in News or in SGA? Isn't that the Oleville feed?

**Comment by drewvolz** [comment]
I've been wanting to move news tidbits either out of the "news" tab and into the associated tab the news is related to. I guess that's where that stems from.

**Comment by drewvolz** [comment]
And good question. I want to separate out "branch" news (oleville feed) from SGA?

**Comment by hawkrives** [comment]
> I want to separate out "branch" news (oleville feed) from SGA?

How are those different? I know nearly nothing about SGA.

**Comment by drewvolz** [comment]
**Branches:** ADC, BORSC, DCC MEC, Pause, PAC, SAC, SOC, VN
**SGA:** made up of various branches

I'll change what I meant and say I'd like Senate news to be different than SGA branch news.

**Comment by hawkrives** [comment]
So is this a Senate module or an SGA module? I guess my initial idea was just for Student Senate.

**Comment by drewvolz** [comment]
Let's make it just for senate.

**Comment by hawkrives** [comment]
I'm going to close this one, then, so we can revisit it if we ever want to think about adding an Oleville module.

I'ma open a new issue for Senate integration.
