### ISSUE TITLE
Calendar description text padding

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#242]
@hawkrives and I noticed that the calendar event text would look better if it had a tiny bit of padding so that it did not get as close to the right side of the screen/view.

Smaller screen

<img width="361" src="http://i.imgur.com/DFfRuWd.jpg">

Larger screen

<img width="361" src="http://i.imgur.com/VjwCmdq.jpg">

**Comment by hawkrives** [comment]
Why did you close this?

**Comment by hawkrives** [comment]
Why did

**Comment by drewvolz** [comment]
I guess I had the idea that it worked well, but it was a graphical enhancement that could wait and we weren't waiting to ship on. We can leave it open. That's fine.
