### ISSUE TITLE
Balances View loads ad infinitum sometimes

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2442]
Every once in a while the balances view gets stuck in a refreshing state forever, which can only be stopped by leaving the SIS component and coming back.

**Comment by hawkrives** [comment]
or rather, it never times out 🤔

**Comment by hawkrives** [comment]
@hannesmcman When you get back from break, I'd like us to keep an eye on this – it may have been resolved as part of the recent OleCard refactorings. I will also be keeping an eye out.

**Comment by rye** [comment]
Triaging. As I recall, since removing the extra caching layer, we have not seen this anymore. (I _definitely_ have not had this issue in recent memory.)

**Comment by hawkrives** [comment]
Agreed.
