### ISSUE TITLE
Disable vertical scrolling on TextInputs

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2445]
The view listens to a swipe/scroll and it catches me off guard when the cell scrolls but the view didn’t.

**Comment by drewvolz** [comment]
#### `maxHeight`

If `autogrow` is `true`, limits the height that the `TextInput` box can grow to. Once it reaches this height, the `TextInput` becomes scrollable.

TYPE | REQUIRED
-- | --
number | No

**Comment by hawkrives** [comment]
Hmm. That might be a major strike against using them.

**Comment by hawkrives** [comment]
What if we just set autogrow=true and don't set maxHeight?

**Comment by drewvolz** [comment]
Tracking this inside https://github.com/facebook/react-native/issues/18653
