### ISSUE TITLE
CircleCi Android Builds Failing

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2465]
All of the android builds seem to be failing due to this error:
```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: com.google.android.gms.common.api.internal.zzda
```

**Comment by hawkrives** [comment]
@hannesmcman Can you reproduce this locally? I'm currently installing Android Studio so I can try, but it sounds like we've got … er, two things that both add Google Maps to the android project, so it should be reproducible locally (I hope…)

Edit: `gms` may be part of Google Play, not Google Maps

**Comment by hawkrives** [comment]
Further investigation: I was going to blame a Circle Android image update, but picking two builds where once worked and one didn't revealed that they shared the same docker image hash.

[last good android nightly](https://circleci.com/gh/StoDevX/AAO-React-Native/10523):
```
Build-agent version 0.0.4761-f18e895 (2018-03-20T01:12:48+0000)
Starting container circleci/android:api-27-node8-alpha
  image is cached as circleci/android:api-27-node8-alpha, but refreshing...
api-27-node8-alpha: Pulling from circleci/android
Digest: sha256:bf560cc2aa17756c9d866e4624ae10e0c50836369a26abe11906071631dbc3be
Status: Image is up to date for circleci/android:api-27-node8-alpha
  using image circleci/android@sha256:bf560cc2aa17756c9d866e4624ae10e0c50836369a26abe11906071631dbc3be
```

[first bad android nightly](https://circleci.com/gh/StoDevX/AAO-React-Native/10584)
```
Build-agent version 0.0.4761-f18e895 (2018-03-20T01:12:48+0000)
Starting container circleci/android:api-27-node8-alpha
  image is cached as circleci/android:api-27-node8-alpha, but refreshing...
api-27-node8-alpha: Pulling from circleci/android
Digest: sha256:bf560cc2aa17756c9d866e4624ae10e0c50836369a26abe11906071631dbc3be
Status: Image is up to date for circleci/android:api-27-node8-alpha
  using image circleci/android@sha256:bf560cc2aa17756c9d866e4624ae10e0c50836369a26abe11906071631dbc3be
```

**Comment by hawkrives** [comment]
How much do we care about understanding this vs. just fixing it? //cc @hannesmcman @rye @drewvolz
