### ISSUE TITLE
Add space to bottom of homescreen notice

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2474]
<img width="504" alt="screen shot 2018-03-27 at 10 37 34 pm" src="https://user-images.githubusercontent.com/464441/38007526-75a659aa-320f-11e8-88f0-b2ee5d26e652.png">

Just needs some `marginBottom`, I think

**Comment by drewvolz** [comment]
A CARLS screenshot on AAO??

**Comment by hawkrives** [comment]
It's what I had open, so yes
