### ISSUE TITLE
Fix deprecations for RN v55

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2501]
**componentWillMount** is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: **Container, Transitioner, glamorous.Text, glamorous.View**

<hr>

**componentWillReceiveProps** is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: **CardStack, Connect(HomePage), Container, NavigationContainer, Provider, SafeView, Transitioner, glamorous.Text, glamorous.View**

<hr>

**componentWillUpdate** is deprecated and will be removed in the next major version. Use componentDidUpdate instead. As a temporary workaround, you can rename to UNSAFE_componentWillUpdate.

Please update the following components: **Connect(HomePage)**

<hr>

**isMounted(...)** is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

<hr>

Android | iOS
--|--
<img src="https://user-images.githubusercontent.com/5240843/38280967-8203fbac-3765-11e8-8f20-0c4ce1cb13f2.png" width=533 />| <img width="433" alt="screen shot 2018-04-03 at 5 22 39 pm" src="https://user-images.githubusercontent.com/5240843/38280908-220acea6-3765-11e8-815b-49a46b9c6599.png">

**Comment by hawkrives** [comment]
None of those are in things that we control. I fixed the depredations in things we control.

**Comment by drewvolz** [comment]
This issue is to track it. It’s a known issue until they’re fixed, even if they’re out of our control.

**Comment by drewvolz** [comment]
Alright. If they're out of our control, there's not use in tracking it.
