### ISSUE TITLE
Course search promise rejection

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2502]
Happens when the course search data for Android is loaded.

<img src="https://user-images.githubusercontent.com/5240843/38281133-5ba1e478-3766-11e8-9b8d-e79c63e4e6f0.png" width=420 />

**Comment by hawkrives** [comment]
Can you give us the stack trace from the devtools? That'll have the actual file paths in it

**Comment by drewvolz** [comment]
I could not. I spent an hour trying to get RN debugger to launch but it was freezing and stalling out. My devtools would not successfully launch.

**Comment by drewvolz** [comment]
Weirdly enough, the error happens when I do not have a debugger enabled. I cannot replicate with the debugger, but I see the rejection when using as normal.

**Comment by drewvolz** [comment]
Bugsnag has this to say:

<img width="770" alt="screen shot 2018-04-08 at 2 18 12 pm" src="https://user-images.githubusercontent.com/5240843/38472078-b311dea0-3b37-11e8-9f36-a60f0d643fa1.png">

**Comment by drewvolz** [comment]
Relevant: https://github.com/facebook/react-native/issues/15902

**Comment by hawkrives** [comment]
Try 

```js
// symbol polyfills
global.Symbol = require('core-js/es6/symbol');
require('core-js/fn/symbol/iterator');

// collection fn polyfills
require('core-js/fn/map');
require('core-js/fn/set');
```

The reason it works with a debugger is that remote debugging uses Chrome's js engine, instead of the bundled js engine.

**Comment by drewvolz** [comment]
Getting a runtime error to the effect of `Incompatible receiver, Set required!` which that thread is hinting at `core-js` being the culprit.

**Comment by hannesmcman** [comment]
So is there nothing we can do about this one besides wait?

**Comment by hawkrives** [comment]
I'll try to dig into this. Assigning to me.

**Comment by hawkrives** [comment]
Having looked at the code again, I think it's the Promise#finally:

https://github.com/StoDevX/AAO-React-Native/blob/f74db946946ef9dfa0eeb3c9b49d07c2430f2da9/source/views/sis/course-search/search.js#L233

Promise.prototype.finally is not yet standardized. I have now made a local branch that replaces the Promise chain here with an async function, which should have the same results.

**Comment by hawkrives** [comment]
Not fixed yet. 

>So yeah, we still have the Symbol.iterator problem. Easy (temporary) solution: move away from p-props. 
>
>Long term: figure out how to set Array.prototype[Symbol.iterator] so that things work.

**Comment by hannesmcman** [comment]
@hawkrives Should this be reopened?
