### ISSUE TITLE
Find a better solution to fixing the scrolling textinputs

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2538]
Reminder to check on react-native often to see if we can revert #2535.

**Comment by drewvolz** [comment]
As soon as we update to RN v0.57, we can set the prop `scrollEnabled={true}` on our `SelectableCell`.

**Comment by hawkrives** [comment]
As of 0.57.5, setting `scrollEnabled={false}` _crashes the app_ (good work RN).

<img width="487" alt="image" src="https://user-images.githubusercontent.com/464441/48989200-d159b500-f0ee-11e8-99c4-6fb547af5cfd.png">
