### ISSUE TITLE
Remove entries and exceptions from Info.plist

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2545]
Looking at iOS' `Info.plist`, I am wondering if we can remove two items:

- [x] KSTO scheme (app is no longer published, answer is _yes_)

https://github.com/StoDevX/AAO-React-Native/blob/89009eef5adc993ac50aad363ca9c0e856ab9e88/ios/AllAboutOlaf/Info.plist#L72-L75

- [x] Oleville insecure resource? ~The site is `https` now but do we have it listed because it loads insecure content?~

https://github.com/StoDevX/AAO-React-Native/blob/89009eef5adc993ac50aad363ca9c0e856ab9e88/ios/AllAboutOlaf/Info.plist#L94-L98

**Comment by hawkrives** [comment]
We should remove oleville.com from the `NSTemporaryExceptionAllowsInsecureHTTPLoads` block. The mixed content is only when the site loads, which we do in an SFViewController, which isn't subject to our `NSTemporaryExceptionAllowsInsecureHTTPLoads` rules.
