### ISSUE TITLE
Add NSLocationAlwaysUsageDescription key to Info.plist

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2556]
From iTunes Connect:

```
Missing Info.plist key - This app attempts to access privacy-sensitive data
without a usage description. The app's Info.plist must contain an
NSLocationAlwaysUsageDescription key with a string value explaining to the user
how the app uses this data.
```

This might be causing our backlog issues on Circle.

**Comment by rye** [comment]
We could just… copy the existing one from [`NSLocationWhenInUseUsageDescription`](https://github.com/StoDevX/AAO-React-Native/blob/4fd758a988237e40365afe8619c12974b831e207/ios/AllAboutOlaf/Info.plist#L89-L90)?  Seeing as I don't think we have any instances where we constantly use one's location?  Someone else should make sure I understand that right.

**Comment by hawkrives** [comment]
I think that should work.

**Comment by drewvolz** [comment]
It’s just asking for the key with an English description of what we’ll use your location “all the time” for. So, copying and tweaking should work.

**Comment by rye** [comment]
I'm pretty sure our description,

>We only use your location when you would expect us to, and never when you aren&apos;t using the app.

is probably just about perfect.  (PR: #2557.)
