### ISSUE TITLE
Dictionary definition problem-reporter is editable but reverts all changes

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2577]
This is for Android. I blame TextInput being multiline and already having text in the field.

**Comment by hawkrives** [comment]
@drewvolz @rye Can you try to reproduce this on `v2.7.0-beta.2`, please?

**Comment by rye** [comment]
Yes. When I open the Dictionary editor, the keyboard does show up (Android) but whenever I try to modify the text it quickly reverts back.

**Comment by hawkrives** [comment]
@rye ok, thanks. I've updated the issue.
