### ISSUE TITLE
Calendar tab bar differs from the rest

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2579]
Android only. Honestly I like it better at the moment

**Comment by hawkrives** [comment]
I believe that there are two types of bottom tabs; one where the labels are always visible ("fixed"; this has a gray background, like Google Photos), and one where the labels shift ("shifting"; this seems to always have a colored background, from the examples I've seen, and the tab bar can actually change color based on the active tab.)

Here are the Material docs on how to use it: https://material.io/design/components/bottom-navigation.html

I quite like the colorful bottom tabs.

**Comment by drewvolz** [comment]
Right. But right now, android calendar is the only one that is inconsistent

**Comment by hawkrives** [comment]
Yes. It should be the same as the others. That is to say, it should be colored.
