### ISSUE TITLE
Update "android" and "ios" to skip native builds on data/ changes

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2582]
If the only changes are in data/, we should skip running the "native" builds (`bundle exec fastlane`) to speed up PR times. 

We'll still have queue the VMs, but that's a non-issue on Circle. 

~Should we extend that to the jest and flow jobs too?~

**Comment by drewvolz** [comment]
We can close this?

**Comment by hawkrives** [comment]
No
