### ISSUE TITLE
Add Pause menu

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#264]
I got @zimmer18 started on adding the pause menu to the app, using the same structure as we have for the cage menu.

Even if we do #195, this will be ready a lot sooner and gives a good start to making changes.

**Comment by elijahverdoorn** [comment]
See branch [`pause-menu`](https://github.com/StoDevX/AAO-React-Native/tree/pause-menu).

**Comment by zimmer18** [comment]
Closed by #265
