### ISSUE TITLE
Update Privacy Policy

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2647]
Our Privacy Policy seems to have just been… taken from the Oleville Privacy Policy, and the things that that Policy describes are not isomorphic to what we do.

I'd like to update the Privacy Policy, especially to address GDPR concerns, but also to prune down the language and make it actually useful.  I'd like users to be able to read about their privacy and actually understand where their data is.  In general, we shouldn't use the Privacy Policy as a shield to hide behind and not be transparent; this should be a living document that gets changed as new data wrangling protocols take effect.

I'll open a PR sometime soon with some proposed changes, which will obviously be open to suggestions and debate.

**Comment by hawkrives** [comment]
👍

**Comment by drewvolz** [comment]
👍

**Comment by drewvolz** [comment]
@rye If you’d like assistance on the [update-privacy](https://github.com/StoDevX/AAO-React-Native/tree/update-privacy) branch, let me know.
