### ISSUE TITLE
Map not loading on Android

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#27]
On my android phone, the map view is not loading. It shows this:
<img src="https://cloud.githubusercontent.com/assets/12042702/17458859/59c1c80a-5be7-11e6-80f1-19cd023450dc.jpg" width="320">

Any ideas? @hawkrives I think that this was your code.

**Comment by hawkrives** [comment]
It is. I'll fire it up and take a look at it in a bit.

**Comment by hawkrives** [comment]
![screen shot 2016-08-12 at 2 58 33 pm](https://cloud.githubusercontent.com/assets/464441/17613954/418816c6-609d-11e6-9481-40da3ec47243.png)

There appears to be a JS error in their code somewhere, although the map works in the stock browser.

**Comment by hawkrives** [comment]
Or not. I haven't been able to reproduce that error yet.

Next up, I'm going to compare the inspectors from the native browser and the webview. But I need to put this away for now.

**Comment by hawkrives** [comment]
Current analysis says that they've got some code that resizes the canvas they draw to, and that code is setting said canvas to `0` height in our webview.

**Comment by elijahverdoorn** [comment]
Would injecting our own resize code fix the issue?

**Comment by hawkrives** [comment]
Maybe, but I can't figure out where their stuff is getting called.

Actually. You gave me an idea.

If I trigger a layout with `document.body.style.height = "500px"`, I get this:

<img width="543" alt="screen shot 2016-08-19 at 11 41 13 pm" src="https://cloud.githubusercontent.com/assets/464441/17813464/6d7951a4-6666-11e6-816e-34dba917af0e.png">

Which gets us part of the way there.

**Comment by hawkrives** [comment]
<img width="543" alt="screen shot 2016-08-19 at 11 43 42 pm" src="https://cloud.githubusercontent.com/assets/464441/17813559/c86b5580-6666-11e6-868a-a5529912b93d.png">

Well hmm.

`document.querySelector('#map-size').style.height = '500px'`

**Comment by hawkrives** [comment]
oh god. they're drawing _multiple `<canvas>`s_

![screen shot 2016-08-19 at 11 45 52 pm](https://cloud.githubusercontent.com/assets/464441/17813632/1691797e-6667-11e6-850c-48cebffeb484.png)

**Comment by hawkrives** [comment]
slash multiple image tiles

![screen shot 2016-08-19 at 11 47 14 pm](https://cloud.githubusercontent.com/assets/464441/17813690/4659931c-6667-11e6-8468-2f6ff780fa47.png)

**Comment by drewvolz** [comment]
Is there a need for multiple canvases? Can we remove one with WebView javascript injection?

**Comment by hawkrives** [comment]
Each canvas is one tile in size

The bigger problem, and the reason that map is so short, is that it's only rendering one row of tiles

**Comment by hawkrives** [comment]
I've established that they use NewRelic for analytics. This is not useful information.

**Comment by elijahverdoorn** [comment]
Suggestion/Note To Self: Use the `Linking` interface of react-native to open it in an external browser (since it works there for some reason) on android.

See: https://facebook.github.io/react-native/releases/0.21/docs/linking.html

**Comment by elijahverdoorn** [comment]
This has been fixed for the moment. More can be done on it, but we can close this specific issue.
