### ISSUE TITLE
Width of embedded video not constrained

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#272]
We format the style of common media types that appear in news articles such as 

`img`, `p`, `a`, `div`, `body`

A `video` element appeared in a news story, which we do not have a width override applied to in a style. A fix would be to add CSS styling for videos, but there could be other elements that we did not plan on showing up.

<img width="361" alt="screenshot of newst" src="https://cloud.githubusercontent.com/assets/5240843/19398157/444a888c-9219-11e6-9a8c-9b026e139839.PNG">

**Comment by yongzhihuang** [comment]
You can use a library like http://fitvidsjs.com/ to do it for you, it works for all screen resolutions.

Does that count as a PR  XD

**Comment by drewvolz** [comment]
Thanks for the suggestion, @yongzhihuang. I think we will aim for a solution that does not make use of JQuery... especially in a React-Native mobile application. It should be simple enough to handle a list of DOM elements.

Although quite a few HTML elements [could appear](https://developer.mozilla.org/en-US/docs/Web/HTML/Element), (`embed`, `object`, `param`, `source`, `canvas`, `table`, `button`, `form`, `textarea`), the solution that probably fits our needs is to apply a styling when we notice something new that breaks the mold.

**Comment by yongzhihuang** [comment]
oh woops, did not realized this was for React Native.  Sorry about that.

**Comment by hawkrives** [comment]
We could probably just add `* {max-width: 100%}`. 

However, you raise a good point about other elements. I'd advocate adding all of the block-level elements to the selector; MDN should have a list. 

Also I think that YouTube video is an `<embed>` tag, or maybe an `<iframe>`…

**Comment by drewvolz** [comment]
@hawkrives you are correct that the video is within an `<iframe>`.

**Comment by hawkrives** [comment]
MDN does have a list of block-level elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements#Elements
