### ISSUE TITLE
Sliding to pop navigation causes issue on willBlur 

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2738]
When I navigate in the app, I sometimes use the back button in the nav bar and sometimes pull on the side of the view to return back to the previous screen. They accomplish the same thing.

Within course filters, changes to the filter lists only apply if you tap the back button in the nav bar (on iOS only? Not sure). Do we want to have both back actions apply changes, or should they be considered to be different?

Response from Hawken:
> If they're behaving differently, that's a bug in React Navigation. I guess I used addListener for willBlur. https://github.com/react-navigation/react-navigation/issues/4637 is our bug, I think, but it's closed as WorkingAsIntended. The report says "willBlur is not always fired" and he says "user releases gesture, then willBlur fires, then didBlur fires".

> Here's a potentially easy fix: investigate if we can do screens that come in from the bottom. Because then you can't swipe back. I'd like to switch Settings and Filter back to modal, from-bottom transitions, if possible.

**Comment by hannesmcman** [comment]
When #2744 is merged, we will no longer experience this problem with FilterView, so we can maybe remove the shipping hold? Do we still want to investigate looking into modals?

**Comment by drewvolz** [comment]
Modals would be better to present Settings and EditHome, but that could come with a switch to react native navigation. I would think we could close when merging #2744.

**Comment by hawkrives** [comment]
Yeah, I'm good with closing when FilterViews no longer have this issue, through whatever means (including removal of them, lol)
