### ISSUE TITLE
Open Radio streams in an in-app browser, instead of attempting to play it inline

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2747]
Radio streams are tricky.

The current state is: 
- sometimes iOS will start on the first tap; sometimes it won't.
- Android always opens the stream in a web browser.

I propose that we change iOS to also open in a web browser.

**Comment by drewvolz** [comment]
We can and should make this work natively. I’ll flesh out my proposal in a bit.

**Comment by drewvolz** [comment]
# Premise

Our current radio streaming capabilities do not start up reliably or quickly. It appears to take several starts and stops to enable a stream, sometimes taking more than a minute or two to begin playing audio. The current implementation involves webviews and web browsers.

## What are the radio streams?

We tap into both St. Olaf's `KSTO` and Carleton's `KRLX` internet radio broadcasts. The main ways of reaching these streams are via:

*  __KRLX__ (MP3/M3U stream)
   * [web](https://live.krlx.org/) and [stream](http://radio.krlx.org/mp3/high_quality.m3u)

* __KSTO__ (HLS/M3U8 stream)
   * [web](https://www.stolaf.edu/multimedia/play/embed/ksto.html) and [stream](https://cdn.stobcm.com/radio/ksto1.stream/chunklist.m3u8)


## Current radio streaming strategy

* `iOS` implements a hidden `<WebView />` and listens for events fired by an internal `<audio />` player and the front-end buttons to start/stop the stream.

* `Android` loads the streams in a visible web browser.

## Proposal

I propose the following changes to the radio streaming strategy for this app.

- We should build a native bridge for streaming. This would be responsible for listening to bridged events such as `start`, `stop`, `pause` coming from JS over to native land.
  - We should start a streaming service natively.
    - `iOS`: we have an example of starting a native stream for `KSTO` in the [native KSTO app](https://github.com/StoDevX/ksto-radio). It is a good baseline to be able to adjust into a bridged library.
    - `Android`: we will probably require a bit more legwork to make a bridged library as I have not written an example app for `KSTO` in android.
 
  - We should listen / fetch track metadata.
    - Incoming timed HLS ID3 tags that `KSTO` emits when the audio changes tracks. The tag should be serialized and returned to the JS across the bridge. It can then be rendered in the view.
    - `KRLX` maintains an API for fetching these and we shall write a fetching interface to present track data to the user in the view. This is not necessary to implement as a bridged method.

 - As part of this change, we adjust the functionality of sending analytics to broadcast media.
    - As far as `KSTO`, there should be a `POST` request to handle the various bits of metadata that BMS cares about collecting according to their analytics scripts. This shall live as part of react native rather than be written as part of the bridge.
    - I am unaware of analytics collected on `KRLX`.

- We replace the current streaming mechanisms with their native counterparts.

- - -

Questions? Comments?

**Comment by hawkrives** [comment]
I still think we should just make this open in an SFWebView/Custom Tab, _purely_ because it's proven so touchy and breakable in the past.

**Comment by drewvolz** [comment]
Okay. Let's do this and move my proposal to a new issue?

**Comment by hawkrives** [comment]
Sure. I will make a PR set to close this issue, and I'll watch for your new one 😺
