### ISSUE TITLE
Changing a filter resets the ScrollView's horizontal position

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2763]
If I am in Courses, for example, which goes <kbd>Enrollment</kbd> <kbd>GEs</kbd> <kbd>Departments</kbd> <kbd>Level</kbd> <kbd>Status</kbd> <kbd>Lab</kbd>, and I change the <kbd>Lab</kbd> status, which I have to scroll over to see, my scroll position is reset to the left side when the view closes.

I think this will require some PureComponent/shouldComponentUpdate usage on the Toolbar, if not something higher, since I'm diagnosing this as the component is being re-rendered too much.

**Comment by hannesmcman** [comment]
iPhone X? Not seeing this on iPhone 8 Plus..

**Comment by hannesmcman** [comment]
@rye does this happen on android?

**Comment by hawkrives** [comment]
Huh. I can also no longer reproduce this.
