### ISSUE TITLE
Filter Popover not aligned on Android

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2764]
Any ideas?

<img src="https://user-images.githubusercontent.com/1566689/43987143-095f52cc-9ce2-11e8-9e21-8cf5c0c92ebc.jpg" width="345" />

**Comment by hannesmcman** [comment]
Could fork a copy of https://github.com/SteffeyDev/react-native-popover-view and fix there? Only a problem on android.

**Comment by hannesmcman** [comment]
PR made: https://github.com/SteffeyDev/react-native-popover-view/pull/13

**Comment by hawkrives** [comment]
Nice
