### ISSUE TITLE
Calendar detail title runs into back button

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2767]
1 | 2
--|--
<img width="530" alt="screen shot 2018-08-10 at 4 37 29 pm" src="https://user-images.githubusercontent.com/5240843/43987921-c11d15f8-9ce6-11e8-8304-cb3542612b76.png"> | <img width="530" alt="screen shot 2018-08-10 at 4 37 25 pm" src="https://user-images.githubusercontent.com/5240843/43987922-c14760f6-9ce6-11e8-845d-289f942363a4.png">

**Comment by hawkrives** [comment]
Closed by #3025
