### ISSUE TITLE
Recent filter combinations are not saving or loading

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2769]
I am not seeing any filter combos being loaded onto the front page of course search. I am unsure if they’re having difficulty saving, loading, or both.

**Comment by hawkrives** [comment]
I … don't know in what fashion I'd expect them to work anymore. 

Since I can't build up multiple filters before having it persist anymore. 

Should we think about a way to "save" a filter combo, instead?

**Comment by hannesmcman** [comment]
Currently, filter combinations are only saved when a user is in "browsing" mode (pressed the `Browse All` button or a recent filter combination) and presses the cancel button of the search bar...
https://github.com/StoDevX/AAO-React-Native/blob/c59c12856e1ef728160beaa2c53fef5ec7a599f9/source/views/sis/course-search/search.js#L124-L130

**Comment by hannesmcman** [comment]
@drewvolz @hawkrives Do we want the filter combination to be saved at a point other than when the `Cancel` button is pressed? If so, when?

**Comment by hawkrives** [comment]
@hannesmcman Idk. I was trying to envision some way for the user to "save" a filter combo, but I haven't come up with anything yet.

**Comment by hannesmcman** [comment]
@hawkrives The only problem I see with the current code is that a filter combination will not be saved if a user leaves the SIS view without pressing the `Cancel` button within the Course Search tab. Could we just add 
```javascript
componentWillUnmount() {
   if (this.state.mode === 'browsing') {
      this.props.updateRecentFilters(this.state.filters)
   }
}
```
to `CourseSearchView`?
