### ISSUE TITLE
There is no way to return to the overview of the Course Search tab

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2770]
When you start the Course Search tab, there's a search box, a list of recent searches, and a list of recent filter combos. 

There is no way to get back to this screen, except by returning to the homescreen and coming back. 

There should be some other way of returning to this screen.

**Comment by drewvolz** [comment]
Hitting cancel on the search returns you to it

**Comment by hawkrives** [comment]
… which I apparently forgot about.
