### ISSUE TITLE
Filter popovers do not resize on rotation

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2773]
![8fc23ce8-36d3-43a4-b235-480bcb23d380](https://user-images.githubusercontent.com/5240843/43995663-64d6f0dc-9d6f-11e8-83c1-cd4bc81ad8bc.gif)

Can we fix this the way we’ve fixed other rotation views?

**Comment by hannesmcman** [comment]
I think, similar to #2764, this calls for a PR to https://github.com/SteffeyDev/react-native-popover-view. The anchor point needs to be recalculated on the rotation event, which seems like a problem for the library itself. Thoughts?

**Comment by hawkrives** [comment]
I concur that this should be solved in the library.

**Comment by hannesmcman** [comment]
Looks like there's a related issue in the repo already: https://github.com/SteffeyDev/react-native-popover-view/issues/2

**Comment by hannesmcman** [comment]
@hawkrives @drewvolz Orrr we could just wrap the `FilterPopover` component with `Viewport`
