### ISSUE TITLE
Create all-white icon for push notifications on Android

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2808]
From OneSignal's documentation:

> **Small Notification Icons** - by default our SDK automatically uses either a white bell icon or your App's launcher icon. Starting with Android 5, the OS forces Small Notification Icons to be all white when your app targets Android API 21+. If you don't make a correct icon, it will most likely be displayed as a bell or solid white icon in the status bar.
>
> **Large Notification Icons** - The large notification icon will show up to the left of the notification text on Android 4.0.3 - 6.0 devices, and shows on the right for Android 7.0+ devices. If you do not set a large icon, the small icon will be used instead. OneSignal will auto scale large notification icons for you to prevent the icon from being cropped.
>
> <img src=https://user-images.githubusercontent.com/464441/44290420-455a0680-a23e-11e8-9a33-4ab624a6a22a.png width=480>

Directions from OneSignal's documentation can be found [in their docs](https://documentation.onesignal.com/docs/customize-notification-icons).

**Comment by hannesmcman** [comment]
@rye Wanna take this android guy?

**Comment by rye** [comment]
Sure, I can take a stab at it.

**Comment by hannesmcman** [comment]
@rye Are you done with this?

**Comment by rye** [comment]
Nope.
