### ISSUE TITLE
[stoPrint] Visual bug in pull-to-refresh on Print Jobs screen

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2826]
When I pull-to-refresh, as soon as the refresh vibration happens, my screen jumps down about twice as far as it was right before the refresh started.

![screenrecording_08-20-2018 07-48-56 min](https://user-images.githubusercontent.com/464441/44341633-1619e400-a44e-11e8-9cf3-0736c82e6f76.gif)

(Apologies for the gigantic gif.)

**Comment by hannesmcman** [comment]
This seems to only be a problem with `SectionList` components when the `onRefresh` callback affects Redux state.
