### ISSUE TITLE
[stoPrint] "Not Connected" screen's Help button should not link to the Help screen

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2827]
since the Help screen's Contact option is at the very bottom, and I'd rather not send people to the Helpdesk for app support.

Ideas (not mutually exclusive):

- Somehow link to eduroam / VPN connection instructions
- Include a Contact Us-ish button to email allaboutolaf@stolaf

**Comment by hannesmcman** [comment]
@hawkrives How do you feel about #2468 as a solution to this issue?

**Comment by hawkrives** [comment]
I have never liked that solution. 

The Help view was never intended, by me, to act as an App help section. It was supposed to be more of campus help, hence WiFi reporting and Helpdesk contact information. 

*I* would prefer a solution that allows us to remove the app contact from help entirely. However, that may confuse people about the Helpdesk vs App Help. 

Perhaps having a row (instead of a card) (or a much much smaller card) for the app help could go at the top. I would prefer it to be less than ⅓ of the screen size. 

/Rambling

**Comment by hannesmcman** [comment]
I think having a row at the top of the Help View for app help is a good idea... @drewvolz what are your thoughts?

**Comment by drewvolz** [comment]
That's worth exploring. I can't imagine it from any of these comments, though.

**Comment by hannesmcman** [comment]
Fair enough. I'll spin up a prototype.

**Comment by hannesmcman** [comment]
@drewvolz @hawkrives Should it be something that comes from the frogpond server like the other tools in the Help View?

**Comment by hawkrives** [comment]
Maybe just add a `compact: true` key to the tool spec and render it smaller then?

**Comment by drewvolz** [comment]
This now opens an email and was fixed via #6205
