### ISSUE TITLE
[stoPrint] Show time remaining instead of time printed?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2829]
Idk. 

We could also rework that bar to label the items, IE "Expires: 8:00 PM • Cost: $0.56 • Pages: 14"?

Idk.

**Comment by hannesmcman** [comment]
@hawkrives Is it sufficient to just put 
```javascript
Expires: {item.usageTimeFormatted}
```
or do you think we need to specify that it expires at that time *tomorrow*? (or today for that matter)

**Comment by hawkrives** [comment]
Can you give me an example of what that field contains?

**Comment by hannesmcman** [comment]
4:11:31 PM @hawkrives

**Comment by hannesmcman** [comment]
@hawkrives I think having time to expiration (e.g. "Expires: 6 hours") would be ideal

**Comment by drewvolz** [comment]
I’d like for that time to become “live” so that we do not mislead anyone who locked their device and came back to screen. Think building hours times, bus view times, etc

**Comment by hawkrives** [comment]
@hannesmcman I agree. I like that idea. Especially if we wrap it in a timer thing so that it's live.
