### ISSUE TITLE
Change homescreen color of stoPrint button

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2845]
Student orgs and stoPrint are too similar in color

![Orgs and stoPrint](https://i.imgur.com/Jj1f9x2.jpg)

```js
{
  view: 'StudentOrgsView',
  tint: c.periwinkle,
  gradient: c.tealToSeafoam,
},
{
  view: 'PrintJobsView',
  tint: c.chartreuse,
  gradient: c.tealToSeafoam,
}
```

**Comment by hawkrives** [comment]
`tint` is no longer used, so they're currently exactly the same color. Whee.

**Comment by drewvolz** [comment]
@hawkrives we should strip out `tint` from the view definitions

**Comment by hawkrives** [comment]
File a new issue, please.

**Comment by hannesmcman** [comment]
lol I didn't even see this issue when I made the PR
