### ISSUE TITLE
Balances should hide "login needed" text until the login fails

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2847]
It's really odd … a lot of the time, when I open the app and go into SIS, it fetches my updated balances but also says I need to log in. 

The auto-login-at-app-launch seems to be failing.

**Comment by drewvolz** [comment]
If you're logged-out, it always says "not logged in!" at the bottom of the "Log in with St. Olaf" row.

Relevant:
https://github.com/StoDevX/AAO-React-Native/pull/1613
https://github.com/StoDevX/AAO-React-Native/issues/1633
https://github.com/StoDevX/AAO-React-Native/pull/1634

**Comment by hawkrives** [comment]
Yes. But I'm logged in.

**Comment by drewvolz** [comment]
Simply trying to point to things that have changed that might affect the behavior you're noticing.

**Comment by hawkrives** [comment]
I won't block release on this, as it's not a regression from 2.5, and it's only broken-ish. It works most of the time. 

I'll continue to work on it, but I won't target 2.6.0.

**Comment by hawkrives** [comment]
I've edited this issue title to reflect the current state of things; Balances now shows a "log in here" (or whatever it says) button until the initial fetch request succeeds; I would like to hide that text until the request has failed.

**Comment by rye** [comment]
Triaging. @hawkrives, this doesn't _seem_ to happen for me anymore. I think this is because we removed the authentication layer and the caching layer. Shall we close this issue?

**Comment by hawkrives** [comment]
I think this issue can be closed. Thanks!
