### ISSUE TITLE
Course notes are lengthy on list rows

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2961]
Also stemming from #2952, course list notes were added to the list rows. They can get kind of lengthy. 

> I want to either remove them from the list rows, or limit them to 1 line.

<details>
<summary>Screenshots of long course notes</summary>

~ | ~
--|--
![telegram-cloud-file-3-831937890-90711-7770742396837060420](https://user-images.githubusercontent.com/5240843/45101298-677dd080-b0e8-11e8-83d2-7233b85eec55.jpg) | ![telegram-cloud-file-3-830932384-97183-1821923187031404446](https://user-images.githubusercontent.com/5240843/45101313-6c428480-b0e8-11e8-9dfd-864c551e11e2.jpg)
![telegram-cloud-file-3-830932499-97272--4431890308569011349](https://user-images.githubusercontent.com/5240843/45101334-749abf80-b0e8-11e8-9cf2-e915c620e984.jpg)
</summary>

**Comment by hawkrives** [comment]
I would also argue that the notes should be below the deptnum/professor line.
