### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2964]
I like changelogs. Okay, that's a lie. I used to hate changelogs. I have a love/hate relationship with them. Every big project has a changelog, though. And they make the release procedure _much_ easier, because everything that needs to go in the tag body is right there.

Here's a proposal: use a variant of the format/style of: https://keepachangelog.com/en/1.0.0/.

I think that if we put this in a file in our repository, that'll make updating it a lot easier.  I thought about putting it in the Wiki, but that would require opening and maintaining the Wiki.

Here's what I think we should use as the distinction between what gets a changelog entry and what doesn't:

## Types of ChangeLog entries:

(The `monospace` text denotes a heading to be used in the body of the version section of the changelog.)

- `Added` for new features.
- `Changed` for changes in existing functionality.
- `Deprecated` for soon-to-be removed features.
- `Removed` for now removed features.
- `Fixed` for any bug fixes.
- `Security` in case of vulnerabilities.

## What gets a changelog entry

- New features¹
- Fixes of any bugs from a previous release
- Removals/deprecations
- Changes of behavior or appearance
- Security fixes

## What does not need or get a changelog entry

Except as noted in (1),
- Code style changes
- Patch or Minor version upgrades of app dependencies²
- Any upgrades of build-related dependencies

***

¹: Any new features or changes that get made and then get changed again within the same release band get combined together. For example, if one adds a new View, and then separately fixes a bug with it before the next release, one should not create a separate changelog entry denoting the change; in either case one should either update the existing changelog entry or just count the new change as part of the previous one.

²: Development version updates (e.g. `v0.56.x` to `v0.57.y`) are considered major updates.

***

How does this sound? How do people feel about changelogs, and do we think they are useful?

We can start with this with the release of v2.6.0.

**Comment by hawkrives** [comment]
I like this idea.

**Comment by drewvolz** [comment]
I’m a fan

**Comment by drewvolz** [comment]
Anyone see the need to have this open any longer?

**Comment by rye** [comment]
No, I don't really see a need.
