### ISSUE TITLE
Course rows reference old course prop

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2967]
Need to update to `course.offerings` (I think). 

But it's slightly more complicated because `sis-timestring-parser` uses the old prop as well. Tracking that here https://github.com/StoDevX/sis-timestring-parser/issues/33.

https://github.com/StoDevX/AAO-React-Native/blob/586d744f443597c4f0c9cc01af2e01932a7072c4/source/views/sis/course-search/row.js#L69

**Comment by hannesmcman** [comment]
Wow I can't believe I didn't even notice this!

**Comment by hawkrives** [comment]
In that case, I really want to put notes at the bottom of the list row.

**Comment by drewvolz** [comment]
> In that case, I really want to put notes at the bottom of the list row.

Your comment is now addressed in #2966.
