### ISSUE TITLE
Wrong icon for unfavorited places

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2980]
Unsure if this is Android-only or not, but shouldn't this be an empty heart outline? Just an idle thought.

![screenshot_20180908-101944](https://user-images.githubusercontent.com/1566689/45255748-f68d2180-b350-11e8-8647-ce82f5481e30.jpg)

**Comment by hawkrives** [comment]
Yeah, it should. We should check the ionicons site to make sure they still have the empty heart icon. 

I may be about to work on a branch to let us use the old version of ionicons, because we still need some of the outline icons they removed. (Namely "share" for iOS.$
