### ISSUE TITLE
Prettier and Danger are not reporting code style issues where they should

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2993]
See #2992 which includes complaint about new lines of code from #2990.

Something needs to be revisited.

**Comment by rye** [comment]
I agree that

>Things that cause Danger to comment should fail the build

as @hawkrives says.

**Comment by rye** [comment]
Except for things like… iOS slowness reports.

**Comment by hawkrives** [comment]
Yeah.

**Comment by hawkrives** [comment]
Okay. Got it.

https://circleci.com/workflow-run/27e1cbad-4a67-4c6b-8b78-07e1cc59c6ef

![image](https://user-images.githubusercontent.com/464441/45264832-5e527380-b408-11e8-9d0f-393301257233.png)
