### ISSUE TITLE
Change ASC to CAAS

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3010]
ASC is now known as CAAS according to this [news article](https://wp.stolaf.edu/news/padula-family-supports-new-center-for-advising-and-academic-support. ). This means we need to change:
- [x] Dictionary term and definition?
  - the new one is [pretty sparse](https://wp.stolaf.edu/academic-support/) comparatively
  - but we could detail the "portfolio of services" provided in the webpage sidebar
- [x] Building hours names and times
  - source updated [here](https://wp.stolaf.edu/academic-support/asc-hours/)

**Comment by hawkrives** [comment]
CAAS is, as I understand it, a new umbrella organization. I don't know that it replaces either the ASC or the AAC, both of which are now located under it in the internal hierarchy.

I can ask around.

**Comment by drewvolz** [comment]
> This fall, this change will be official, as its academic support center becomes the Center for Advising and Academic Support (CAAS).

**Comment by hawkrives** [comment]
Fair. I think that the leadership of the ASC is the leadership of the CAAS, but I don't remember how the AAC fits into it, aside from the fact that it's also merged into CAAS.

**Comment by drewvolz** [comment]
What’s the verdict on this, @hawkrives?

**Comment by hawkrives** [comment]
yes
