### ISSUE TITLE
How to hide notes from non-WRI111/REL121 courses

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3014]
Adapted from #3011 

We need notes on these two types of courses, because they show the actual name of the course.

**Comment by hawkrives** [comment]
Actually, @hannesmcman, do we show name or title in the list view currently? I could just tweak the scraper to set the title to the actual name from notes, and then we can hide them completely.

**Comment by hannesmcman** [comment]
@hawkrives We currently show name, since title is not always given.

**Comment by hawkrives** [comment]
closing~
