### ISSUE TITLE
Sleep randomly for up to an hour before beginning nightly

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3027]
This is a common practice, especially when doing things e.g. certbot renewals, to cause the build to begin at a different time each day. Not only is this good practice, but it's also better for us, because it may allow us to avoid intermittent failures on remote servers due to large spikes of load on the hour.

**Comment by hawkrives** [comment]
That's a range of minutes from 0..60 inclusive after the start time, right?

I don't doubt that it's good practice, but generally the CI services don't like you just idling on their boxes, and the Cron syntaxes generally run as close to the allotted time as possible.

**Comment by rye** [comment]
If I were a CI provider, I wouldn't care.

Why? Sleeping is _really_ easy to run on my infrastructure. If a process is sleeping for 367 seconds, I _know_, for a fact, the Linux CFS can just ignore my process for 367 seconds. The process doesn't have to get scheduled unless it gets an interrupt or something, which it shouldn't unless Circle is doing some strange stuff that we don't know about.

The only "bad thing" that this would do is allocate a build worker for our build. But that build worker would be sitting there doing absolutely nothing, eating 0% CPU and contributing only positively to the load average. In any correctly-designed system, this will not be a problem; if it were to be a problem, then people who open up CircleCI and make a build with multiple parallel sleeping jobs would be able to slowly cause a denial of service. Build workers should be infinite, but server capacity is not.

There's a hard limit of 5 hours, I believe, so we can't get excessive, but I definitely think that sleeping for a random amount up to a minimum of 10 minutes is a good idea. An hour is a safe bet.

Cron is designed to run as close to an assigned time as possible, but this has a negative effect which is that all other jobs that want to run at `0 5 * * *` will start immediately at `0 5 * * *`. So we will be contending with all of the other builds that run at that time.

All we would need to do is create a job that sleeps and stick it in front of the `cache-` jobs.

**Comment by hawkrives** [comment]
I believe that both Travis and Circle will terminate jobs that haven't output anything in 10 minutes, to terminate stuck jobs.

**Comment by rye** [comment]
Yes, but we can up that limit.
