### ISSUE TITLE
Display Meal Plan Information

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#303]
IIRC, the meal plan balance info used to live at https://www.stolaf.edu/apps/olecard/checkbalance/index.cfm, but at the end of summer when @drewvolz and I were wrapping stuff up the meal plan info was either missing or disabled temporarily. 

We'd need someone else to go re-implement the data fetching.

<hr>

_(edit from @drewvolz -- it is worthy to note that with the info being hidden, it is of great importance that we make sure to not assume the data is available... so when scraping the table it is displayed in, we should take care to ensure that we don't necessarily expect it to be there before proceeding.)_

**Comment by elijahverdoorn** [comment]
Confirming that it's still there. I'll throw an implementation together.

**Comment by hawkrives** [comment]
There's some stuff in https://github.com/StoDevX/AAO-React-Native/blob/master/lib/financials.js#L100, and some stuff in the original version, that might be useful

**Comment by hawkrives** [comment]
Original AAO implementation: https://github.com/StoDevX/all-about-olaf/blob/f1c372a9e9c4f16f58bda3a994a3fb889c11dbf2/St.%20Olaf/SISTableViewController.m#L575-L643

**Comment by elijahverdoorn** [comment]
Yeah, I'm just building off what's there. Shouldn't be too hard.

**Comment by hawkrives** [comment]
:+1:

**Comment by hawkrives** [comment]
I'm going to quote @drewvolz's extra comment so there's a notification:

> it is worthy to note that with the info being hidden, it is of great importance that we make sure to not assume the data is available... so when scraping the table it is displayed in, we should take care to ensure that we don't necessarily expect it to be there before proceeding.

**Comment by elijahverdoorn** [comment]
Agreed, I'll be careful of that.

**Comment by elijahverdoorn** [comment]
I've got all the fetching done, but the `loadLoginCredentials()` function is returning nulls. Is there a chance that we're not storing this information when the user logs in in the first place? Have we removed that functionality since implementing the OAuth stuff?

**Comment by hawkrives** [comment]
Yeah, we're not storing it at all currently. When we added OAuth for the SIS, we just made that work™, and shoved other-things-that-use-olaf-credentials to the back burner, so there's currently nothing that receives credentials to store.

I see a few paths forward:
1. Ask for both SIS login and St. Olaf credentials in Settings, and prompt for them at appropriate screens. This is annoying, but they will only need to enter the credentials once.
2. Only ask for credentials, and automatically log into and submit the Google OAuth form. This feels dirty and creepy. I don't like it, but it's simpler, as the user only needs to enter their info once.
3. Something else that I haven't considered yet.

**Comment by elijahverdoorn** [comment]
I considered the first option, but didn't think about the second. I'm ok with annoying the user one time, I'm less ok with the second option; unless I hear other ideas or objections soon I'll move forward with the first option.

**Comment by hawkrives** [comment]
I think that our old login code is still in the repo history from right before OAuth was enabled; that should give you a good start.

Then, tie that screen into a button like we have in the SIS screen, allowing the user easy access to the login form.

You'd need to change the login checking endpoint; maybe `/apps/olecard` or something? It might also be worth asking IT if they have a spot where we can just check login credentials.
