### ISSUE TITLE
Pause Menu Drop Down

### ISSUE THREAD

**Issue by erichkauffman** [StoDevX/AAO-React-Native#304]
The drop downs on the pause menu do not open on iOS.

**Comment by erichkauffman** [comment]
This may be due to new custom collapsable component since none of the other drop downs are working either.

**Comment by hawkrives** [comment]
Are they using react-native-collapsible or my new collapsible component?

Most likely react-native-collapsible. 

Try switching the imports to the collapsible component I made in components/collapsible.js

(cc @Mattt4k)

**Comment by hawkrives** [comment]
The PR to make things use the new collapsible component hasn't landed yet.

**Comment by hawkrives** [comment]
I hope to finish that tomorrow or Wednesday.

**Comment by elijahverdoorn** [comment]
Thanks for the update, @hawkrives. @ekmanzu Will you try this and report back?

**Comment by drewvolz** [comment]
@hawkrives fix listed above does work, and I've merged it now after testing and fixing up the merge commit. Consider this closed.

**Comment by hawkrives** [comment]
Should be fixed on master. Drew tested the #294 before we merged.
