### ISSUE TITLE
[discuss] Remove bugsnag from network errors

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3059]
Idk. I'm split 50/50.

- There's not really anything we can do about them
- They aren't "bugs" or "crashes", so they don't really belong in Bugsnag
- Yeah?

**Comment by drewvolz** [comment]
I see it as valuable to know if the urls have gone bad — as we’re the only ones updating these at the moment. We don’t have any other health check setup right now.

**Comment by hawkrives** [comment]
But it doesn't tell us that, currently. And all of the errors we have atm are from bonapp, anyway. 

Plus, it wouldn't report errors from URLs in, say, Student Work - it just reports fetch() errors.

**Comment by hawkrives** [comment]
Besides which, I would argue that those don't belong in Bugsnag either.

**Comment by drewvolz** [comment]
Belong is a funny way to put it. How do you suppose we make sure our network errors are caught then?

**Comment by hawkrives** [comment]
I don't have an answer for that, either. 

However, the current app won't catch incorrect content urls - it really only reports when someone opens the Caf view and switches networks at the same time.

**Comment by hawkrives** [comment]
Also, I say "belong" because they're not app bugs. They're content bugs. Which may be a silly distinction, but I'd rather track content problems separately from code issues.

**Comment by drewvolz** [comment]
Okay. If you don't feel we gain anything from them and write them off as menu errors, we can nix them.

**Comment by rye** [comment]
I see it as valuable to monitor network errors. They should at least be logged. I will only agree that these shouldn't be logged once we have something built to handle failed network requests—namely offline cache updating and exponential backoff queues.

However, the current way we get them is not the most optimal. They could use a bit more verbosity in the short term, although if we do plan on doing cache updates and updating stuff that way, I'm game to just maintain the status quo until we can remove them.

**Comment by hawkrives** [comment]
I just don't see the point in having them, even before we build that stuff.

**Comment by rye** [comment]
Now that I've had more time to think about it, I kinda agree.  If a client fails to connect to something, we don't really care.

My main thing is that this gives us insight into whether or not clients are actually getting data rendered on their screens… if we nix network errors, how will we know if e.g. menus are broken for everyone?

What if we were to remove the general case and instead just add custom cases, e.g. "menu failed to render: data malformed" or something like that.  That's definitely a lot more useful than "Network request failed" to me.

**Comment by hawkrives** [comment]
I like that idea

**Comment by rye** [comment]
Triaging. We have since switched to Sentry. Explicit network error reporting occurs in two locations—not everywhere.

- `source/views/help/wifi.js`
- `source/views/menus/menu-bonapp.js`

Personally, I think it's far more valuable to have Sentry just receiving actual errors, which include unhandled promise rejections. We should gracefully handle these things through UI and handle network errors either in that way or let them drop as promise rejections?

The only way I could see making this worth keeping is if we made _all_ network problems get reported. But we can't fix them.

**Comment by hawkrives** [comment]
Agreed.

For the menus, specifically, we built a "retry" button interface that shows up after ~3 failed fetches. 

I think that qualifies as "handling the error", as far as the network goes. Any JSON-parsing errors should still be reported to Sentry (which is what currently happens.)

My proposal, then, would be to remove the network error reporting from `source/views/menus/menu-bonapp.js`.

**Comment by rye** [comment]
@hawkrives should I remove the network error reporting from `source/views/help/wifi.js`? This view also makes a report whenever it encounters errors loading the thing.

**Comment by hawkrives** [comment]
Sure
