### ISSUE TITLE
Ship new build without debug menu?

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3069]
#3068 points to the `settings/debug` view always being exposed...

If this is the case and it is _always_ showing up, do we want to tag a new build for release? I don't know how I feel about including the debug view in the release build for end-users. It shows off **a lot** of information.

**Comment by hawkrives** [comment]
Yes. We should tag and ship 2.6.3.

**Comment by hawkrives** [comment]
2.6.3 has been tagged and uploaded
