### ISSUE TITLE
Build script for android:release is broken

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3072]
`yarn run android:release` runs the `react-native` equivalent for building a release android app:

https://github.com/StoDevX/AAO-React-Native/blob/479add9f1ab9cd1caf79a848afaf9d6ae09c59c3/package.json#L7

but the console returns:

```console
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installRelease' not found in root project 'AllAboutOlaf'. Some candidates are: 'uninstallRelease'.
```

**Comment by rye** [comment]
Where is this? Locally, or in CI?

**Comment by rye** [comment]
(assuming local since it's a `react-native` command)

**Comment by drewvolz** [comment]
This is meant to be run locally to test out the release build. We're missing some setup according to [this](https://facebook.github.io/react-native/docs/signed-apk-android#testing-the-release-build-of-your-app).


> Note that --variant=release is only available if you've set up signing as described above.

**Comment by hawkrives** [comment]
We should remove it. If you want to build the release app locally, you should use fastlane.

**Comment by hawkrives** [comment]
update:

> Okay, here's my vote
> Remove the :simulator/:emulator variants
> And fix whatever's broken with :release

**Comment by drewvolz** [comment]
Do we have access today to the signing key that was used to publish AAO on the playstore? I'm in favor of closing this and coming back to it when we're ready to create a new signing key if we do not have access.

> Once you publish the app on the Play Store, you will need to republish your app under a different package name (losing all downloads and ratings) if you want to change the signing key at any point. So backup your keystore and don't forget the passwords.

**Comment by hawkrives** [comment]
Yes

**Comment by hawkrives** [comment]
We have to use it for every android release. Explore the "matchesque" lane to see how it's used.

**Comment by hawkrives** [comment]
I will somewhat question why we need it, though. Since it obviously hasn't been used in 1+ years.

**Comment by hawkrives** [comment]
I removed the `:simulator`/`:emulator` scripts in #3557.

`installRelease` should not require a signing key for local development; however, I still question if we need it, since there are buttons to do so in Android Studio / Xcode (and those work, unlike the scripts).

**Comment by drewvolz** [comment]
I'd like to close this particular issue because `"android:release"` has been removed.

**Comment by hawkrives** [comment]
Er, it hasn't? I'd like to remove it, though

**Comment by drewvolz** [comment]
I’ve had a change of mind since opening this, and think we should remove it, then.
