### ISSUE TITLE
Detox Version 9.0.4 test: App not launching and getting ps|grep issue

### ISSUE THREAD

**Issue by PSG2019** [StoDevX/AAO-React-Native#3104]
Hi Team,

Facing issue while launching the app for detox test.. getting error as below. 

detox[12168] INFO:  [DetoxServer.js] server listening on localhost:60341...
detox[12168] ERROR: [exec.js/EXEC_FAIL, #15] "C:\AndriodSDK\sdk\platform-tools\adb -s emulator-5554 shell "ps | grep \"com\.fourtest$\""" failed with code = 1,stdout and stderr:

Pacakage.json : 
{
  "name": "FourTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "react": "16.5.0",
    "react-native": "0.57.1"
  },
  "devDependencies": {
    "@babel/generator": "^7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "babel-jest": "23.6.0",
    "detox": "^9.0.4",
    "jest": "^23.6.0",
    "metro-react-native-babel-preset": "0.47.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "detox": {
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_26"
      }
    },
    "test-runner": "jest"
  }
}

**Comment by rye** [comment]
We do not maintain Detox, and your provided examples make it clear that this issue doesn't even relate to this project.
