### ISSUE TITLE
Make SGA/Oleville Top Level View

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#3120]
After talking to a few SGA members, it looks like there is significant interest in having a top-level view for SGA-related news/actions. To start, I think it would be good to extract the "Oleville" tab from the News view, and make a new top-level view with two tabs: "Senate" and "News". Thoughts?

**Comment by rye** [comment]
This would be fine, but I don't think having multiple top-level views for SGA is necessary.

"SGA" as a top-level view? With "Senate", "News", "Events" as tabs? This way we have more than two…

**Comment by rye** [comment]
I would also like this kind of a view to read any data directly from oleville.com, be that through ccc-server or directly from the phones.

**Comment by hawkrives** [comment]
I agree with only one top-level view, which I think is what @hannesmcman proposed.

I also agree with wanting oleville.com to source the data.

**Comment by drewvolz** [comment]
Dup of #2412
