### ISSUE TITLE
Consolidate variables in Android gradle configuration

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3140]
From #3138:

>[The code added in #3138] could go into `android/app/build.gradle` and use the defined constants from there?

I think this would be beneficial. I wanted to also explore consolidating our _VERSION constants from the two into perhaps the `build.properties` file or something equally suited.

**Comment by hawkrives** [comment]
I think this has been accidentally resolved; part of #3557 included moving more variables into the top-level `android/build.gradle` file, and both the `subprojects{}` rule and the `android/app/build.gradle` rules now use the same constants.

https://github.com/StoDevX/AAO-React-Native/blob/eff397900799962cee598ac00e9b30f167ec9945/android/build.gradle#L3-L10

@rye, do you think that suffices to close this issue?

**Comment by drewvolz** [comment]
@rye

**Comment by rye** [comment]
I'll be honest, I haven't actually had a chance to build Android at all and likely won't until I get my next Mac. I'm fine with closing for now — can always reopen. :-)
