### ISSUE TITLE
Release v2.6.4

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3164]
It's about time.

I want to do two things: #3108 and an as-yet unfiled issue to disable state restoration (because I have managed to, once again, completely break my app by suspending on a calendar detail view, and while we can fix that bug, IMO we should disable state restoration until we've audited the rest of the app for this sort of problem.)

**Comment by drewvolz** [comment]
- [x] Privacy policy
- [x] State restoration 

...is the state restoration actually _state_ or _navigation_?

**Comment by hawkrives** [comment]
Navigation state restoration. 

It's done.

**Comment by hawkrives** [comment]
I need to fix login before 2.6.4 I think (only because I told someone it would be fixed in the "next release")

**Comment by drewvolz** [comment]
Oof. We do need to fix that.

**Comment by rye** [comment]
We need to fix all of the crashes that were introduced by RN 0.57 as well.

**Comment by hawkrives** [comment]
Do those have issues? We should make sure that all of the crashes have associated issues.

**Comment by rye** [comment]
I'm specifically concerned about #3260 and #3243 (which isn't a crash so much as login being broken)

We should also have something filed for popovers crashing the app.

**Comment by rye** [comment]
Given that we've stepped forward with RN I think it's also v2.7 rather than v2.6.4.

**Comment by hawkrives** [comment]
(skipping 2.6.4 and going straight to 2.7)
