### ISSUE TITLE
Transfer Android app away from sgawebmaster account

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3165]
As part of the divorcing from SGA.

I'll look into how to do this.

**Comment by rye** [comment]
@hawkrives made the request just minutes ago.

**Comment by rye** [comment]
From discord:

>@hawkrives do you happen to know if the [old] account has Google Play Developer credentials associated? I think that's why we're getting a nightly failure. Don't we need to set up a new API key in order to get this deployed?

[paraphrased a bit]

**Comment by hawkrives** [comment]
This has been done. Tracking fallout in #3173.
