### ISSUE TITLE
Fix Android Deployment API keys

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3173]
Since the rollover to deployments under the new Google Play identity, we have had failing Android nightlies because the old credentials do not support the new namespace.

@hawkrives, can you please follow the following documentation and update the keys repository?

https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials

Thanks.

(I would myself, but apparently "only the account owner can configure API access.")

**Comment by rye** [comment]
(The generated JSON file should go into `[keys repository]/android/play-private-key.json`)

**Comment by hawkrives** [comment]
Oh, it's in the other google developer console settings. Of course it is. 

Sure.

**Comment by rye** [comment]
A new error:

```
[!] Google Api Error: accessNotConfigured: Access Not Configured. Google Play Developer API has not been used in project 621408517588 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/androidpublisher.googleapis.com/overview?project=621408517588 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

I followed that link and enabled it.

**Comment by rye** [comment]
Latest [deployment job](https://circleci.com/gh/StoDevX/AAO-React-Native/33997) passed and a build was uploaded to Google Play.  Done for now.
