### ISSUE TITLE
Detox: Suppress build output

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3186]
Since we build the app in the `Run Fastlane` step, can't we ignore the build output (at least to stdout) when running `yarn detox build --configuration ios.sim.release`? It's basically the same output, but unprettified.

**Comment by hawkrives** [comment]
Go for it, as long as it prints the errors if it errors during build

**Comment by rye** [comment]
I would assume that they're properly using stderr and stdout, but I guess we'll find out.

**Comment by hawkrives** [comment]
I mean, I want all of the test output too

**Comment by rye** [comment]
@hawkrives, that's the plan. I just want to suppress stdout during the detox build step.
