### ISSUE TITLE
Detox: Re-use Fastlane build output?

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3187]
I wonder, is there any way for us to reuse the Fastlane built targets in Detox?

This would shave nearly half of the "build" part of the iOS build off, which I think is not insignificant. Just a question.

**Comment by hawkrives** [comment]
I don't think so; I think Detox links extra things into the native binary, for debugging hooks.

**Comment by hawkrives** [comment]
Update: Detox does not link extra things in, afaict. It does build a release-mode binary, but then again so does the main build.

So this may be feasible after all.

**Comment by hawkrives** [comment]
Update 2: No, this is not feasible; Detox requires an app built for the simulator, (an x86 target), while testflight and the app store require ARM targets.

So unfortunately, we can't share the build artifacts between them.
