### ISSUE TITLE
Migrate to America/Chicago

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3198]
According to the [(unofficial) table of IANA time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), `US/Central` is deprecated.

In fact, if you download an unofficial copy of the [time zone database](https://timezonedb.com/download), you will not find a mention to `US/Central` at all.

If you prefer "official" sources, IANA's [tzdb download](https://www.iana.org/time-zones) (current version: 2018g) has no mention of "US/Central" except in the `backward` file:
```console
$ rg 'US/Central' *
backward
118:Link	America/Chicago		US/Central
```
This `backward` file includes the following header:
```
# tzdb links for backward compatibility

# This file is in the public domain, so clarified as of
# 2009-05-17 by Arthur David Olson.

# This file provides links between current names for timezones
# and their old names.  Many names changed in late 1993.

# Link	TARGET			LINK-NAME
[...]
Link	America/Chicago		US/Central
[...]
```

I am led to believe what I thought was the case before, which is that `US/Central` is an old way of referring to a time zone.  `America/Chicago` is the best convention for us to follow, and while unlikely it is possible that `US/Central` could be removed later.

I move that we consolidate all of our time zone usage on `America/Chicago`, since that is what St. Olaf uses as its standard.

**Comment by hawkrives** [comment]
(I'm going to mark this as accepted.)
