### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#32]
This seems to be an easy tool to resize the icon:
https://makeappicon.com/

**Comment by hawkrives** [comment]
Are we planning to re-use the existing icon, or go with something Oleville-related?

**Comment by elijahverdoorn** [comment]
We're going with this one: 
![oleville-logo](https://cloud.githubusercontent.com/assets/12042702/17468267/f17a9df2-5ceb-11e6-8cd1-2de1b8989345.png)

**Comment by hawkrives** [comment]
It's round ⭕

**Comment by elijahverdoorn** [comment]
True, but I think that having a bit of a white border on the iOS version is ok. It matches the trend set by apps like messenger, groupme, Twitter. The tool that I posted above will make the whitespace for us.

**Comment by drewvolz** [comment]
Yeah, our current set of iOS icons were made by that toaster. It's a cool site. I have a CLI tool for taking a high quality app icon and creating all of the other icon sizes. If I find that, I'll send it your way. It does look good after running it through `makeappicon`. I had to see it on the full device before I could make a comment.. Neat icon, nevertheless.

**Comment by elijahverdoorn** [comment]
@drewvolz If you find that tool, I'd like a copy. I'll eventually get around to adding it to the project so that we can all look at it and voice opinions.

**Comment by drewvolz** [comment]
I remembered incorrect -- it was for screenshots, which we do not have to worry about anymore. Apple recently sent out an email saying they now allow you to upload your highest quality screenshot (that fits their standards) and they will slice-n-dice as needed to fit the smaller screenshot sizes. So, never mind.

**Comment by hawkrives** [comment]
@elijahverdoorn, mind if I take a stab at adding the icons to the build? I ran them through the tool you linked (I attached the output.)

[logo copy.zip](https://github.com/StoDevX/AAO-React-Native/files/413008/logo.copy.zip)

**Comment by elijahverdoorn** [comment]
Go for it.

**Comment by hawkrives** [comment]
Done with 8bbf925493a7fcb4477c736ae484856b7db6f7bd.

**Comment by drewvolz** [comment]
This is solved with #117

**Comment by drewvolz** [comment]
@elijahverdoorn the app icon preview on the iOS app store is the icon with a white background, but when downloaded, a black background. Would you be open to a PR in the near future to a white background on the icon?

**Comment by hawkrives** [comment]
Aka "can we please change the iOS icon to a white background‽" 

pretty please? 

🎁🍨

**Comment by elijahverdoorn** [comment]
@hawkrives @drewvolz I was taking a poll around here and people said they like the black, but I personally agree with you that the white would look better. I'd accept a PR for that change.
