### ISSUE TITLE
Cage menu overridden by new cage menu

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#320]
I really like the new menus and think that we should extend it to the cage, but the changes have overridden the standing items on the cage menu. We should re-enable those somehow, I know that people use that section.

**Comment by hawkrives** [comment]
We're thinking about how best to do that. Most of the data is still in the JSON response from the cage, but the simple way of showing it also renders, like, condiments. So we can't take the easy way out.

I'd like to handle this myself, if you don't mind?

(Our [@drewvolz and I]'s main concern is future maintainability – we would like to let BonApp change their menu and have to do as little work as possible on our end.)

Give me until Wednesday; if I haven't got something worked out by then, we'll just load the current Cage data in on top of the API-given specials or something.

**Comment by drewvolz** [comment]
@elijahverdoorn can you specify what you meant by "standing items"? 

Like @hawkrives mentioned, it would be optimal to feed-in a version of the Cage menu in the JSON format that BonApp uses / that we parse for Cage and Stav.

**Comment by hawkrives** [comment]
(I'm interpreting Standing as "currently existing", as a synonym of the current status quo)

**Comment by elijahverdoorn** [comment]
Yeah, @drewvolz: I'm referring to the items that are always there, like coffee. I've gotten feedback from a lot of people that they like being able to see these, since they are not huge fans of the scrolling cage menu screens.

I have yet to examine the JSON that we're now parsing, I'll take a look and see if I have any ideas. I support the idea of reducing future work for us.

**Comment by hawkrives** [comment]
Here's the Cage menu, for your perusal: https://gist.github.com/hawkrives/f60880cd6e03c6c24ab1e6526cb292cf

**Comment by hawkrives** [comment]
The work has been happening in the [`fancy-menu`](https://github.com/StoDevX/AAO-React-Native/tree/fancy-menu) branch.

**Comment by hawkrives** [comment]
> @elijahverdoorn: I really like the new menus and think that we should extend it to the cage, but the changes have overridden the standing items on the cage menu. We should re-enable those somehow, I know that people use that section.

In my PR #393, `fancy-menus`, I have taken the position that if something's not available through the Cage API, that needs to be reported to BonApp so that they can update their data.

I believe that to be a per-location service, as Carleton's responses are much fuller than ours – theirs even have prices, for instance.

So this could be an instance for you still at Olaf to apply some pressure on BonApp to update their basic menus.

**Comment by elijahverdoorn** [comment]
@hawkrives I'll get in touch with Randy Clay - he just came to Senate last week and had good things to say about SGA, so I'll leverage that. More to come.
