### ISSUE TITLE
ListViews are sometimes blank

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#321]
If you open the Transportation view, scroll to the bottom of the list, then go back, and open Important Contacts, it's blank. Part of the time.

Screenshot proof included below.

<img width="361" alt="7512" src="https://cloud.githubusercontent.com/assets/464441/20276076/637a471a-aa60-11e6-9913-25b53ce7a5d1.PNG">

**Comment by hawkrives** [comment]
Interesting note: I let my iPhone go to sleep, then when it woke up the information showed up a split-second later.

**Comment by drewvolz** [comment]
I am able to simply tap on the button and reproduce your screenshot (no data visible) without navigating to the transportation view first. This behavior has been around since the advent of the 2.0 refresh of the app. I suspect we are maybe trying to draw the data to the screen at the wrong point in time?

**Comment by hawkrives** [comment]
Except that … that's the simplest component we have! Take a static list of input, render to screen.

**Comment by drewvolz** [comment]
https://github.com/facebook/react-native/issues/1831 describes our issue. Supposedly we need to set `initialListSize` or `removeClippedSubviews={false}` ... @hawkrives what do you think?

**Comment by drewvolz** [comment]
The impact is larger than we originally thought.  For instance, I click on news, immeditaly click on a story, then go back. Then the news view is blank. 

@hawkrives: "this issue should remain open until we have added the prepared rows prop everywhere"
