### ISSUE TITLE
Campus map is broken

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#322]
Searching as well as tapping on building callouts seems to be broken... and it is a third-party webservice provided by Campusbird/concept3D.

The webpage works directly from my mobile device in a browser but not within the iOS app itself.

**Comment by hawkrives** [comment]
another one of those? … sigh.

**Comment by drewvolz** [comment]
I vote to ditch the webview and bring back the native map... https://github.com/StoDevX/AAO-React-Native/blob/master/data/map-coordinates.json
