### ISSUE TITLE
"Network Failure" (incorrect) after RN 0.57 upgrade

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3243]
Not sure what's triggering this—this might be a `react-native-device-info` thing? No clue.

<img width=320 src="https://user-images.githubusercontent.com/1566689/49160594-b5236700-f2ec-11e8-8528-6fdeb6c8adc1.png" />

**Comment by rye** [comment]
Has anyone been experiencing this on iOS? @hawkrives?

**Comment by rye** [comment]
I'm going to try to replicate in a simulator.

**Comment by rye** [comment]
Yes, I was just able to replicate this on a fresh build of `master`:

![screenshot_1543462227](https://user-images.githubusercontent.com/1566689/49197623-1c750180-f355-11e8-92af-974cc49e6852.png) | ![screenshot_1543462232](https://user-images.githubusercontent.com/1566689/49197622-1c750180-f355-11e8-8f0c-623bd0556f41.png) | ![screenshot_1543462248](https://user-images.githubusercontent.com/1566689/49197621-1c750180-f355-11e8-8d73-b7c6e91ac990.png)
---|---|---
![screenshot_1543462259](https://user-images.githubusercontent.com/1566689/49197620-1c750180-f355-11e8-8a6b-0edf818343c1.png) | ![screenshot_1543462262](https://user-images.githubusercontent.com/1566689/49197618-1bdc6b00-f355-11e8-9ff7-bb97e4ba53bd.png) | ![screenshot_1543462270](https://user-images.githubusercontent.com/1566689/49197617-1bdc6b00-f355-11e8-856e-393db4d67748.png)

@hawkrives, I figure since you're the most familiar with the changes to login state that were made, do you have any ideas? Or can you point me to something that I can debug for this one? I was looking at `redux/parts/settings` but I still haven't the slightest clue.

**Comment by rye** [comment]
After much debugging, it seems like this is a server-side issue.

Worth checking if clients that don't have the beta also get this issue.

**Comment by hawkrives** [comment]
Closed by #3308
