### ISSUE TITLE
Centralize logic for build skipping into reusable scripts

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3250]
I can think of a few possible use cases here, but the main thing would be the creation of a few scripts called something like `script/ci-should-continue`, taking one of three arguments: `native`, `ios`, or `android` and exiting with `0` if the build should not be skipped or `1` if the build should be skipped.

This way, we run things as follows:
```
script/ci-should-continue ios && <ios commands> || echo "Skipping iOS build because we said so."
```

These should be Ruby-based? Ideally, we'll centralize the logic into a central library file which we can require from `fastlane` to dedupe the logic.

**Comment by rye** [comment]
We should only call this on "expensive" operations, such as `fastlane`, `detox`, and the like.  Obviously, it should run as fast as possible.

**Comment by rye** [comment]
We could build this as a Ruby Gem, if we wanted to! ~(Under `frogpond` namespace?)~ (RubyGems doesn't have namespaces)

This would make it _very_ easy to test and distribute.

**Comment by hawkrives** [comment]
is this done‽‽?!

**Comment by rye** [comment]
Yea
