### ISSUE TITLE
circle: Stop building native builds on master unless merged branch touched native files

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3253]
We can reduce our CI footprint significantly by doing this.

One issue is, how do we know which is our "source" and which is our "to" when doing this? Is there a general case we can apply to all commits to figure out the previous mainline point in history?  Or do we need to have special handling for `master`?

If we want, merge commits into master have `2` parents, and we can just do something like `master^1` to get the previous `master` commit… that'd work.  `git log [...] HEAD^1..HEAD^2`?

**Comment by rye** [comment]
Here's a thingy:

https://stackoverflow.com/questions/1527234/finding-a-branch-point-with-git

**Comment by rye** [comment]
Here's the suggestion from that StackOverflow on `skip-native-builds-part-2` a bit ago:
```
diff -u <(git rev-list --first-parent HEAD) \
             <(git rev-list --first-parent master) | \
     sed -ne 's/^ //p' | head -1
```
produces `ba8708a66358dfc2b49fc4fa649c95a45df9494e`, which is exactly what we would want.

What about on `master`?

With a little bit of magic, here's what I came up with:

```
diff -u <(git rev-list --first-parent HEAD^1) \
             <(git rev-list --first-parent master) | \
     sed -ne 's/^ //p' | head -1
```

But, on a single-commit branch, that might cause problems.  Needs another test in that case.

Also, diffs could get massive. This doesn't scale. It'd be nice to have some internal Git tool that does this…

Wait.

# Eureka! Introducing… `git merge-base`!

Okay, so there are five scenarios in which we might find ourselves:
1. A branch which is equal to `master`
1. A branch which is one commit ahead of `master`
1. A branch which is multiple commits ahead of `master`
1. A commit directly on `master`
1. A merge commit consisting of a branch with `1..n` commits ahead of a previous point in `master`.

I found a plumbing (?) command: `git merge-base`? 

This works _everywhere_: `git merge-base master HEAD^1`. Order is independent. Let's think about it. 
 It finds the oldest shared commit in the history between `master` and HEAD's first parent.

The name of the following game is to find all commits that are special about HEAD, that differentiate it from the "previous" `master`.

## ① `HEAD == master`

In this case, we want our range to include `{ B }`.

```
master: ---A---B
```

In this case, `HEAD^1 == A`, `master == B`, and `git merge-base A B == A`; then `A..HEAD == B`, which is all that we need to consider.

## ② `HEAD` is just 1 commit ahead of `master`

In this case, we want our range to include `{ C }`.

```
  HEAD:      C
            /
master: ---A---B
```

In this case, `HEAD^1 == A`, `master == B`, and `git merge-base A B == A`; then `A..HEAD == C`, which is all that we need to consider.

## ③ `HEAD` is n commits ahead of `master`

In this case, we want our range to include `{ C D }`.

```
  HEAD:      C---D
            /
master: ---A---B
```

In this case, `HEAD^1 == C`, `master == B`, and `git merge-base C B == A`; then `A..HEAD == { C D }`, which is all that we need to consider.

## ④ `HEAD` is 1 commit ahead of a previous `master` but is itself `master`

This is… the same as ② actually.  It's just an inversion; `HEAD^1` is previous `master`, `HEAD` is `master`, merge-base is then previous `master`, so the change is just the commit difference.

## ⑤ `HEAD` is a merge commit on `master` containing many commits from a topic branch

In this case, we want to consider the commits that were added by the topic branch.

```
             C---D---G---H
            /             \
master: ---A---B---E---F---I
```

Here, `HEAD == I`, `HEAD^1 == F`, `master == I`, and `git merge-base F I == A`, so `A..HEAD == { C D G H }`. I think. It should be, because your merge brings the two histories together.  It'd be in chronological order.

# So what should we do?

Instead of doing `git log [...] master..HEAD` we should do `git merge-base master HEAD^1` to find the oldest common point `𝓀`, then do `git log [...] 𝓀..HEAD`.  In the case where we're building a merge commit (q.v. ⑤) the log will include just the commits on the branch that was merged.  If we want to check _all commits on both branches_, then we'd need to use `...` instead of `..`, which "includes commits reachable by either but not both".  However, this would cause us to start doing native builds on branches that don't have native code changes if `master` suddenly had native build changes.

```
kristofer@maero ~/Blorp (master) ⑆ git log
commit 1cbc4a323288268040cb9e95816fc5315491a03f (HEAD -> master)
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:34:06 2018 -0600

    G

commit b142d47c8bf3362d71d6443989e1dc87e4dc9376
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:39 2018 -0600

    E

commit 80538fc9756bcc2d6651eb20eb5d2f4eb8d74bc5
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:30 2018 -0600

    D

commit 0e2550cd8b695b91b3a7fd67cee294564ec2fb7a
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:32:38 2018 -0600

    A
kristofer@maero ~/Blorp (master) ⑆ git checkout topic
Switched to branch 'topic'
kristofer@maero ~/Blorp (topic) ⑆ git log
commit d8a728dba3563c7ab6097c4f8d2caec2f9974233 (HEAD -> topic)
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:53 2018 -0600

    F

commit 1e3059c84cfff719176a9a1f27191f8a2af8c226
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:17 2018 -0600

    C

commit 5efdbec8e1679705ff3015863181aead59b81fc3
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:32:58 2018 -0600

    B

commit 0e2550cd8b695b91b3a7fd67cee294564ec2fb7a
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:32:38 2018 -0600

    A
kristofer@maero ~/Blorp (topic) ⑆ git merge-base master HEAD^1
0e2550cd8b695b91b3a7fd67cee294564ec2fb7a
kristofer@maero ~/Blorp (topic) ⑆ git log (git merge-base master HEAD^1)..HEAD
commit d8a728dba3563c7ab6097c4f8d2caec2f9974233 (HEAD -> topic)
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:53 2018 -0600

    F

commit 1e3059c84cfff719176a9a1f27191f8a2af8c226
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:17 2018 -0600

    C

commit 5efdbec8e1679705ff3015863181aead59b81fc3
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:32:58 2018 -0600

    B
kristofer@maero ~/Blorp (topic) ⑆ git checkout master
Switched to branch 'master'
kristofer@maero ~/Blorp (master) ⑆ git log (git merge-base master HEAD^1)..HEAD
commit 1cbc4a323288268040cb9e95816fc5315491a03f (HEAD -> master)
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:34:06 2018 -0600

    G
kristofer@maero ~/Blorp (master) ⑆ git merge topic
Auto-merging file
CONFLICT (content): Merge conflict in file
Automatic merge failed; fix conflicts and then commit the result.
kristofer@maero ~/Blorp (master|MERGING) [01] ⑆ echo "H" > file
kristofer@maero ~/Blorp (master|MERGING) ⑆ git commit -am "H"
[master 2d7b503] H
kristofer@maero ~/Blorp (master) ⑆ git log (git merge-base master HEAD^1)..HEAD
commit 2d7b5033af03092ea3e24e9b9948bf282c0b3e27 (HEAD -> master)
Merge: 1cbc4a3 d8a728d
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:36:29 2018 -0600

    H

commit d8a728dba3563c7ab6097c4f8d2caec2f9974233 (topic)
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:53 2018 -0600

    F

commit 1e3059c84cfff719176a9a1f27191f8a2af8c226
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:33:17 2018 -0600

    C

commit 5efdbec8e1679705ff3015863181aead59b81fc3
Author: Kristofer Rye <kristofer.rye@gmail.com>
Date:   Wed Nov 28 12:32:58 2018 -0600

    B
```

**Comment by rye** [comment]
So, if my understanding is correct, we just need to add a couple of things: `git merge-base master HEAD^1` to find the start of our log range, and then use `HEAD` as the end to make this general.

**Comment by rye** [comment]
Let's separate this one from #3252, since this is more of a logical change than an implementation change.

**Comment by rye** [comment]
And I'll gladly implement this.

**Comment by hawkrives** [comment]
Yeah, #3252 is more of "let's make build skipping possible", while this is "let's make it more effficient". Thanks for taking this on!
