### ISSUE TITLE
Replace Google Analytics with a simple, custom server

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3283]
I have designs for exposing the Analytics information inside the app (my thought process being something like "we collect the data from people, so we ought to share it back with them" – and also we have no reason to keep it private).

Google's also shutting down Google Analytics for Apps next year-ish. They want us to move to Firebase (yeah no).

But really all we need are app launches, screen opens, screen durations, and session durations, I think.

I wouldn't want to build our own crash reporter, but I think we could build a simple analytics service. Be transparent and simple. And not going to shut down on us, lol.

**Comment by drewvolz** [comment]
Why the opposition to Firebase?

**Comment by hawkrives** [comment]
Google developer tool. (Also has a mental connotation in my head of being a large monolithic library, but that may not be true.)

I would prefer to move away from Google, all things considered, rather than just switch which services we're feeding data within them, and I don't trust most smaller companies to not wind up selling user data at some future point.

**Comment by rye** [comment]
We also can fine tune our privacy policy around this.

I'm on board.

**Comment by hawkrives** [comment]
Relevant: https://github.com/18F/analytics-reporter/blob/master/README.md

**Comment by hawkrives** [comment]
Also, I'd like to be able to pull some of the data out of GA for whatever we decide to track in our own tool - ie, screens, session counts, etc. so that we can load them into our app.

**Comment by hawkrives** [comment]
(alternately, https://count.ly/mobile-analytics / https://github.com/Countly/countly-sdk-react-native is an open-source product that we can self-host)

**Comment by hawkrives** [comment]
We wound up just removing in-app analytics entirely, in favor of just using session counts from the store fronts and potentially in-person user testing in the future.
