### ISSUE TITLE
iOS builds need to switch target SDK versions

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3290]
> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "All About Olaf". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
> - SDK Version Issue - This app was built with the iOS 11.4 SDK. 
>
>   Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.
>
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

**Comment by drewvolz** [comment]
> This probably requires Xcode 10, too.

> Xcode 10.1 or later

So Xcode 10.1.

**Comment by hawkrives** [comment]
Or Xcode 10.1, sure
