### ISSUE TITLE
Use tabs in Ruby code?

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3311]
This is my default, and it's our default in JS-land.

Either this, or I'd like to propose adding an `.editorconfig` to support this.

Thoughts?

**Comment by hawkrives** [comment]
Sure

**Comment by rye** [comment]
Sure to which, tabs?

**Comment by hawkrives** [comment]
Hawken's vote: yes to tabs

**Comment by rye** [comment]
Kris' vote: yes to tabs
