### ISSUE TITLE
Force-ish iOS user-agent to our string

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3325]
as of 2.7.0-beta.2, the user-agent for the app (on iOS, at least) is as follows:

```
AllAboutOlaf/43039 CFNetwork/976 Darwin/18.2.0
```

It should look more like 

```
AllAboutOlaf/2.6.3 (iOS/12.1)
```

Need to look into #3310 more and see why our UA isn't being set.

**Comment by hawkrives** [comment]
update: the same IP (which I think is my phone) is also sometimes sending this UA: 

```
"AllAboutOlaf/2.7.0-beta.2 (iOS/12.1.1)"
```

which is what it should be sending.

**Comment by hawkrives** [comment]
is there a difference between our fetch-layer caching and the CFNetworking cache?

**Comment by hawkrives** [comment]
yes?

```
stolaf.api.frogpond.tech 172.18.0.1 - - [18/Dec/2018:21:00:06 +0000] "GET /v1/food/named/cafe/burton HTTP/2.0" 200 2350 "-" "AllAboutOlaf/2.7.0-beta.2 (iOS/12.1.1)"
stolaf.api.frogpond.tech 172.18.0.1 - - [18/Dec/2018:21:00:06 +0000] "GET /v1/food/named/menu/burton HTTP/2.0" 200 118 "-" "AllAboutOlaf/2.7.0-beta.2 (iOS/12.1.1)"
stolaf.api.frogpond.tech 172.18.0.1 - - [18/Dec/2018:21:00:11 +0000] "GET /v1/food/named/menu/burton HTTP/2.0" 304 0 "-" "AllAboutOlaf/43039 CFNetwork/976 Darwin/18.2.0"
stolaf.api.frogpond.tech 172.18.0.1 - - [18/Dec/2018:21:00:11 +0000] "GET /v1/food/named/cafe/burton HTTP/2.0" 304 0 "-" "AllAboutOlaf/43039 CFNetwork/976 Darwin/18.2.0"
```

where the first two are the first time I've opened the Burton screen, and the second two are when it's cached.

**Comment by rye** [comment]
It seems like this is because `CFNetwork`-y requests (I guess) are bypassing our Fetch logic, or have their own UA set?  (Our `modules/fetch/init.js` skips setting the `User-Agent` header if one is already set, from what I'm seeing) https://github.com/StoDevX/AAO-React-Native/blob/bc81dddccad40e6f1c7b20b6c820f187243782d7/modules/fetch/index.js#L74-L76

Do we need to do some thinking on this? Or are those lines the likely culprit?

**Comment by hawkrives** [comment]
I think we need to think on this more.

1. The UA-setting-skipping logic only applies to `fetch()` requests, by way of doing `fetch(url, {headers: {'User-agent': 'blah'}})`
2. We don't do that anywhere
3. So we _should_ be setting the UA header on every request
4. So what is allowing CFNetworking to set its own header? I have to assume that those requests are still being triggered through this fetch() system, because thats the only way we trigger network events.

**Comment by hawkrives** [comment]
I did some digging on related topics, wondering if we could get away with just … not having my caching layer at all, and concluded that we likely do need a manual caching layer in order to handle the stale-but-offline case. 

Using http://petersteinberger.com/blog/2012/nsurlcache-uses-a-disk-cache-as-of-ios5/ and https://developer.apple.com/documentation/foundation/url_loading_system/accessing_cached_data, I see several ways to control accessing cached data, but it looks like the only way to hit the cache when you're offline is to catch the error and retry. 

Which is essentially what I'm doing now, so I think we can leave it.

**Comment by rye** [comment]
Re-triaging.

>so I think we can leave it.

So, I'm going to close this issue, especially since the last hit on any endpoint with the UA including  CFNetwork was on 2019-04-19T23:41:10Z:

```console
[root@api ~]# cat ~rives/ccc-server/logs/access.log | grep 'AllAboutOlaf' | grep 'CFNetwork' | tail -n1
stolaf.api.frogpond.tech 172.18.0.1 - - [19/Apr/2019:23:41:10 +0000] "GET /v1/tools/help HTTP/2.0" 304 0 "-" "AllAboutOlaf/46703 CFNetwork/978.0.7 Darwin/18.5.0"
```
