### ISSUE TITLE
TextView contents cannot be highlighted/selected on iOS

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#333]
This is a limitation of ReactNative at the moment. It has been implemented [for Android](https://github.com/facebook/react-native/pull/8028) but not iOS.

Keeping track of this issue:
* [Product Pains](https://productpains.com/post/react-native/support-selecting-text-within-text-elements-for-copypaste-etc)
* [GitHub](https://github.com/facebook/react-native/pull/8028)
* [GitHub again](https://github.com/facebook/react-native/issues/10897)

iOS is a bit more complicated. The guy who implemented it for Android has this to say

> I have implemented this feature for Android, waiting for it to be merged. iOS has proved to be *much* more difficult since their Text widget works by drawing raw characters to the screen, instead of using the native iOS UITextView, so I'm hoping that someone else more experienced with RN Shadow Views will be able to take that on.

## Status

- [x] Building hours detail (title, subtitle, badge, hours day/schedule)
- [x] Notice snapshot test
- [x] Notice (message)
- [x] Card (header/footer) 
- [x] Contacts card (title, description)
- [x] Dictionary (word, definition)
- [x] SIS balances (flex, ole, print balances)
- [x] KSTO (title, description, notice)
- [x] Transportation (title, description)
- [ ] Orgs
  - [ ] Android 
    - [x] contact, description, error message
    - [x] name
    - [ ] category
    - [ ] meeting time, location are not possible atm b/c of `<Cell>` (see https://github.com/Purii/react-native-tableview-simple/issues/30)
  - [ ] iOS
    - [x] name
    - [ ] description
    - [ ] category
    - [ ] meeting time, location are not possible atm b/c of `<Cell>` (see https://github.com/Purii/react-native-tableview-simple/issues/30)

**Comment by drewvolz** [comment]
As of 0.39, we are able to mark `<Text>` as selectable. This means we are now able to do this!

http://facebook.github.io/react-native/releases/0.39/docs/text.html#selectable

**Comment by hawkrives** [comment]
What views would we like to make selectable?

**Comment by elijahverdoorn** [comment]
Maybe the event info?

It would be really cool if you could highlight an event, have all the info copied to your clipboard, then got to your texting app (for example) and past the copied data and have a nicely-formatted, clean description of the event to text to friends.

**Comment by drewvolz** [comment]
At that rate, we probably would need to add a share button to each row. But I like where you were headed with that idea.

With selectable text, maybe the dictionary detail, student orgs detail, hours detail...

**Comment by hawkrives** [comment]
Oh right, good ideas. Dictionary should be easy; Orgs is trickier since it farms out to TableView and Cell.

**Comment by hawkrives** [comment]
@drewvolz Could you please add a checklist to the OP of what screens have been done? Thanks!

**Comment by drewvolz** [comment]
Updated.

**Comment by hawkrives** [comment]
The orgs android detail view doesn't use `<Cell/>`, fyi

**Comment by drewvolz** [comment]
I count 3 instances of `<Cell/>` being used in [Android's detail view for orgs](https://github.com/StoDevX/AAO-React-Native/blob/master/source/views/student-orgs/detail.android.js).

**Comment by hawkrives** [comment]
… or maybe they are. Really, past me? I see them… hmm.

**Comment by hawkrives** [comment]
@drewvolz Can we close this? We not have components to allow text selection. 

I'd like to file follow-up issues for any other areas that we want to tweak text selection on.

**Comment by drewvolz** [comment]
Why close this and file follow-up issues? I think this issue fits as we're trying to accomplish this still? 

I'd like us to look into https://github.com/chirag04/react-native-tooltip together with the Clipboard-API.

**Comment by hawkrives** [comment]
Because it's not a single issue? We've accomplished it on the majority of the views, and I don't think the list in the OP is up to date. 

There's no need that I can see for a custom popup, either - `selectable={true}` gives you a [Copy] option on tap+hold.

**Comment by drewvolz** [comment]
> There's no need that I can see for a custom popup, either - selectable={true} gives you a [Copy] option on tap+hold.

That's not the type of selection I'd like to continue to implement. Looking for native drag and select for individual words and characters.

> I don't think the list in the OP is up to date.

Then we should perform a new audit and update the list here

**Comment by drewvolz** [comment]
...but okay, let's go with your suggestion.
