### ISSUE TITLE
Add Safety Committee tile

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3335]
The original request: (important bits bolded)

>Along with that, IT has helped us create **a vanity URL** which will direct everyone to **a Google form** to report unsafe winter walking conditions.
>
>One item we'd love to incorporate with these posters is the ability for students (and maybe some faculty and staff too) to access the Google form via the [All About Olaf] app. **Is there any way another "tile" could be created for "Report a Safety Concern" that could link to the following page? [link]**

See the email for the link.

This feature was requested for delivery by January 18th. Our 2.7.0 milestone says 2019-01-01.

---

- @hawkrives says he wants to maybe make the "Help" menu on the bottom, and that may be a place for this to go to. For now, @rye thinks it goes into Home screen, or gets a card in Help.
- Since the big part of the flow is a Google Form, we should consider kicking people out to their default browser. @rye's google-fu says [`react-native`'s Linking is a good idea?](https://facebook.github.io/react-native/docs/linking.html)
  - E.g. `Linking.openURL(url).catch(err => console.error('An error occurred', err));`?

---

As always, feel free to self-assign and take it on.

**Comment by hawkrives** [comment]
a simple first PR could be to 

1. add a new type of homescreen tile, `browser-url`
1. add a new openUrl function that calls `Linking.openUrl` called `openUrlInBrowser`
1. add a homescreen handler such that `type: external-url` tiles trigger the new `openUrlInBrowser` function
1. add a new homescreen tile with `{type: browser-url, name: Safety Concerns, icon: [xyz], url: https:…}`

and then I can still do my help redesign in parallel, but then we have something working. and we can bikeshed on colors and icons in that initial PR.

**Comment by drewvolz** [comment]
I feel jarred when something kicks me out of the app and into the OS browser. Can we kick around the idea of prompting the user on a `browser-url` whether they want to leave the app or not? I feel like that would be a more polite way for this to flow.

**Comment by hawkrives** [comment]
No one will report things if they have to log in to google in the in-app browser IMO, since they'll have to do the 2fa dance.

**Comment by hawkrives** [comment]
@rye The safety committee has responded and said that we can go live whenever.

**Comment by drewvolz** [comment]
> No one will report things if they have to log in to google in the in-app browser IMO, since they'll have to do the 2fa dance.

??? I'm not saying keep them in-app. I'm saying let them know they're leaving the app.

**Comment by hawkrives** [comment]
Ah
