### ISSUE TITLE
Ensure pull to refresh delay is visible on Orgs and Dictionary

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3340]
1. Pull to refresh on news in an out-of-cached state
2. and then pull again.

Noticing the artificial delay isn’t there for the spinner?

---
Todo:
- [ ] Orgs
- [ ] Dictionary
- [x] Menus
- [x] News
- [x] FAQs

**Comment by hawkrives** [comment]
I think this is applicable to any pull-to-refresh view, not just with cached data.

**Comment by drewvolz** [comment]
I’ll agree with that

**Comment by hannesmcman** [comment]
I tested all the other PTR views and the only one that seems to have this issue is the BonApp menu view..

**Comment by drewvolz** [comment]
I still see it on both Menus and News

**Comment by hannesmcman** [comment]
Oops yep you're right!

**Comment by hawkrives** [comment]
Closing due to removal of caching

**Comment by drewvolz** [comment]
>I think this is applicable to any pull-to-refresh view, not just with cached data.

This isn't just a caching issue so the issue should be renamed.

**Comment by hawkrives** [comment]
This is not applicable to any view anymore.

**Comment by drewvolz** [comment]
>I still see it on both Menus and News

Reopening since it still is on Menu, News, FAQs, Orgs, and Dictionary

**Comment by drewvolz** [comment]
Handled partially in #3984

**Comment by hawkrives** [comment]
I've removed all PTR delays, so I'm going to close this.
