### ISSUE TITLE
Select, rather than deselect, OR filter option when "Show All" is active

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#3346]
After showing the new filter toolbar feature to a few friends that use the app, I received the following suggestion, which will make the selection of filters more intuitive.

Setting:

When an OR filter is disabled, all of its options are selected. 

Current behavior:

When the user selects an option, that option is deselected, while all other options remain selected. 

Desired behavior:

When the user selects an option, that option should now be the only option selected.

**Comment by hawkrives** [comment]
See, I disagree. Then my only way to exclude a single station is to manually check all of them.
