### ISSUE TITLE
Clear cache after updating the app

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3354]
In order to facilitate us being able to change the way things are cached in the future. 

Everything starts with a common prefix, although I don't remember it offhand. 

We should be able to store the "last known app version" in AsyncStorage, then compare it to the running app. 

If they're different, we should call AsyncStorage.getAllKeys, and filter that list to just the ones matching the prefix, then delete all of the matching items.

**Comment by drewvolz** [comment]
Do we want open cache issues like this to remain open now that our caching strategy has been reverted? @hawkrives

**Comment by rye** [comment]
Since our persistent caching strategy has been reverted, I'm going to close this, @drewvolz.
