### ISSUE TITLE
Filter with no items is showing a closed message

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3355]
When I tap a filter that appears to have no menu items to show, a closed status is appearing instead. I am seeing “closed today” when I select the “breakfast” station for the meal time of lunch or dinner.

<img src="https://user-images.githubusercontent.com/5240843/50424641-ad3fdf80-0824-11e9-9862-cf31ba57dd4d.gif" width=280 />

**Comment by drewvolz** [comment]
Relevant lines

https://github.com/StoDevX/AAO-React-Native/blob/7a7c4f23789f55110d86476d6c2c5b7e2cea739a/source/views/menus/menu-bonapp.js#L142-L155

**Comment by drewvolz** [comment]
Related to https://github.com/StoDevX/AAO-React-Native/issues/741?

**Comment by hawkrives** [comment]
The "menu" should be not-null no matter which station you choose, because the station is extracted from the found menu.

**Comment by drewvolz** [comment]
Caching issue.
