### ISSUE TITLE
Add persistent notice to menu views when data update failed

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#3356]
Now that we are caching data, we should let the user know when the data that they are viewing is out-of-date. This would be easy to do if we add a "network connection is offline" banner of some type to relevant views when the data was unable to update. Possible inspiration below:

Spotify | Slack
-- | --
![img_2300](https://user-images.githubusercontent.com/24640726/50430348-60462280-0891-11e9-8f6f-3e3821c135e4.PNG) | ![img_2301](https://user-images.githubusercontent.com/24640726/50430352-63d9a980-0891-11e9-8ad2-401cf94328ca.PNG)

**Comment by hawkrives** [comment]
I'm in favor of just doing the simple thing, which is show an Alert when the request fails due to network issues (which is what Mail &c on iOS do.)

**Comment by rye** [comment]
Triage: The caching that would necessitate this has been reverted, right? Now requests just seem to hang.

**Comment by hawkrives** [comment]
Yeah. I think we can close this… if/when we do caching again, we will open a new issue.
