### ISSUE TITLE
Get rid of status/ labels?

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3364]
This is why we have things like Projects. I'd kinda like to revisit them, but at the same time, I don't think they're necessary.

Rather, I'd like to rename some of them.

I specifically want to delete:
- `status/in-progress`

**Comment by hawkrives** [comment]
I can't see project assignment from the PR overview screen, though. 

Although we tend to just re-title with `[WIP]` in the title, which is enough for me.

I'm fine with removing `status/in-progress`, I suppose.

**Comment by rye** [comment]
I like the use of `[WIP]`.

I'd be fine with turning `status/in-progress` into `WIP` instead.

**Comment by hawkrives** [comment]
Sure, I'd be fine with that too.

**Comment by rye** [comment]
Done.
