### ISSUE TITLE
Fix rendering of fill-columns on privacy policy

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3369]
The privacy policy is rendering with sudden newlines. I think this is due to the fill-columns.

<details>
<summary>📸Screenshot</summary>

![a1cc3716-7cb8-455d-acc0-1b5f6cd5b243](https://user-images.githubusercontent.com/5240843/50521811-be872700-0a84-11e9-8702-980bbe80078f.png)

<img src="https://user-images.githubusercontent.com/5240843/50521812-be872700-0a84-11e9-9e6c-7fb3ae4d5464.png" width=380 />

</details>

**Comment by hawkrives** [comment]
What is fill-columns

**Comment by hawkrives** [comment]
I agree that it seems like our markdown view preserves line breaks in the content, in which case we should go remove them all.

**Comment by rye** [comment]
> [...] in which case we should go remove them all

…That's papering over the issue like we did with #3362. 

I think our primary issue is lying within the `markdown` module, in how it invokes `ReactMarkdown`: https://github.com/StoDevX/AAO-React-Native/blob/57587ffbb48981f87eb304bf418367195d1f8177/modules/markdown/markdown.js#L51-L71

An assumption we should not be making is that `\n` means "new `<p>`"—that is not how Markdown works. I want to make sure that those props are not the problem.

**Comment by drewvolz** [comment]
Fill-columns where the line length is a certain number of characters, I guess? I picked up on it from Kris https://github.com/StoDevX/AAO-React-Native/commit/1df860dc06b57bb38b05c5d330cdf292da6fbfa6

**Comment by rye** [comment]
>Fill-columns where the line length is a certain number of characters, I guess? I picked up on it from Kris 1df860d

Yes, `fill-column` is an Emacs variable that lets you tune the automatic line breaking.
