### ISSUE TITLE
Show BonApp special message for closed cafeterias

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#3373]
Right now, if the menu retrieved is empty, we always return the vague message "No items found." Instead, we should see if BonApp has provided a special message, which is often more descriptive, and if so, show that instead, along with the date.

Current Behavior | Desired Behavior
-- | --
<img width="326" alt="screen shot 2018-12-29 at 5 02 21 pm" src="https://user-images.githubusercontent.com/24640726/50542452-9e8e5b00-0b8b-11e9-9bf8-46acaab460b9.png"> | <img width="327" alt="screen shot 2018-12-29 at 5 23 12 pm" src="https://user-images.githubusercontent.com/24640726/50542560-748a6800-0b8e-11e9-9d61-a0dacd9cc2f8.png">

**Comment by drewvolz** [comment]
I believe I might have introduced this bug in #3047 when making sure that the debug cafe picker wouldn’t try to parse cafe information if there were no menu items.
