### ISSUE TITLE
Jest is broken around New Year?

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3375]
Q.v. #3374.

Looking at our nightly from today, [Jest seems to be broken](https://circleci.com/workflow-run/c2d6bf2d-c722-46ee-a208-db5e2525aeb9) (read: it's not producing the correct results).

Initially, I thought I would blame #3363, but:
- #3363 was merged 3 days ago, and we've had a successful nightly since then.
- I remember something about us having issues around the New Year last year or the year before that.
- The only tests that have magically gone red are the `building-hours` ones.

I'm pretty sure this is because of the New Year coming up—I think it's messing with our date parsing, or with those tests specifically because they're too general? Or maybe `isScheduleOpenAtMoment` is a bit wonky.

I will note that the app is running fine, and is producing expected results at this moment.

I'll poke around this. Others who actually wrote the tests are welcome to join.

**Comment by rye** [comment]
I'm thinking this boils down to (a) parsing of schedules or (b) between-ness?

**Comment by rye** [comment]
I think I'm closing in on the issue.

Adding a debugging print to `parseHours`, I'm getting the following (strange) console output:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/1566689/50550822-81fe2b80-0c3c-11e9-8e46-aefffca8b356.png">

This definitely explains why the tests are failing.

Digging deeper, I get:

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/1566689/50550876-5596df00-0c3d-11e9-954b-de7a9fc6ebae.png">

So it looks like `m` is correct, but `open` and `close` are a year before they should be? If we can fix that, these errors should go green and the only thing we'll be left with is the bus time failure which seems to be related.

**Comment by rye** [comment]
Tried messing with this in a node console, got:
```js
moment.tz('12:00am', 'h:mma', true, 'America/Chicago').toISOString()
// => '2018-12-30T06:00:00.000Z'
```

So `moment.tz` isn't wrong, I don't think.

**Comment by hawkrives** [comment]
Our building hours tests / code get really wonky around DST changes, I know - I wouldn't be surprised if New Years also broke stuff. 

I wish you lots of luck in tracing down the issue.

**Comment by rye** [comment]
I think this has to do with `dayOfYear` wrapping around, which would make a lot of sense. In the "handles weird times › handles Friday at 4:30pm" test case, `m` is `2019-01-04T22:30:00.000Z`, which has `dayOfYear = 4`.  We have that `open` is `2018-12-30T16:00:00.000Z` (`10am` local) before calling `open.dayOfYear()` to change it, but after changing it, `open` goes back to `2018-01-04T16:00:00.000Z`.  A similar thing happens to `close`, and this is what makes the test suite fail.

**Comment by rye** [comment]
I have successfully "resolved" this down to just one failure, by checking if `open` or `close` is before six months before `m`, and if so adding a year to those dates. I don't claim that's right, but it makes the tests green again.

Now to deal with bus schedules.

**Comment by rye** [comment]
Saw the other side of this issue today.

Looks like the logic from #3376 should be duplicated in the other direction.  I'll do that right now.

**Comment by hawkrives** [comment]
@rye looking at the test failures… do you think this will wind up with failed snapshots in six months?

**Comment by rye** [comment]
@hawkrives, no I don't think so since those snapshots are based on a specific date? I think it might also make sense to do this handling in a loop too, so we are always no more than ±6mo away from the given context moment.

**Comment by rye** [comment]
I'll try setting my computer's date to some time in 2020 and see if jest dies
