### ISSUE TITLE
Dictionary editor broken in strange way

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3386]
The editing experience at least on iOS is tricky. 

I am unable to type a space or a newline at the end of the content, but seem to be able to if I’m not at the end of the content.

The title is a single line so no spaces can be added there at the moment.

**Comment by hawkrives** [comment]
Probably calls .trim somewhere

**Comment by drewvolz** [comment]
That’s my thinking, too. This is the way the editor was broken for every part of the word and definition before. Removing gDSFP at least let’s us now edit most of the content...

**Comment by drewvolz** [comment]
Yes, trim is being called on both the title and definition after edits

**Comment by hawkrives** [comment]
We should only trim when we submit, then.
