### ISSUE TITLE
Make it clearer that "suggest an edit" ≠ "report an issue"

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3393]
Maybe make a better way for people to send us an email saying they have an issue? Under "Report a Problem?"

Maybe move "Have an App Question?" up in the "Report a Problem" thing and link to it from detail views?

**Comment by drewvolz** [comment]
> Maybe move "Have an App Question?" up in the "Report a Problem" thing and link to it from detail views?

This is issue #2468

**Comment by drewvolz** [comment]
Report a problem was removed in #6205
