### ISSUE TITLE
Sourcemaps failing to upload on nightly

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3495]
Has been occurring for a while now.  The build still succeeds and gets published, but sourcemaps aren't uploaded.

May be a wontfix, depending on how eager we are to move to Sentry.

**Comment by rye** [comment]
I think we're going to classify this as a wontfix. The "solution" will be to migrate off of bugsnag and onto Sentry?

I'm going to open a separate issue for that one.

**Comment by hawkrives** [comment]
SGTM
