### ISSUE TITLE
Tableview simple editor issues

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3496]
- [ ] Login UI lost its width. Width of settings credentials editor is 2.5 characters wide.
- [ ] Building hours editor lacks text in editable text fields
- [ ] Dictionary editor lacks text in editable text fields

**Comment by rye** [comment]
What do you mean by your first item?  I am not seeing the same issue. Could this be a SafeAreaView or platform related?

The Building Hours/Dictionary editors seem to lack text in editable text fields for me too. Perhaps this issue should take on one of the points and another could be opened for the second and third checkboxes?

**Comment by drewvolz** [comment]
I think these are all the same issue with a relation to the width of the editable text area.

**Comment by rye** [comment]
Okay, that makes sense. I have a similar issue on Android where the text input does not even show any action happening while I type my username and password, which seems identical to the video you sent me.

We are using our own custom layer of abstraction on top of TableView, which will probably need to get fixed to fix this issue.

FWIW, my approach to doing this would be to set a `placeholder` of `Username` and a `placeholder` of `Password`, but this would change the behavior, I think.

Was the previous approach to have `Username` visible while the user was typing in their username? If not, (e.g. it was hidden while they were typing) then I think we were custom-implementing a janky placeholder equivalent.

As to the other two instances, I think this relates to possible issues with `CellTextField`.

FWIW, we upgraded to `react-native-tableview-simple` v2.0.1 a month ago, which [didn't seem to get much testing](https://github.com/StoDevX/AAO-React-Native/pull/3417).  The issues there might have been right under our noses.

Is it possible that SafeAreaView is causing this? `rn-tableview-simple` added a `withSafeAreaView={false}` option, which could be tested.

**Comment by hawkrives** [comment]
At the core, we're looking at this chunk of code for the first item on the list:

https://github.com/StoDevX/AAO-React-Native/blob/c2255d7b2f12b57a8042de9dd58360b3a0a4b139/source/views/settings/screens/overview/login-credentials.js#L87-L110

As such, the `placeholder` prop is passed _directly_ to the underlying `TextInput`, which is a component provided by RN itself.

https://github.com/StoDevX/AAO-React-Native/blob/c2255d7b2f12b57a8042de9dd58360b3a0a4b139/modules/tableview/cells/textfield.js#L100

This could well be a rn-tableview-simple@2.0 regression, IMO.

**Comment by drewvolz** [comment]
I think the culprit is here:

https://github.com/StoDevX/AAO-React-Native/blob/c2255d7b2f12b57a8042de9dd58360b3a0a4b139/modules/tableview/cells/textfield.js#L114-L116


where those styles look like

https://github.com/StoDevX/AAO-React-Native/blob/c2255d7b2f12b57a8042de9dd58360b3a0a4b139/modules/tableview/cells/textfield.js#L20-L30

<hr>

Things appear to look _normal_ (testing on iOS) when I reduce the styles down to:

```js
singlelineCell: {
    paddingTop: 0,
    paddingBottom: 0,
},
multilineCell: {
    paddingTop: 10,
    paddingBottom: 10,
},
```
