### ISSUE TITLE
Edit home not scrollable via regular swipe

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3497]
I can only seem to trigger the scroll if I do one of the following
- grab the top empty area and flick down
- move a row below the bottom of the screen
- once at the bottom, grab the bottom and flick up

**Comment by rye** [comment]
Can't repro on android, for what that's worth.

**Comment by hawkrives** [comment]
yeah but I can drag the items around really well now (iOS) lol

**Comment by hawkrives** [comment]
This is still an issue on 0.59.

**Comment by rye** [comment]
Triage: I cannot verify without an iOS device. Can someone check and upload a screencap?

**Comment by hawkrives** [comment]
https://gfycat.com/badshockedcranefly

[edit] Note that I am never grabbing the dragger thing on the right; that's just from me attempting to scroll.

@drewvolz I want to replace the iOS edit view with the Android one, which has the explicit up/down arrows.

**Comment by drewvolz** [comment]
@hawkrives I'd decently opposed to that idea

**Comment by drewvolz** [comment]
The android arrows were a stopgap to get it _working_ on the android platform and not meant to be a replacement for this behavior IIRC.

**Comment by rye** [comment]
Resolved by #3977, which removed the Home view editor entirely.
