### ISSUE TITLE
Balances logs-in when user has not agreed to terms

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3506]
Fallout from #3503. 

> Next, I needed to address (at the very least) the way in which the Balances screen always says "not logged in".
> 
> I did this by triggering the login mechanism if you aren't marked as logged in. Also fairly straightforward.

If you have not agreed to our notice that BonApp is the source of truth, you’ll still be able to use this screen anyways as it’s now going through the motions of logging you in and refreshing.

I think we need to tie-in the redux value of that alert before auto-logging-in and refreshing.

**Comment by hawkrives** [comment]
So this isn't actually fallout from #3503 – it pre-dates that.

The `getBalances` method will also perform a login; it just doesn't inform redux that the user has been logged in. So, if you took yesterday's build, didn't agree to the terms, but had logged in in Settings, you would also be able to see your balances.

I agree that we should check the approval status before fetching, but I just wanted to clarify the source of the issue.

**Comment by drewvolz** [comment]
Thanks for clarifying — my bad for incorrectly pointing.
