### ISSUE TITLE
Filter popover not anchored with many items

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3507]
Correct | Incorrect
--|--
<img src="https://user-images.githubusercontent.com/5240843/53252033-e5bc3800-3672-11e9-9c71-758f8a25e867.png" width="250" /> | <img src="https://user-images.githubusercontent.com/5240843/53252032-e5bc3800-3672-11e9-815a-1262e1aa0c7e.png" width="250" />

**Comment by rye** [comment]
I don't know if I'd call this a bug.

As a user, I would prefer it to show as much of the list as possible instead of anchoring. Am I alone in this feeling?

**Comment by hawkrives** [comment]
I think this is intended on the underlying library's part, and I like what it's doing now.

**Comment by drewvolz** [comment]
It may or may not be intended (unsure that we can say it is) but it seems confusing to me to cover the toggle that enabled the filter. The triggering button is the way we close the other filter popovers, and I’d very much not like to break from that design.

**Comment by drewvolz** [comment]
The white space around where we can tap off is significantly reduced in this design (as the button argument is part of the white space but still being covered by an alpha layer) so I’d like to bring back that tap-off space

**Comment by drewvolz** [comment]
Alright. Closing.
