### ISSUE TITLE
Hours not rendering on view open

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3520]
To reproduce:

1. Reset everything
1. Force quit app
1. Open app
1. Go to Building Hours
1. List is empty

**Comment by rye** [comment]
The network request is not fired off until the timer rolls over, it seems.

**Comment by rye** [comment]
(PTR doesn't work.)

**Comment by drewvolz** [comment]
I’ve noticed this intermittently. I would say it was a visual blip and the hours loaded after a second on my device.

**Comment by drewvolz** [comment]
But I think this is a symptom of our larger caching impl

**Comment by hawkrives** [comment]
It's not from caching

**Comment by hawkrives** [comment]
Caching always returns _some_ data

**Comment by hawkrives** [comment]
I just had this happen to me this morning.

**Comment by drewvolz** [comment]
I've noticed a few of our listviews have logic that very briefly shows "list is empty" logic or text before the actual view loads.

**Comment by rye** [comment]
I can no longer reproduce this on my device; should we close?

**Comment by drewvolz** [comment]
I think this is still happening. A fresh install will show "no hours" as the loading state until we've fetched. It's accurate but not ideal.

**Comment by hawkrives** [comment]
I'd like to think that we can close this now - @drewvolz thoughts?

**Comment by drewvolz** [comment]
I think we can close it
