### ISSUE TITLE
Contacts view funkiness

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#36]
![contacts](https://cloud.githubusercontent.com/assets/5240843/17577194/dcb10028-5f48-11e6-8ee1-61b802433837.png)

**Comment by drewvolz** [comment]
And `react-native-card-view` did not push an update recently.

**Comment by elijahverdoorn** [comment]
I'm seeing the same on android. I can look into it later tonight.

**Comment by elijahverdoorn** [comment]
It has to do with the amount of text in the card. If I shorten the text in the card, it renders fine. I'm not really impressed with that, so I'm just going to make something similar myself. :(

**Comment by elijahverdoorn** [comment]
Finished.
