### ISSUE TITLE
Building hours audit

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#361]
We need to audit the building hours to be sure we are not still using summer hours for any location. I think I noticed the post office still using summer hours.

**Comment by hawkrives** [comment]
Post Office is definitely using Summer Hours.

**Comment by zimmer18** [comment]
work in branch [building-hours](https://github.com/StoDevX/AAO-React-Native/pull/382)

**Comment by drewvolz** [comment]
Closed by #382 and #390
