### ISSUE TITLE
switch to presence for student org stuff

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3631]
to follow up on #932…

SA _is_ moving to Presence. The move is now far enough along that Olaf has begun importing Presence events into the Master Calendar ([calendar](https://wp.stolaf.edu/calendar/event/debunking-sexual-health-myths/), [presence](https://stolaf.presence.io/event/debunking-sexual-health-myths)).

We should start putting stuff in to make the switch back to Presence from stolaf.edu/orgs/list.

I think v2.8 should include a new Presence/Orgs/something tab in Calendar, as [not every event](https://stolaf.presence.io/event/a-hole-new-world-anal-health-and-pleasure) will be imported.

I think we can switch the _list_ of orgs entirely within ccc-server, as long as we make sure modify Presence's responses to return the same data structure as Orgs currently expects.

---

- fetch events: https://github.com/StoDevX/AAO-React-Native/pull/939 / https://api.presence.io/stolaf/v1/events
- fetch orgs: https://github.com/StoDevX/AAO-React-Native/pull/991 / https://api.presence.io/stolaf/v1/organizations

**Comment by drewvolz** [comment]
I have a local branch that works on this but I’m not sure it’s worth using. I’ll check later

**Comment by hawkrives** [comment]
I just found https://stolaf.presence.io/Error/Forbidden/ … bah.

**Comment by hawkrives** [comment]
![image](https://user-images.githubusercontent.com/464441/55654080-015c4780-57b6-11e9-8549-d080a4a8a720.png)

this one's even better.

yes, I love blurry 404 pages.

**Comment by rye** [comment]
Triage: what do we need to do to land this for v2.8? Does existing functionality need to be replaced somewhere with this API call, and/or does this API call need to be proxied?

**Comment by hawkrives** [comment]
We should just need to adapt the old code we had for Presence onto CCC-server; the apps should be able to continue using the same endpoint (/v1/orgs, I think), at least initially

**Comment by rye** [comment]
Where does that old code live?

**Comment by hawkrives** [comment]
https://github.com/frog-pond/ccc-server/pull/291 I think, so I think this issue can be closed.

**Comment by rye** [comment]
Sounds good. Closing.
