### ISSUE TITLE
Switch to react-native-community packages

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3643]
https://github.com/react-native-community/react-native-webview

At some point soon, RN will deprecate and then remove the WebView component from core.

I _think_ the only thing that uses WebView is the radio player.

---

- [x] [Async Storage](https://github.com/StoDevX/AAO-React-Native/pull/3565) (not merged)
- [x] [NetInfo](https://github.com/StoDevX/AAO-React-Native/pull/3566) (merged into Async PR)
- [x] [Datetime Picker](https://github.com/StoDevX/AAO-React-Native/pull/5518) (merged)
- [ ] MaskedViewIOS (we don't use it anywhere?)
- [x] WebView
- [x] Picker

**Comment by drewvolz** [comment]
`modules/HtmlContent` imports `WebView` but I do not think we use `HtmlContent` anywhere?

**Comment by rye** [comment]
@drewvolz moodle… and such use `trackedOpenUrl`/`openUrlInBrowser`… I suppose that must be different from a `WebView` because `git grep WebView` only gives—as you say—`modules/html-content/index.js` and `source/views/streaming/radio/player.js`.  As you say, `HtmlContent` is not used anywhere. (The only occurrence of that text is the export.)

**Comment by hawkrives** [comment]
Yeah, openUrl/etc use SFViewController or Chrome Custom Tabs - completely different native implementations from the WebViews.

**Comment by hannesmcman** [comment]
This also applies to Async Storage, NetInfo, and MaskedViewIOS...is there anything else?

**Comment by drewvolz** [comment]
Keeping this updated, I think this is the current state:
- [x] [Async Storage](https://github.com/StoDevX/AAO-React-Native/pull/3565) (not merged)
- [x] [NetInfo](https://github.com/StoDevX/AAO-React-Native/pull/3566) (merged into Async PR)
- [ ] MaskedViewIOS
- [ ] WebView

**Comment by hawkrives** [comment]
I updated the OP with a checklist

**Comment by drewvolz** [comment]
Is this one done as of #5513

**Comment by hawkrives** [comment]
Yes, although RN removed `Picker` recently, so I'll need to add that to the checklist.

**Comment by hawkrives** [comment]
I think this is done!
