### ISSUE TITLE
5s-sized screen has line wrapping on "Important Contacts"

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#37]
<img width="432" alt="screen shot 2016-08-11 at 7 09 35 pm" src="https://cloud.githubusercontent.com/assets/464441/17585502/2707b424-5ff7-11e6-8574-0a8a698e6cea.png">

Haven't looked at it any further yet. We might just be able to shrink the left-right-padding on the buttons.

**Comment by drewvolz** [comment]
As an alternative approach, could we attack this with font resizing based upon screen size?

**Comment by hawkrives** [comment]
This is fixed.
