### ISSUE TITLE
Switch to Dependabot

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#3757]
Since GitHub acquired them… and they have Ruby support. 

I essentially flipped a coin to pick between Rennovate and Dependabot when we moved from Greenkeeper. 

I can work on this, or someone else can take it on.

**Comment by rye** [comment]
I'll do it.

- [x] Add an installation of Dependabot on `StoDevX/AAO-React-Native` only
- [x] Remove installation (webhooks) of Renovate
- [x] Delete Renovate files

**Comment by rye** [comment]
Installed. I will let it generate some PRs, and if all looks good I will then delete the Renovate installation.

**Comment by hawkrives** [comment]
I think we can go ahead and remove the renovate config file.
