### ISSUE TITLE
Fix regression in HTML parser

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3921]
Introduced by #3912, likely, we're getting exceptions like:

```
TypeError: TypeError: TypeError: undefined is not an object (evaluating 'u.default.parseDOM')
```

Nightly 2.8.0-pre+65526 on Android works fine, +65786 does not. If it's not #3912, it's something else in that range.

**Comment by hawkrives** [comment]
Thanks all

**Comment by rye** [comment]
Resolution confirmed in Android 2019-08-09 nightly.
