### ISSUE TITLE
Use the app icons

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#40]
Ass a followup to #32, it'd be nice if we actually used the app icons to, you know, show the app.
- [x] Android
- [x] iOS

Need to do research to figure out how to do this. Are we supposed to just do thorough Xcode for iOS?

**Comment by drewvolz** [comment]
If you would like, I could help do this? I have added images for both iOS and Android apps before. I believe [this is a good guide](http://stackoverflow.com/a/34333915) on how to do it.

**Comment by hawkrives** [comment]
Sounds good to me!

**Comment by drewvolz** [comment]
This is fixed by #117
