### ISSUE TITLE
Tapping on radio tabs is crashing at the moment

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#4005]
We suspected the `parser` (#3996) and/or `buffer` (#3999) upgrades.

I've gone thru the steps of reverting both of these changes locally on iOS but the crash remains.

**Comment by hawkrives** [comment]
If you install build 179569561 from TestFlight, does it crash?

**Comment by drewvolz** [comment]
Both 179569561 and 179655893 function correctly.
