### ISSUE TITLE
Nix embedded webviews for OAuth requests

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#401]
We must change the webviews we use to authenticate with Google if we would like to continue doing so. We have a few months.

> Notice to developers: authorization requests in embedded browsers will be blocked on April 17, 2017

> In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views”, such as the WebView UI element on Android and UIWebView/WKWebView on iOS, and equivalents on Windows and OS X.

> Modern “in-app browser tab” patterns available on some operating systems, such as Chrome Custom Tabs on Android and SFSafariViewController on iOS offer further UX improvements for browser-based OAuth flows.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by elijahverdoorn** [comment]
Is there a reason we can't use Passport for all of this? http://passportjs.org/

Get the login that way? There might be an issue with us using this, so we get the user's Google login, but we fail to get the user's St Olaf login since we don't have the real Google login. Just throwing that out there, I'll do more research and maybe make some kind of test. (may not be able to do much until after finals)

**Comment by hawkrives** [comment]
Links for embedded browsers: 

- SFViewController: https://www.npmjs.com/package/react-native-safari-view
- Chrome Custom Tabs: https://www.npmjs.com/package/react-native-custom-tabs

**Comment by hawkrives** [comment]
We have a big problem with this: both those options, and every other alternative that Google will support, maintains a separate cookie storage from our code, to prevent exactly what we're trying to do.

**Comment by elijahverdoorn** [comment]
I've been poking at this, at least to get some sort of sign-in going on, found [this](https://github.com/devfd/react-native-google-signin) repo, which is out of date and doesn't work with current versions of RN. Additionally, if I understand correctly, we still would have a problem sending this authentication to the SIS server even if we did get it working.

**Comment by hawkrives** [comment]
That's my understanding, as well.

Did I ever show you the response I got from Craig and Rich, about Oauth stuffs?

**Comment by elijahverdoorn** [comment]
Yeah, I think I saw that but have since forgotten what it said.

**Comment by hawkrives** [comment]
Rich:

> www.stolaf.edu is using mod_auth_openidc. Check their documentation and your mobile toolkit's documentation to see if they support either 2-legged OAuth or long-lived mobile tokens. Maybe your app could get a long-lived Google token good only for www.stolaf.edu.
> 
> That's all I know about OAuth on mobiles. In fact it's a little bit more than I know for sure.

So, we need to do research on "two-legged oauth" and/or if we can request a token from Google's OAuth for the entire www.stolaf.edu domain, I guess.

**Comment by elijahverdoorn** [comment]
Alright, down that rabbit hole I go I guess! 🐰

**Comment by elijahverdoorn** [comment]
oops

**Comment by hawkrives** [comment]
quick summary of the current auth flow:

1. https://www.stolaf.edu/sis/login.cfm
2. https://accounts.google.com/o/oauth2/auth?client_id=368607578799-f5geh8k6l3km5et1ufbtusikso5sb7rj.apps.googleusercontent.com&redirect_uri=https://www.stolaf.edu/sis/login.cfm&scope=https://www.googleapis.com/auth/userinfo.profile+email&state=&response_type=code&hd=stolaf.edu
3. https://www.stolaf.edu/sis/login.cfm?code=4/QsTCNp1Kr2X90vIZLXOurJoWeZpxjERj93nW_hmIQM8#
4. https://www.stolaf.edu/sis/index.cfm

and we're in to the SIS.

**Comment by hawkrives** [comment]
Closing this, since we've worked around it in `master`.
