### ISSUE TITLE
Replace iOS beta onboarding link with testflight

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#4062]
Swap out the defunct heroku/fastlane signup with testflight's link. This is a note so that we are aware that it's broken and that we should correct the link once we promote our next beta build.

**Comment by rye** [comment]
Triaging this… is there any place besides the README that we need to change?

**Comment by rye** [comment]
Oh, also—do we know who controls the boarding-aao Heroku app? Apparently it's throwing errors, and while we're [changing to a public TestFlight link](https://developer.apple.com/testflight/) I think we should also deactivate that app.

**Comment by hawkrives** [comment]
Me. I'll try to remember to do that.

**Comment by rye** [comment]
@hawkrives I can't seem to find the login password for TF so you might have to take care of changing the link.

**Comment by rye** [comment]
I cannot generate the TestFlight link, however I have confirmed that I do have control over the boarding-aao Heroku app.

**Comment by drewvolz** [comment]
Closed by #6694
