### ISSUE TITLE
Building hours view is missing its VC title

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#4234]

**Comment by hawkrives** [comment]
@drewvolz Is this still an issue? I feel like we thought this vanished on its own.

**Comment by drewvolz** [comment]
This is still an issue.

**Comment by hawkrives** [comment]
This is indeed still an issue:

<img src=https://user-images.githubusercontent.com/464441/139586607-f19f6039-736d-43fc-92d8-e0a0a3e6d541.jpeg width=480 />

**Comment by drewvolz** [comment]
Fixed
- https://github.com/StoDevX/AAO-React-Native/commit/e2df00be3d8783bdace67700bf203db68ac60640 withn #5513
