### ISSUE TITLE
Android OneSignal Notification Package breaks build

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#45]
@elijahverdoorn: The build is failing with ([context](https://ci.appveyor.com/project/hawkrives/aao-react-native/build/1.0.43#L2646))

```
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-onesignal : Configuration with name 'default' not found.
```

on Android on both OS X and Windows. Did you ever see that error while you were building notifications or have any idea what it's talking about?

**Comment by hawkrives** [comment]
Found it. We hadn't added `react-native-onesignal` to the package.json.

**Comment by elijahverdoorn** [comment]
Thanks for the fix.
