### ISSUE TITLE
Filter html from item descriptions

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#462]
We need to clean up the item descriptions to prevent raw HTML from appearing. I know @hawkrives mentioned possible performance concerns with cleaning up each of those strings.

<hr>

<img width="540" alt="bonappimage" src="https://cloud.githubusercontent.com/assets/5240843/21575356/a49b35a6-ced7-11e6-9bc3-6b2e41c4672a.png">

**Comment by hawkrives** [comment]
Note: none of our BonApp menus have any HTML, that we've seen. This example was from some other cafe, somewhere else, but it shows us that they _can_ include HTML.

**Comment by hawkrives** [comment]
So you know how I said our cafes didn't have any HTML

Well

Look at the first item

<img width="375" alt="screen shot 2017-01-04 at 5 00 54 pm" src="https://cloud.githubusercontent.com/assets/464441/21662466/67c71714-d29f-11e6-9215-dc0ac55e4351.png">

**Comment by hawkrives** [comment]
Also

<img width="373" alt="screen shot 2017-01-04 at 5 02 43 pm" src="https://cloud.githubusercontent.com/assets/464441/21662515/a0f5eb6e-d29f-11e6-92ac-51399ef3457c.png">

**Comment by elijahverdoorn** [comment]
Found another example of this: 
![screen shot 2017-01-06 at 1 50 01 pm](https://cloud.githubusercontent.com/assets/12042702/21730835/284da71e-d417-11e6-8627-f814933ea656.png)

**Comment by drewvolz** [comment]
Yep! Thanks for reporting, @elijahverdoorn . I think  #496  will solve this.

**Comment by elijahverdoorn** [comment]
@drewvolz Just approved that. Thanks for fixing.
