### ISSUE TITLE
Turn off wifi reporting in help tools

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#4699]
An out of band conversation with @hawkrives revealed that the backend for wifi reporting no longer collects the reports and the db entry for aao has been nixed

(a) So we can disable this view from the backend by changing the enabled value here to false. https://github.com/StoDevX/AAO-React-Native/blob/master/data/help/0-wifi.yaml

(b) Additionally, we should remove the location collection logic, and/or this feature + deps + views altogether? 

Thoughts @hawkrives and @rye?

**Comment by rye** [comment]
Pity to see it go, but it does mean that the privacy policy, location permissions, and such can all get removed.

That should happen, and we should aim to publish a new release in short order.

**Comment by hawkrives** [comment]
Oh, that's true, we can remove location permissions. Excellent point.
