### ISSUE TITLE
Dictionary flex property

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#48]
Similarly to the [menu issue](https://github.com/StoDevX/AAO-React-Native/commit/3daf29c9f6336e6abab31f56463ed1a1dea5069a) the dictionary is not rendering properly.

**Comment by drewvolz** [comment]
This is caused by `collapsibleRow.js` line 19, where a similarly named `container` styling has `flex: 1`. Removing this line does fix the problem, but I am unsure if that is the solution.

**Comment by hawkrives** [comment]
Fixed. That was the problem. 

The `container`s from collapsibleRow are inserted into the listview as direct children, so when `flex` goes to split up the available space evenly, it doesn't take into account the collapsed nature of some of them – the available space went up, so they all get a little bigger.

**Comment by hawkrives** [comment]
Fixed by 400034574038d1c18484177e41b3fc69c9ab53b0
