### ISSUE TITLE
Version 2.1.0

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#486]
- [x] Collect issues that need to be resolved before shipping
- [x] Agree on a feature freeze date
- [x] Write changelog
- [x] Test aggressively
- [ ] Build binaries
- [ ] Submit to app store / play store
- [ ] Do something about FAQs (either add more or remove it)
---

## Issues / PRs
- [x] #470 – FancyMenus Filtering
- [x] #496 – Wrapper for trimmed text with spaces
- [x] #440 – Android tab-view upgrade

## Feature freeze date
- 1/15/17

#### New Features

We can't wait to show you what we've been up to!

* You can reorder the home screen now!
* Check out the Northfield events calendar!
* Discover new student orgs to join!
* Meals Remaining in SIS is back!
* Hours redesign! More buildings! More hours!
* Menus redesign! Better menus! Faster loading!
* There's a new FAQs section in Settings! Check it out.
* The Pause Events calendar is now included!

#### Bug Fixes

* We've eradicated the pesky lists that liked to end behind the tab bars.
* Contacts will no longer vanish at inopportune moments.
* SIS probably still has bugs. We fixed some, though.
* News will not scroll sideways when the article includes a video.
* Oh, and we made News load again, too.
* Oleville will properly display images now.
* The bus schedules no longer report incorrect times between loops.
* We fixed a few tricky DST and timezone issues.

#### Miscellaneous

* The app is significantly smaller (from ~17 MB down to ~5 MB!). 
* We tweaked the app icon to include a white background (on iOS), so that the app stands out a bit more.
* The Calendar now includes "Ongoing" and "Today" headings.
* Hours gained information for a bunch of popular spots around campus (and additional hours for some existing buildings!) If we don't have a building or office that you want to know hours for, let us know and we'll add it!
* Menus can be filtered now! Only want to see the Deli station? You can do that! Only care about gluten-free vegan selections? Turn that filter on! Let us know what you think.
* We added a list of all the student organizations on campus! St. Olaf is transitioning to a new service called "Check I'm Here", and they provide a nice list of student orgs. We even highlight the "new" orgs, in case you're hip and want to join them before anyone else.
* The SIS view … well, we fixed some bugs, and probably made some new ones too. It still can't keep you logged in for more than ~15 minutes, though. We're working on it.

**Comment by hawkrives** [comment]
@elijahverdoorn @drewvolz Seeking comments here. 

I'd like to ship sometime this month? Earlier is better than later?

**Comment by elijahverdoorn** [comment]
Yes, let's do that. I'm down for feature freeze whenever you're ready, you're way more up to date on what's in progress and what's done right now. @hawkrives

**Comment by hawkrives** [comment]
Drew and I will make up the changelog for you, since we, ah, got a little out of control since 2.0.1 in terms of changes. He's been keeping track of closed things in https://github.com/StoDevX/AAO-React-Native/projects/1

**Comment by elijahverdoorn** [comment]
@hawkrives I'm happy to help, but I'd welcome your lead since you and @drewvolz clearly are the most active here.

**Comment by drewvolz** [comment]
I've put a freeze for features in 9 days, so on 1/15. Does that date work for everyone? A halfway point in the month.

**Comment by elijahverdoorn** [comment]
Added note about FAQs

**Comment by hawkrives** [comment]
We added a draft changelog.

**Comment by hawkrives** [comment]
I am working on a refactoring of the Settings screen to make it use redux, which would solve both #220 and, as a side effect, also solves #501.

It's not quite ready, but I should be able to finish it up tonight /slash/ tomorrow and put it up for review tomorrow afternoon/evening.

I would request that we hold off on shipping until I have a chance to let you all see it? I understand if you'd rather not, but I'm regarding it as a bugfix and not a feature, so it doesn't fall under the "feature freeze" label 😝

**Comment by elijahverdoorn** [comment]
@hawkrives I'd consider that a bugfix. I'll hold on shipping.

**Comment by hawkrives** [comment]
Thanks.

**Comment by elijahverdoorn** [comment]
Seeing nothing more in the shipping hold category and not knowing of any outstanding issues, I'd like to make the cut at the current master if people are ok with that. (including #620)

**Comment by hawkrives** [comment]
The only possible shipping hold I know of is #622. I'm also curious what your tests show for the Courses view, since my only account is special (fifth-year) which might be the source of the problems in #588.
