### ISSUE TITLE
Building Hours not rendering

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#49]
The building hours view is totally empty when I load it on android.

**Comment by drewvolz** [comment]
It might also be empty on iOS. I was about to log an issue.

**Comment by elijahverdoorn** [comment]
I'm looking into the contact card issue, then this one. If anyone figures it out, make a PR.

**Comment by hawkrives** [comment]
<img width="487" alt="screen shot 2016-08-15 at 9 45 16 am" src="https://cloud.githubusercontent.com/assets/464441/17653237/fb5c5b6c-62cc-11e6-8dcd-61e2d2f2995d.png">

It's not … totally empty on iOS, at least

**Comment by elijahverdoorn** [comment]
Hmmm... Wonder if this has something to do with the OneSignal integration on Android? That's the only difference that I can think of between the two that might cause this.

**Comment by hawkrives** [comment]
<img width="644" alt="screen shot 2016-08-15 at 10 50 39 am" src="https://cloud.githubusercontent.com/assets/464441/17653826/1d8661d4-62d6-11e6-9e98-30794be55060.png">

Hmm.

**Comment by elijahverdoorn** [comment]
It's not loading at all for me... I hate this kind of bug...
