### ISSUE TITLE
Android icon needs drop shadow

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#490]
Turns out that Android launchers (at least Trebuchet and Google Now Launcher) don't add any sort of drop shadow to the icons. 

The only icon I could find, besides ours, without a drop shadow was for Instapaper.

Both our icon and their icon look weird without a shadow.

- Instapaper: https://play.google.com/store/apps/details?id=com.instapaper.android
- AAO: https://play.google.com/store/apps/details?id=com.allaboutolaf
- slack: https://play.google.com/store/apps/details?id=com.Slack

**Comment by elijahverdoorn** [comment]
I did some photoshopping, what do we think of this? Too much?

<img src=https://cloud.githubusercontent.com/assets/12042702/21732455/305e3042-d41f-11e6-88e0-44d24af7ea74.png width=256>

**Comment by hawkrives** [comment]
It seems a tad heavy.

Can you figure out the drop shadow that Camera and Email use in this screenshot?

<img src=https://cloud.githubusercontent.com/assets/464441/21734314/650ba000-d428-11e6-9eae-e16757aa9503.png width=400>

**Comment by elijahverdoorn** [comment]
Another Attempt

<img src=https://cloud.githubusercontent.com/assets/12042702/21781923/1db67fee-d677-11e6-9f49-cebd45e91ff3.png width=256>

**Comment by hawkrives** [comment]
Nice! I'll try and throw that into my sim later.

**Comment by hawkrives** [comment]
<img width=400 src=https://cloud.githubusercontent.com/assets/464441/21783264/30c3909a-d67c-11e6-9def-4878b7e63163.png>

It's better! I'm going to try the first option again.

**Comment by hawkrives** [comment]
With the first icon, it was definitely a more noticable shadow:

<img width=400 src=https://cloud.githubusercontent.com/assets/464441/21783373/b6031654-d67c-11e6-964c-f855b41e9794.png>

**Comment by hawkrives** [comment]
Maybe increase the shadow offset on your second icon? And it appears that Android icons commonly have the shadow straight down, rather than off to the right (light source directly north, instead of nw) but you can better judge that.

**Comment by hawkrives** [comment]
hi @rye

i'm testing on android again today, and the lack of a drop shadow bugs me

so i'm assigning to you

you can reassign as you see fit

**Comment by rye** [comment]
I'll do it :)

**Comment by rye** [comment]
No longer needs this. Closing.
