### ISSUE TITLE
Ensure that "Sign In"/"Sign Out" labels work correctly

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#501]
Sometimes "sign out" appears when the signin process didn't finish successfully. It should still show signin for that case.

**Comment by hawkrives** [comment]
<img width=320 src=https://cloud.githubusercontent.com/assets/464441/21743525/826e3864-d4c9-11e6-9b88-86704493da49.jpg>

**Comment by drewvolz** [comment]
I can confirm this behavior.
