### ISSUE TITLE
Add Ole Avenue Construction camera

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#5030]
Just spot-checked the [webcams](https://www.stolaf.edu/multimedia/webcams/) page, and found a new one:

https://www.stolaf.edu/multimedia/webcams/?cam=oleave

(This is probably a temporary one, but it's going to stick around for a while?)

**Comment by hawkrives** [comment]
I talked to Joshua last week; it'll be up for the duration of the Ole Ave project, at least.
