### ISSUE TITLE
Add a • group to the top of Orgs list?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#505]
To group all the "new" orgs together?

They'd be duplicated then; both in the top there, and in the alphabetical sections.

**Comment by hawkrives** [comment]
<img width="400" alt="detail" src="https://cloud.githubusercontent.com/assets/464441/21743545/e664fd58-d4c9-11e6-9636-8f906de55648.jpg">

**Comment by drewvolz** [comment]
We could remove them from the general list view if they're featured at the top. That is the way we are doing this on the calendar with Ongoing and Today.

**Comment by hawkrives** [comment]
Not quite. In both of those views, the normal sort order would put the highlighted events at the top anyway – if we pull these out, in Orgs, then you have to look through both the "new" section and the alphabet for the org you want. 

IMHO.

**Comment by drewvolz** [comment]
Fair enough. There's no harm in displaying it in both, then.
