### ISSUE TITLE
[discussion] Add "late night" hours to the Pause hours?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#508]
Should we add "late night" to the pause hours view? Like how the Cage has a separate Late Night set.

**Comment by drewvolz** [comment]
I would say yes. They have a separate menu for late-night.

**Comment by hawkrives** [comment]
What are the hours for their late night menu?

**Comment by drewvolz** [comment]
The "late night" menu is offered **Fri - Sat:  9:00pm - 2:00am**

**Comment by hawkrives** [comment]
Do we want to call it "Late Night", or does "Late Nite" fit better with the Pause?

**Comment by drewvolz** [comment]
I have only seen it referred to as "late night" --[ here are posts on the FB wal](https://www.facebook.com/thelionspause/posts/360880793964685?match=bGF0ZSBuaWdodA%3D%3D)l for reference.
