### ISSUE TITLE
Change campus map URL?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#511]
From the direct link, to "map.stolaf.edu".

**Comment by drewvolz** [comment]
I have no issue with the change. Might be more permanent if they ever switch third-party services.

**Comment by hawkrives** [comment]
This should be as simple as changing [data/map.yaml#L1](https://github.com/StoDevX/AAO-React-Native/blob/master/data/map.yaml#L1):

```diff
-url: 'https://www.myatlascms.com/map/index.php?id=294'
+url: 'http://map.stolaf.edu'
```

---

**Update**: It looks like `map.stolaf.edu` is only available over HTTP, not HTTPS, so we'd either need to add an exception like https://github.com/StoDevX/AAO-React-Native/blob/master/ios/AllAboutOlaf/Info.plist#L96-L100, or wait for it to be available over HTTPS. Which we'd probably need to ping IT about.

**Comment by drewvolz** [comment]
What do we prefer? An exception, or an `https` link?

**Comment by hawkrives** [comment]
I think it's unlikely that Olaf will change map providers this year; things like that _usually_ seem to happen over summer breaks.

I'd rather not add any more exceptions to our list, since we've already got 12.

**Comment by drewvolz** [comment]
Should we send a note to ask for `https`?

**Comment by hawkrives** [comment]
I believe so, yes.

**Comment by hawkrives** [comment]
_Let me clarify:_ there is a website served over HTTPS, however, the certificate is not valid for `maps.stolaf.edu`.

![image](https://cloud.githubusercontent.com/assets/464441/21776180/e82ca6ea-d65e-11e6-8c73-210252d476d5.png)

Given that it reports being for `*.boisestate.edu`, I believe that this is a misconfiguration on MyAtlasCMS' side.

**Comment by elijahverdoorn** [comment]
Has anyone sent a note to IT? If not, I'll do it.

**Comment by drewvolz** [comment]
I did not.

**Comment by hawkrives** [comment]
I have not. Officially delegating to @elijahverdoorn.

**Comment by elijahverdoorn** [comment]
Email sent.

**Comment by elijahverdoorn** [comment]
Here is the response I got:


> On 1/13/17, at 11:01 am, Dan Beach wrote:
> Elijah,
>
> I would recommend using the https://www.myatlascms.com/map/index.php?id=294 address as the permanent link. Alternatively, you can use wp.stolaf.edu/map/  The future of map.stolaf.edu is more uncertain than you might think and the myatlas.com one is the most reliable.

**Comment by hawkrives** [comment]
In that case, I'm going to close this issue in favor of leaving it pointing at the myatlascms site.

**Comment by hawkrives** [comment]
Thanks for following up, @elijahverdoorn!

**Comment by drewvolz** [comment]
Thanks, Eli!
