### ISSUE TITLE
Prevent closing-of-filterviews-by-dragging-downwards

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#514]
See https://github.com/facebook/react-native/issues/1014#issuecomment-96233760

> The scene configs are objects with lots of overridable properties in them. If you want to start with FloatFromBottom and disable gestures, you can do this:

```
configureScene={() => ({
  ...Navigator.SceneConfigs.FloatFromBottom,
  gestures: {}, // or null
})
```

**Comment by drewvolz** [comment]
This needs to apply to all views that have a close button. Settings and Edit Home would fit this.

**Comment by hawkrives** [comment]
Alright. I propose that we make a file, `views/components/scene-configs.js`, where we store common and custom configs. 

Then we'd make our custom FloatFromBottom config in there, and provide it instead of Navigator.SceneConfigs.FloatFromBottom when calling navigator.push(). 

That's my proposal.

**Comment by hawkrives** [comment]
I have a local branch that solves this, which I'll push next time I have Internet on my laptop.
