### ISSUE TITLE
List pause on-campus pizza delivery hours

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#519]
I feel that these hours should be listed on the Pause Hours as a schedule. The Pause lists them on their website as a schedule. Objections?

**On-campus Pizza Delivery**
Sunday – Thursday: 6:00PM – 12:00PM
Friday – Saturday: 8:00PM – 2:00AM

**Comment by hawkrives** [comment]
I see a benefit of people knowing if they can be lazy and have a pizza delivered easily?

Or that might be an objection. I'm not sure.

**Comment by drewvolz** [comment]
If we do end up including this, we should list that on-campus excludes honor houses.

**Comment by hawkrives** [comment]
There's no support for showing notes on the main list screen, and lazy people aren't going to open the view to read the notes.

IMHO.

**Comment by elijahverdoorn** [comment]
Maybe we could list them in the contact card? Seems like the place people will be if they're going to use the app to interact with the pause.
