### ISSUE TITLE
Dietary Restrictions filter doesn't disable correctly

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#521]
@drewvolz:
> [Applying] and removing dietary restriction filters will cause an incorrect count of filters, and then mucks up the list of food items displayed. I feel as if there is a bug where the cor icon diets are not unapplying themselves once deselected. It feels reversed after a few toggles?
>
> […]
>
> The number of filters only resets back to zero at one point if the cor icon filters are all checked, when the original state for that is having them all disabled.

Yep. This is a bug.

Each filter has an `enabled` property, which sets whether the filter is enabled or not. I have a bug in the `enabled` setting code for list filters, because I originally didn't distinguish between the AND and OR styles.

In [views/components/filter/section-list.js#L33](https://github.com/StoDevX/AAO-React-Native/blob/2c9a67ae159772ee39f5c319b06bbc1bfd5580ec/views/components/filter/section-list.js#L33)

```js
// `result` is the list of selected options, and `options` is the list of all options
onChange({
  ...filter,
  enabled: result.length !== options.length,
  spec: {...spec, selected: result},
})
```

That `enabled` setting is correct for the OR mode, where a filter is disabled only when all of the options are selected (aka "this filter should show any of these options".)

However, it's incorrect for the AND mode, where a filter should be disabled whenever none of the options are selected (aka "this filter should only show items with all of these selected options".)

I think a good change would be to pull out the `enabled` value into a variable, then do an `if` to check on the `mode` of the filter, and switch between the two algorithms depending.

Something like:

```js
// `result` is the list of selected options, and `options` is the list of all options
let enabled = false
if (mode === 'AND') {
  enabled = result.length !== options.length
} else if (mode === 'OR') {
  enabled = result.length !== 0
}

onChange({
  ...filter,
  enabled: enabled,
  spec: {...spec, selected: result},
})
```

I can do this at some point, or someone else can take it, either way is fine with me.

**Comment by drewvolz** [comment]
Thank you for the detailed explanation :+1:

**Comment by hawkrives** [comment]
Nope. Still happens, although now when you disable the dietary restrictions it filters out any items with no tags on them…

**Comment by drewvolz** [comment]
Great...

**Comment by hawkrives** [comment]
I found the bug: I had the logic paths reversed. The should-enable-AND logic was being applied to OR filters and vice-versa.

**Comment by drewvolz** [comment]
You found it! Thank you!
