### ISSUE TITLE
Scrutinize App Transport Security exceptions

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#523]
We've got 12 exceptions, and I don't think that we need some of them anymore.

- [unused] `bamco.com`
	- I can't find any uses of this URL in the codebase.
- [unused] `hub.cafebonappetit.com`
	- I can't find any uses of this URL in the codebase.
- [required] `legacy.cafebonappetit.com`
	- Used for the menus
- [required] `localhost`
	- Needed for dev-time react-native reloading
- [required] `manitoumessenger.com`
	- Needed for the MESS's RSS feed
- [required] `oleville.com`
	- Needed because oleville isn't HTTPS (RSS feed)
- [required] `stolaf-flash.streamguys.net`
	- Needed for the streams
- [unused] `stolaf.cafebonappetit.com`
	- Used to be used to load the café menus?
	- I can't find any uses of this URL in the codebase.
- [unused] `template.cafebonappetit.com`
	- I can't find any uses of this URL in the codebase.
- [unused] `van-go.info`
	- Used to … open the link in a browser?
- [required] `wp.stolaf.edu`
	- RSS feed (https) links to images over http
- [unused] `youarriveontime.com`
	- Used to … open the link in a browser?

I think we can eliminate `bamco.com`, `hub.cafebonappetit.com`, `stolaf.cafebonappetit.com`, `template.cafebonappetit.com`, `van-go.info`, and `youarriveontime.com` from our exceptions list.

#### Keep
- `legacy.cafebonappetit.com` – Used for the menus
- `localhost` – Needed for dev-time react-native reloading
- `manitoumessenger.com` – Needed for the MESS's RSS feed
- `oleville.com` – Needed because oleville isn't HTTPS (RSS feed)
- `stolaf-flash.streamguys.net` – Needed for the streams
- `wp.stolaf.edu` – RSS feed (https) links to images over http

#### Remove
- `bamco.com`
- `hub.cafebonappetit.com`
- `stolaf.cafebonappetit.com`
- `template.cafebonappetit.com`

#### Maybe remove?
- `van-go.info`
- `youarriveontime.com`

**Comment by drewvolz** [comment]
Refresh my memory. Do exceptions _only_ apply to webviews?

**Comment by drewvolz** [comment]
Ah. I can answer my own question. No, we'd need them outside of webviews.

**Comment by drewvolz** [comment]
We can probably remove some of the bon appetit ones that we were relying on for `cor icon` diet indicators. I'm not so sure we want to remove the transportation ones (van-go, youarriveontime). Your suspicion of "opening the link in a browser" sounds right. _Which we should probably think about adding._

**Comment by hawkrives** [comment]
We're currently calling `Linking.openURL` with the URL, so I think we're opening them in a browser? I can't imagine that passing a non-https URL out of your app would require ATS.

**Comment by hawkrives** [comment]
> Do exceptions only apply to webviews?

Yeah. My understanding is that they're applied at the OS' network layer (or, well, the Foundation layer.) So any code that requests data from the network is subject to these restrictions: webviews, fetch, native requests…

**Comment by drewvolz** [comment]
I think it might be a good idea to add a generic webview component to handle urls within the app.

**Comment by hawkrives** [comment]
See https://github.com/StoDevX/AAO-React-Native/issues/401; I'd rather use SFWebView / Chrome Custom Tabs than write our own little mini-browser.

We should also catch URLs from News and display them in said embedded browsers.

**Comment by drewvolz** [comment]
Would the URLs passed to "our own little mini-browser" be subject to App Transport Security exceptions?

**Comment by hawkrives** [comment]
Yes

**Comment by drewvolz** [comment]
Maybe that is an argument towards enabling all URLs within the app -- so that we can display all URLs that come from outside content in these browsers.

**Comment by hawkrives** [comment]
Hence why I want to use SFWebView – it's not subject to ATS, because it embeds Safari in your app.

**Edit**: SFWebView !== "custom mini-browser". RN's WebView would be a "custom mini-browser".

**Comment by hawkrives** [comment]
Disabling ATS will only be possible for a few more months, most likely, unless you're making a web browser yourself.

**Comment by drewvolz** [comment]
I think what I asked got lost in translation. If `SFWebView` bypasses the exception list, that would be good enough for me.

**Comment by drewvolz** [comment]
Did #535 take care of this?

**Comment by hawkrives** [comment]
#535 got rid of half of this ticket.

The other half is van-go and youarriveontime.com, which will be resolved with the SFViewController/ChromeTabs work. So, yeah. We'll remove the rest later.
