### ISSUE TITLE
Integrate network logger into dev tools somewhere

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#5230]
https://github.com/alexbrazier/react-native-network-logger

**Comment by drewvolz** [comment]
Pretty much have this working on `drew/network-logger`  (https://github.com/StoDevX/AAO-React-Native/compare/master...drew/network-logger)

<img src="https://user-images.githubusercontent.com/5240843/213944958-219624ad-3547-49cc-abd2-5fa4d4433009.jpeg" width=250 />

I got as far as adding the dependency for RN networking logging that
- (a) only starts working once you visit the debug view and
- (b) seems to ignore your list of filtered of domains?

However! There could be alternatives like [`react-native-netwatch`](https://github.com/odemolliens/react-native-netwatch). 

It offers to intercept requests at the cross-platform native level, the RN level, and the redux level. I’m wary of its support but I do like all the middleware options it provides.
