### ISSUE TITLE
Add button for "reset all data" in Settings

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#534]
We don't know what bugs may crop up, and it's better to have a fallback than not. 

All this button would need to do is to clear AsyncStorage. Should be simple enough. I think there's an AsyncStorage.clearAll method, even. 

I suppose we should probably show a confirmation dialog,  too.

**Comment by drewvolz** [comment]
Sounds reasonable. Good thought.

**Comment by drewvolz** [comment]
We will need to

**Comment by drewvolz** [comment]
We will need to clear stored items from the Keychain, too.

**Comment by hawkrives** [comment]
Ah yes. Good point.

**Comment by drewvolz** [comment]
And the CookieManager.

**Comment by hawkrives** [comment]
Haven't we removed that yet?

**Comment by hawkrives** [comment]
No we have not. However, I think we can remove it when I move the login auth state into redux.

**Comment by hawkrives** [comment]
I have a local branch with this.

**Comment by hawkrives** [comment]
Gah. I forgot to clear the keychain.

**Comment by hawkrives** [comment]
Done in v2.2

**Comment by hawkrives** [comment]
Closed by #1053
