### ISSUE TITLE
Upgrading react-native-paper?

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#5394]
There's a nicety I'd like to use in the later versions of `react-native-paper`'s [<List.Item />](https://callstack.github.io/react-native-paper/list-item.html#descriptionNumberOfLines) that [v2 lacks](https://callstack.github.io/react-native-paper/2.0/list-item.html).

I'd like to be able to set `descriptionNumberOfLines`. The equivalent for iOS allows for us to override a max number of lines, but paper's `<List.Item />` lacks this property [in the 2.* versions.](https://github.com/callstack/react-native-paper/commit/3782cf5c7805e6c86d1dcd9c4e863e6ad6ffc7c9)

I am wondering if upgrading to the latest version of paper leads us down the path of satisfying the dependencies for:
- upgrading react-native-tableview-simple,
- react-nvigation-material-bottom-tabs, and
- react-navigation-screens/react-navigation-stack

...and perhaps more after that?

```sh
> yarn add react-native-paper@4.9.2
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-tableview-simple@3.2.0" has incorrect peer dependency "react-native@^0.59".
warning " > react-navigation-material-bottom-tabs@1.1.1" has incorrect peer dependency "react-native-paper@^2.2.2".
warning "react-navigation-material-bottom-tabs > react-navigation-tabs@1.2.0" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > react-navigation-stack@1.10.3" has incorrect peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "@types/react-navigation-material-bottom-tabs > react-navigation-material-bottom-tabs@2.3.4" has incorrect peer dependency "react-native-paper@^2.2.2 || ^3.0.0".
[...]
```

**Comment by hawkrives** [comment]
@drewvolz Is this complete? Should we repurpose it?

**Comment by drewvolz** [comment]
This looks to be done. Closing!
