### ISSUE TITLE
Add descriptions to remaining dietary tags

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#543]
**In Balance** 
Contains a balanced portion of whole grains, fresh fruits and vegetables, and lean protein with a minimum amount of healthy fat

**Kosher**
Contains only ingredients prepared in accordance with Jewish Dietary Law

**Comment by hawkrives** [comment]
they go in https://github.com/StoDevX/AAO-React-Native/blob/master/images/dietary-filters.js

**Comment by hawkrives** [comment]
Anyone is welcome to do this.

**Comment by elijahverdoorn** [comment]
Interested in a small change? @ekmanzu? @zimmer18?

**Comment by elijahverdoorn** [comment]
I just did this one in #597.
