### ISSUE TITLE
News views are blank

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#549]
I think the Google API we use for news is either down, or rate limiting. Either way, the news lists are blank at the moment.

**Comment by drewvolz** [comment]
```
{
   "responseData": null,
   "responseDetails": "This API is no longer available.",
   "responseStatus": 403
}
```
I think we have to find a different solution. Betting Google killed off their public API.

**Comment by hawkrives** [comment]
"This API is officially deprecated and will stop working after December 15th, 2016. See our deprecation policy in our Terms of Service for details."

**Comment by hawkrives** [comment]
From https://developers.google.com/feed/

**Comment by hawkrives** [comment]
We already have a dependency on `xml2js`, which I've used before to parse xml. It's currently included to parse Stalkernet responses, but it'll work to parse RSS feeds just as well. 

Also, Wordpress provides a JSON endpoint that we can make use of, for Oleville, Olaf, and PoliticOle, but we'll need to parse the feed for the Mess.

**Comment by hawkrives** [comment]
I had a prototype somewhere that used said Wordpress JSON API for our Wordpress sources. I'll see if I can find it later.

**Comment by elijahverdoorn** [comment]
@hawkrives The Oleville view relies on the wp-json API, I had to configure it myself. If you're looking for an example, that would be a good place to start.

**Comment by hawkrives** [comment]
I made us a local RSS parser. I still intend to switch the Wordpress sites over to WP-JSON at some point, but that'll be after this release, and I'll certainly reference the Oleville view for that.

I figure I'd still need the RSS parser for the Mess' view, since they're not on Wordpress, so I might as well make "minimal" changes while fixing News.
