### ISSUE TITLE
Missing iOS icons for iPad Pro

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#5515]
ITMS-90892: Missing recommended icon - The bundle does not contain an alternate app icon for iPad of exactly '167x167' pixels, in .png format for iOS versions supporting iPad Pro. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleicons

ITMS-90892: Missing recommended icon - The bundle does not contain an alternate app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 10.0. To support older operating systems, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleicons

**Comment by hawkrives** [comment]
iTunes connect was not satisfied - same messages

**Comment by drewvolz** [comment]
Okay. I will revert the first attempt and read through the article linked.
