### ISSUE TITLE
Resetting the app only works after restarting the app

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#5528]
The setting to reset the app's local copy of state isn't applying until force-quitting the app and launching again. Previously the call to reload the bundle would apply immediately afterwards while in the app.

**Comment by hawkrives** [comment]
blocked on #5067 or equivalent, I think

**Comment by drewvolz** [comment]
rn-restart has been superseded a few times -- I think this is at #5720 now.

**Comment by hawkrives** [comment]
This appears to have been fixed, at least for me.

**Comment by drewvolz** [comment]
Looks fixed. Closing!
