### ISSUE TITLE
Utilize UIMenu popups on iOS in some spots

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#5573]
See https://github.com/dominicstop/react-native-ios-context-menu

**Comment by hawkrives** [comment]
We may need to maintain our own fork, as this one seems to have stalled ~10 months ago.

**Comment by drewvolz** [comment]
Until we're ready to tackle this, would it make sense to move this to discussions and out of issues?

**Comment by hawkrives** [comment]
Sure, that sounds good! (GH mobile doesn't have that button yet. Do you mind switching it?)
