### ISSUE TITLE
NoticeView extends beneath a tab bar

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#578]
It's not quite centered:

<img width=480 src=https://cloud.githubusercontent.com/assets/464441/21956229/cdedb7f6-da41-11e6-9c6d-b902ba9bd941.png>

I'm not entirely sure how to fix it. We might just let it lie…

**Comment by drewvolz** [comment]
So... does the challenge arise from knowing on iOS when there is and when there is not a tabbar at the bottom of the view?

**Comment by hawkrives** [comment]
In this case? It depends on if automaticallyAdjustContentInsets is implemented on View, or on ScrollView. 

Although, now that I think about it, we might want to wrap NoticeView in a ScrollView - I like to play with rubber band effects on iOS while I wait.
