### ISSUE TITLE
Fix metro resolving custom module exports

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#5943]
```
Metro has encountered an error: While trying to resolve module `@frogpond/titlecase` from file `aao-react-native/source/views/settings/screens/debug/list.tsx`, 
the package `@frogpond/titlecase/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`node_modules/@frogpond/titlecase/index`.

Indeed, none of these files exist:
  * aao-react-native/node_modules/@frogpond/titlecase/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.mjs|.native.mjs|.mjs)
  * aao-react-native/node_modules/@frogpond/titlecase/index/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.mjs|.native.mjs|.mjs): aao-react-native/node_modules/metro/src/node-haste/DependencyGraph.js (243:17)

  241 |
  242 |         if (error instanceof InvalidPackageError) {
> 243 |           throw new PackageResolutionError({
      |                 ^
  244 |             packageError: error,
  245 |             originModulePath: from,
  246 |             targetModuleName: to,
```

---

Option 1: 

A quick solution that _only_ fixes this one issue but not the larger problem would be to change `@frogpond/titlecase`:

1. Rename `to-title-case.mjs` -> `index.mjs`
1. Change the entrypoint's location in `package.json`:

```diff
{
-     "module": "to-title-case.mjs",
+     "module": "index.mjs",
}
```
   
Option 2: 

Bigger changes to`metro.config.js` that change `resolverMainFields`, `sourceExts`,  `blockList`, `extraNodeModules`, `watchFolders` ...

**Comment by hawkrives** [comment]
I vote ① - we should expect our dependencies being correct, especially ones we control.

**Comment by hawkrives** [comment]
Excuse me, Metro - do you not respect the "module" key?

<img src="https://user-images.githubusercontent.com/464441/164125835-e38e6de0-67f1-43ce-a7f3-621ceb57bf67.png" width=340 alt="excuse me, metro" />

**Comment by drewvolz** [comment]
That's what option 2 is –– we would have to write a bunch of resolver configuration to fix this.

**Comment by hawkrives** [comment]
If titlecase switched to a common js module, would that fix this? If it used the "main" key instead of "module"? 

Probably. 

I'll switch it to TS tomorrow and make it be CJS instead of ESM.

**Comment by hawkrives** [comment]
or "in addition to"

**Comment by hawkrives** [comment]
Unless, of course, just renaming the entrypoint to "index.mjs" works.

**Comment by hawkrives** [comment]
Closed by https://github.com/StoDevX/AAO-React-Native/pull/5951
