### ISSUE TITLE
Investigate autolinking for packages that should be auto linked

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#5949]
Our metro config is pretty vanilla, and that is a good thing. But we have hit a corner case where we thought we were auto linked yet we had to manually link to see the results. 

I believe this is because of how we are resolving our dependencies at the moment. 

We should be able to adopt a metro config that has some of these elements (not necessarily these exactly) to achieve this. In particular, the `extraNodeModules` key within the resolver should be something we look at.

This way we can go back to unlinking the relinked dependencies.

<details>
<summary>Example config</summary>

```js
"workspaces": {
  "packages" : [...],
  "noHoist": ["**"] //keep node_modules in the children folders

const path = require("path");

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },

  /**
  * Ensure any imports inside the shared folder resolve to the local
  * node_modules folder
  */
  resolver: {
    extraNodeModules: new Proxy({}, {
      get: (target, name) => path.join(process.cwd(), `node_modules/${name}`),
    }),
  },

   /**
   * Add our workspace roots so that react native can find the source code for
   * the included packages in the monorepo
   */
  projectRoot: path.resolve(__dirname),
  watchFolders: [
    path.resolve(__dirname, "../common"),
    path.resolve(__dirname, "../../node_modules")
  ]
};
```

</details>

**Comment by drewvolz** [comment]
I think the one thing failing to autolink is the datetime picker

**Comment by hawkrives** [comment]
Oh I fixed the datepicker 

It was nesting inside of a frogpond module on disk, so cocoa pods couldn't find it. I added it as a top level dep so that it would be hoisted.

**Comment by drewvolz** [comment]
Perfect, thanks!

**Comment by hawkrives** [comment]
Do you still think we have something to do to metro?

**Comment by drewvolz** [comment]
Nah. My original thinking has changed. Let's keep this simple.
