### ISSUE TITLE
Fix detox smoke test

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#5972]
The testID cannot be found because the testID for the settings back button is no longer defined.

---

Learnings from looking into fixing the detox smoke test: if we add a custom left back button component (imported from native navigation) we can pass in props for testID and the smoke test then passes. 

What seems to be happening is that passing a testID to the vanilla NavigationOptions for a <Stack.Screen /> seems to only be available if we use createStackNavigator and not create**Native**StackNavigator.

We should stick with the native stack navigator since that uses UINavigationController (iOS) and Fragments (android) so the performance is worth staying for even though it lacks some of the customization that the javascript navigator provides.

What is worth looking into are the style options for the custom back button. Although it passed the smoke test, it rendered in a different size and location compared to our built-in navigation buttons.

**Comment by drewvolz** [comment]
Alternatively we could target the back button (temporarily?) by looking for the text "Back" and tapping on the first that appears. This also fixed the test.

**Comment by hawkrives** [comment]
(I think I like the second option)
