### ISSUE TITLE
Make CI step to verify that "pod install" works

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#5974]
Then, make the build iOS step depend on it.

**Comment by rye** [comment]
Isn't that `pod install --deployment`?

**Comment by hawkrives** [comment]
Yep. But we're currently not running that (except on nightlies), so there's actually another pod.lock error on main right now 😅

I'd like to have a macOS build step that just installs npm and cocoapods, to make sure that the lockfile works. At least temporarily, until the builds are passing again.
