### ISSUE TITLE
Use react-navigation searchbars

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6024]
- [x] #6025
- [x] #6026
- [x] #6087 
- [x] #3558 
- [x] #6110

**Comment by drewvolz** [comment]
We may have to refactor course search's recent search page (the index/entry into course search) for a few reasons.

First, we do not have a list that the searchbar can attach and insert itself into through the navigation hooks. The current list displays list items without being wrapped by a traditional list.

Second, the searchbar automatically hides itself. There is a prop for android to focus it on load but not on iOS. This could feel strange on a very search oriented view. This leads me to ask if (a) are we OK with that? and (b) would we prefer to remove the recent search view if not? or (c) ...keep the old searchbar and all of its deps?

**Comment by hawkrives** [comment]
I vote we make it work like the bottom of Photos' search page

Bar in the toolbar, then just the list of recent search terms. 

We can do other fancy stuff in the future

**Comment by drewvolz** [comment]
Okay so that means to me that we
- [x] ~Add a SectionList (or two FlatList) to the course-search's recent item list component (it's not currently wrapped)~
  - Update: Issue was with tab navigator. Explanation below in "Challenge 1" as to why we don't need a List to search.
- [x] Add searchbar hook

I can try to see what initialization looks like. I think with no recent searches it may show us the searchbar and with data it may hide the searchbar. I will see what happens.

**Comment by drewvolz** [comment]
Making this work for nested tab navigators was a bit confusing at first but the documentation has been helpful in figuring some of this out.

## Challenge 1
SIS top-level recent searches tab has this setup.

✅ When we are one-level deep in a tab navigator, attaching a search bar to the view will work fine. 
See: Recent course search --> Search results

⚠️  When we are top-level inside a tab navigator, attaching a search bar to the view will not work.
See: Tab.Navigator > Tab.Screen --> Course search

### Solution for challenge 1

That second part was causing the search bar to not appear until I came across react navigation's documentation for `navigation.getParent` as a workaround.

> ### getParent
> This method returns the navigation prop from the parent navigator that the current navigator is nested in. If you have a stack navigator and a tab navigator nested inside the stack, then you can use [`getParent`](https://reactnavigation.org/docs/navigation-prop#getparent) inside a screen of the tab navigator to get the navigation prop passed from the stack navigator.

```tsx
navigation.getParent()?.setOptions({
    headerSearchBarOptions: {
      ...
    }
})
```

So challenge 1 feels solved. Noting there may be a quirk where the searchbar fails to mount but I can't judge the stability of it while so much is in flux.

Result:

<img src="https://user-images.githubusercontent.com/5240843/170848481-06ac2883-9280-4c18-aacf-cda8f33b8cc5.png" width=320 />

---

## Challenge 2

The searchbar provides us an immediate value on text change. We have ways of working around delaying search like `useDebounce` for orgs, dictionary, directory, course search results. This works well on lists that we are filtering and not navigating in.

The native searchbar API doesn't provide any sort of done/finished callback. The only react native components I am aware of that do are TextInput (onSubmitEditing) which is what we were using previously.

What is challenging about the course search recent search screen is that I am unable to think of a way to delay immediately searching for a query as soon as the user finishes typing. Do we have a way we can make that functionality happen?

I would like us to be able to fire off several key presses, debounce, and finally navigate to the search results screen without every key press taking us there. Setting a timeout and navigating would be kind of a hack, though. We want to not break user expectations or make assumptions on how long searches take.

Alternatively, the recent search screen could be a different view revealed by a navigation button. That screen wouldn't have a searchbar in it and would be responsible for routing recent queries instead.

I'm most likely not thinking of all the options to solve challenge 2. Thoughts?

**Comment by drewvolz** [comment]
I do have a solution idea for challenge 2. It uses lodash's `debounce` and not our own `useDebounce` hook. I'm seeing `useDebounce` be called on every new character that's typed.

```tsx
let _debounce = debounce((query: string, callback: () => void) => {
	if (query.length >= 2) {
		callback()
	}
}, 1500)

let CourseSearchView = (props: Props): JSX.Element => {
	let navigation = useNavigation()
	let [typedQuery, setTypedQuery] = useState('')

	let showSearchResult = useCallback((query: string) => {
		navigation.navigate('CourseSearchResults', {initialQuery: query})
	}, [navigation])

	useEffect(() => {
		_debounce(typedQuery, () => {
			showSearchResult(typedQuery)
		})
	}, [showSearchResult, typedQuery])

	useLayoutEffect(() => {
		navigation.getParent()?.setOptions({
			headerSearchBarOptions: {
				onChangeText: (event: ChangeTextEvent) => {
					setTypedQuery(event.nativeEvent.text)
				}				
			},
		})
	}, [navigation, typedQuery])
	
	...
}
```
