### ISSUE TITLE
Investigate searchbar jitteriness on PTR

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6035]
Continuing #6024, we could improve the UX of the new native searchbar.

Ideas:
- Look to see if safearea is causing the flicker like we saw with the tableview
- Is this just PTR?
- Are we refreshing our loading/refreshing variables too quickly?
- Is this caused by the warning that we see on load?

```
WARN: Failed to attach search bar to the header. We recommend using `useLayoutEffect` when managing
searchBar properties dynamically.

See: github.com/software-mansion/react-native-screens/issues/1188
```

**Comment by hawkrives** [comment]
I'm game to remove SafeAreaView - I'm thinking that it'd be nice to put a small toolbar at the bottom, like Mail.app has, on any view without a tab bar. I think it would show the last-updates time and maybe an (i) icon to tell you where we get the data from (IE it would replace the current ListFooterComponent).
