### ISSUE TITLE
Listen to KSTO button error

### ISSUE THREAD

**Issue by zimmer18** [StoDevX/AAO-React-Native#609]
I just pressed the listen to KSTO button and this error appeared.

1 | 2
--|--
<img src="https://cloud.githubusercontent.com/assets/14142305/22172553/b311333a-df6f-11e6-9ed0-22b17234be5c.png" width=350 /> | <img src="https://cloud.githubusercontent.com/assets/14142305/22172552/b311040a-df6f-11e6-9ce0-be4ad8c7ad5d.png" width=350 />

**Comment by drewvolz** [comment]
I think that is a simulator error only? Someone please correct me if I am wrong.

**Comment by hawkrives** [comment]
It's a simulator error. When I tapped it on my phone, I was taken to the store.

**Comment by drewvolz** [comment]
I suppose we could add a check to do nothing via the dev/production var.

**Comment by hawkrives** [comment]
We're actually throwing that error

https://github.com/StoDevX/AAO-React-Native/blob/master/views/streaming/radio.js

If we just switch it to a console.warn, we'll be fine in Dev too.

**Comment by drewvolz** [comment]
👍
