### ISSUE TITLE
Pull to refresh feels broken on the bonapp menu

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6093]
Definitely something I introduced in
- #6070 

Maybe this is worth looking at

https://github.com/StoDevX/AAO-React-Native/blob/9b2c284303e6a729636dc671dfdf37bd8d225a0a/source/views/menus/menu-bonapp.tsx#L233-L234

**Comment by hawkrives** [comment]
@drewvolz Do you think this has been fixed by #6718 ?

**Comment by drewvolz** [comment]
I think the state doesn't quite match with what I imagine when I compare it to Mail.app but we can close this and focus on larger issues.

**Comment by hawkrives** [comment]
Ours is very fast. I'm OK with keeping this open.

**Comment by drewvolz** [comment]
I'm okay with closing this if we have no plans to add a delay 🤷‍♂️

**Comment by hawkrives** [comment]
Let's close this and we can reopen if it still feels broken in a week
