### ISSUE TITLE
Daily Meals Left Incorrect

### ISSUE THREAD

**Issue by zimmer18** [StoDevX/AAO-React-Native#611]
I should have three meals left for the day because I've eaten none for the day. I think you might have your clock wrong because when this screenshot was taken I had eaten two meals for the previous day and it's currently early in the morning of the next.

![screen shot 2017-01-21 at 1 19 45 am](https://cloud.githubusercontent.com/assets/14142305/22172865/b6c1a34a-df77-11e6-8d61-3c6e6fe08092.png)

**Comment by hawkrives** [comment]
Could you please check at https://www.stolaf.edu//apps/olecard/checkbalance/index.cfm ?

That's where we get that data from, and I can't see how we'd manage to parse an incorrect number. 

Other question: is this on master, my refactoring, or both?

**Comment by zimmer18** [comment]
I just checked the website and it's correct. It was incorrect really early this morning around 1am so maybe the site updates later in the morning.

**Comment by drewvolz** [comment]
Ah. That would make sense. We have a few "between" times that data doesn't quite make sense. Good catch!

**Comment by drewvolz** [comment]
I think we are able to close this. It is data we cannot control.
