### ISSUE TITLE
Missing Building Hours

### ISSUE THREAD

**Issue by zimmer18** [StoDevX/AAO-React-Native#612]
These three need to be added to building hours view:

- ~~Gender & Sexuality Center~~
- ~~Telecom~~
- ~~Bon App office~~

**Comment by hawkrives** [comment]
@zimmer18 / @elijahverdoorn / @erichkauffman  When it says "Telecom", is that the Switchboard?

**Comment by hawkrives** [comment]
Also, for BonApp, do we want the Catering Office, the management office, or both?

**Comment by hawkrives** [comment]
The GSC has no posted hours on their office, nor their website.

**Comment by hawkrives** [comment]
@elijahverdoorn I don't think we need the BonApp office. (Also they don't post any hours anywhere.)

The telecom switchboard is no more.

That leaves us with the GSC, who should be adding hours to their website soon.

**Comment by hawkrives** [comment]
GSO has posted office hours: https://wp.stolaf.edu/gso/staff/
