### ISSUE TITLE
Color fixup for iOS

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#6171]
| Settings | AAO | 50/50 |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/464441/165426111-9b50f609-f909-439f-99df-70e9494fcca1.png) | ![image](https://user-images.githubusercontent.com/464441/165426126-233efb9c-95a2-4895-b000-82c56305ad5d.png) | ![image](https://user-images.githubusercontent.com/464441/165426137-b57255a1-0808-47cc-842f-06d6a3b7c2ed.png) |

- [ ] Background color
- [ ] Selected row color

And maybe hide ListSeparator when the row is tapped? I think we can do that?

**Comment by hawkrives** [comment]
This may be a duplicate issue…

**Comment by drewvolz** [comment]
Related / duplicates of:
- #3168 
- #6008

**Comment by hawkrives** [comment]
Duplicates #6008

**Comment by hawkrives** [comment]
(My GitHub mobile loaded the OP into the editor when I opened it, so I posted it rather than risk losing it. Thanks for finding the dup, @drewvolz!)
