### ISSUE TITLE
Android course catalog does not download data

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6288]
The course catalog does not appear to download courses on android. iOS works fine.

**Comment by drewvolz** [comment]
I have an answer as to what is going on. Requests to `stolaf.github.io` redirect to `stolaf.dev`.

We are returned a `301 Moved Permanently` response. 

iOS is able to follow it, Android is not following the redirect.

**Comment by drewvolz** [comment]
So maybe it is not a redirect issue?

> Normally, fetch transparently follows HTTP-redirects, like 301, 302 etc.
> https://javascript.info/fetch-api#redirect

I am able to fix this locally by changing `urls.ts`

```diff
- export const COURSE_DATA_PAGE = 'https://stodevx.github.io/course-data/'
+ export const COURSE_DATA_PAGE = 'https://stolaf.dev/course-data/'

- export const INFO_PAGE = 'https://stodevx.github.io/course-data/info.json'
+ export const INFO_PAGE = 'https://stolaf.dev/course-data/info.json'

- export const GE_DATA = 'https://stodevx.github.io/course-data/data-lists/valid_gereqs.json'
+ export const GE_DATA = 'https://stolaf.dev/course-data/data-lists/valid_gereqs.json'

- export const DEPT_DATA = 'https://stodevx.github.io/course-data/data-lists/valid_departments.json'
+ export const DEPT_DATA = 'https://stolaf.dev/course-data/data-lists/valid_departments.json'

- export const TIMES_DATA = 'https://stodevx.github.io/course-data/data-lists/valid_times.json'
+ export const TIMES_DATA = 'https://stolaf.dev/course-data/data-lists/valid_times.json'
```

**Comment by hawkrives** [comment]
Is it an RN 0.68 issue? Since they ship the fetch-to-native shim…

**Comment by drewvolz** [comment]
Here are [the networking issues for 0.68]( https://reactnative.dev/docs/0.68/network#known-issues-with-fetch-and-cookie-based-authentication)

> ### Known Issues with `fetch` and cookie based authentication
> 
> The following options are currently not working with `fetch`
> 
> - `redirect:manual`
> - `credentials:omit`
> 
> * Having same name headers on Android will result in only the latest one being present. A temporary solution can be found here: https://github.com/facebook/react-native/issues/18837#issuecomment-398779994.
> * Cookie based authentication is currently unstable. You can view some of the issues raised here: https://github.com/facebook/react-native/issues/23185
> * As a minimum on iOS, when redirected through a `302`, if a `Set-Cookie` header is present, the cookie is not set properly. Since the redirect cannot be handled manually this might cause a scenario where infinite requests occur if the redirect is the result of an expired session.
