### ISSUE TITLE
2.1.1 hotfix release

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#635]
- ~~#633~~
- ~~#634~~
- ~~#639~~
- ~~#642~~

**Comment by hawkrives** [comment]
branch: [`v2.1.1`](https://github.com/StoDevX/AAO-React-Native/tree/v2.1.1)

**Comment by hawkrives** [comment]
@elijahverdoorn I've cherry-picked today's commits onto v2.1.1, as well as the versioning commit.

**Comment by elijahverdoorn** [comment]
@hawkrives Great. I'll try to build it this afternoon. We should pull the iOS release back and add this code in there too, it's going to be a problem there too and I don't want to have to wait on that review again.

**Comment by hawkrives** [comment]
Yup, agreed.

**Comment by elijahverdoorn** [comment]
Uploaded to both platforms.

**Comment by hawkrives** [comment]
Close now or close when both are released?

**Comment by elijahverdoorn** [comment]
@hawkrives I'll close it when released.

**Comment by hawkrives** [comment]
Both are now released.
