### ISSUE TITLE
rename the repository

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#648]
@hawkrives proposal

> I'd like to propose that we rename the repo to 'all-about-olaf'

We would rename the old repo as well... maybe "legacy-all-about-olaf" or "old-all-about-olaf"

Thoughts?

**Comment by hawkrives** [comment]
I'm for it. I like "old-all-about-olaf" for the old one.

**Comment by elijahverdoorn** [comment]
Sounds good. @drewvolz rename the old and I'll do this one once that is done?

**Comment by drewvolz** [comment]
Renamed the old. We're in the clear to rename this one.

**Comment by elijahverdoorn** [comment]
Done

**Comment by hawkrives** [comment]
```console
$ git remote rm origin
$ git remote add origin https://github.com/StoDevX/all-about-olaf.git
```

**Comment by drewvolz** [comment]
You beat me to that comment by half a second!

**Comment by drewvolz** [comment]
Alternatively, just do a one-liner...

`git remote set-url origin https://github.com/StoDevX/all-about-olaf.git`

**Comment by hawkrives** [comment]
sure, that works too 😝

**Comment by hawkrives** [comment]
This wound up breaking the gh-pages URLs, which the shipping app relies on, so we reverted the change.
