### ISSUE TITLE
app transport exceptions in oleville

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#652]
Hyperlinks need to be disabled within the Oleville section as they can lead to app transport exceptions for http domains that are not white listed within the app.

Is this the appropriate time to think about aggregating Oleville to the news portion of the app?

<img width="417" alt="Oleville ATS" src="https://cloud.githubusercontent.com/assets/5240843/22408777/c27c8f20-e64c-11e6-8fb2-c5c23215ebcf.PNG">

**Comment by hawkrives** [comment]
Sure. 

I'd also like to investigate either catching navigation events from the WebViews and opening them in a browser, or even using HTMLparser2 to avoid webviews entirely.

**Comment by drewvolz** [comment]
Absolutely, that is a great idea.
