### ISSUE TITLE
Ensure analytics are enabled by default

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#653]
> This bug is a result of https://github.com/StoDevX/AAO-React-Native/pull/649

there's a chunk in init that makes sure they're set to be enabled by default, but I have a feeling it is not working the way we want it. I want to double check that it is indeed toggled true from a fresh download or a version update.

**Comment by hawkrives** [comment]
This issue only applies to master. Analytics are permanently enabled on the current release.

**Comment by hawkrives** [comment]
* on current release.

**Comment by drewvolz** [comment]
Sorry -- meant to clarify that I am referencing the [analytics toggle](https://github.com/StoDevX/AAO-React-Native/pull/649) in beta settings.
