### ISSUE TITLE
[RFC] Cage menu is blank (again)

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#660]
> As is the Caf, but we have a solution for the Cage.

Over Christmas break, when we were building and finishing `fancy-menus`, the Cage listed all of their normal menu items for us. As soon as we shipped, though, they quit using them! @drewvolz emailed them, and they directed us to their PDF menus if we wanted to see the normal selection of food.

A bit of background: BonApp's menu api returns both a list of all food items used in the requested day range, which is usually only a single day, as well as a list of menus used for that café. The Cage only has one menu per day, but the Caf has three — Breakfast, Lunch, and Dinner.

The Cage's api response returns their entire set of default menu items, but the response's _menu_ only references the specials.

I propose that, for the Cage, we ignore the listed menus and regenerate them from the big list of all food items. This would be done via a prop in the tabs file, so that it only applied to cafés that need it.

Thoughts?

---

PS: The Caf's menu is blank today because they're on Interim Break hours, but instead of saying "closed for breakfast", they have "breakfast: open, lunch: special hours, dinner: special hours, breakfast: closed". 

The Cafés api returns the next week's schedule for the requested café; each `day` has a status (open | closed) and a message, as well as a list of `dayparts`, which have a `starttime`, `endtime`, `label`, and `message`. 

Today, the response looks something like this:

```json
"days": [
        {
          "status": "open",
          "message": "",
          "date": "2017-02-03",
          "dayparts": [
            {
              "starttime": "07:00",
              "id": "1",
              "label": "Breakfast",
              "endtime": "09:45",
              "message": ""
            },
            {
              "starttime": "12:00",
              "id": "3",
              "label": "Lunch",
              "endtime": "13:00",
              "message": "Interim Break hours"
            },
            {
              "starttime": "17:00",
              "id": "4",
              "label": "Dinner",
              "endtime": "18:00",
              "message": "Interim Break hours"
            },
            {
              "starttime": "07:00",
              "id": "8",
              "label": "Closed",
              "endtime": "09:45",
              "message": "Closed for breakfast Interim Break"
            }
          ]
        },
        {
          "status": "closed",
          "message": "Closed for Interim Break",
          "date": "2017-02-04",
          "dayparts": []
        },
]
```

You can see that there are _two_ entries with the same start/end time for today, one labelled "Breakfast" and one labelled "Closed" (‽). So, the Caf's problem is just bad data. Nothing we can do about it.

**Comment by drewvolz** [comment]
Constructing our own non-specials menu and indicating via a prop is most likely the best choice we have that comes to mind. I am happy with that option.

Dealing with bad hours data is unfortunate. We could try to reason with them directly? Point out dozens of institutions that do it correctly?

**Comment by elijahverdoorn** [comment]
I can pressure them more from this end too. I agree with the proposed solution to the cage issue, and would like to point out that it currently says `No items to show. Try changing the filters` even though I don't have any filters on.

**Comment by hawkrives** [comment]
Yes, this is not a situation I expected to happen, so the logic for "no items" is only used after the filters have beeen applied...
