### ISSUE TITLE
Inject the full title of the news article into the top of the article view

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#67]
Currently, we cut off the title of the news article.

It would be nice if the article displayed the title at the top of the article view.

**Comment by elijahverdoorn** [comment]
@hawkrives did this in #148

**Comment by elijahverdoorn** [comment]
I misunderstood, upon reading again I don't think that we're done with it.

**Comment by hawkrives** [comment]
Nope. Not done.
