### ISSUE TITLE
Menu filters on cors_icon (an object) allow through items with no cors_icons at all

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#6742]
In other words, meat dishes are showing up for `(V)`

**Comment by drewvolz** [comment]
Is this still an issue? I think I am seeing the filters work okay.

**Comment by hawkrives** [comment]
Yes, this still appears for me:

<details>
<summary>if I filter for (v)egetarian dishes, I get back things with meat in them and no cors icons at all</summary>

![image](https://user-images.githubusercontent.com/464441/213866625-9ec5fbe8-6850-43e5-8c13-546c2b272d23.png)

</details>
