### ISSUE TITLE
All calendar views say "no events," and then something about "undefined" if you do a pull-to-refresh

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#6744]
I should go through and take out the "error instanceof Error" checks…

**Comment by hawkrives** [comment]
@drewvolz @rye My calendar is working now - is yours?

![image](https://user-images.githubusercontent.com/464441/213841847-bae48917-6c6f-442b-95a7-156ac5a54660.png)

**Comment by drewvolz** [comment]
Yes! Working fine

**Comment by hawkrives** [comment]
Hmm. I wonder what was happening? I'll close this for now…
