### ISSUE TITLE
Student Work fails with a 504

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#6745]
A problem occured while loading: HTTPError: Request failed with status code 504

---

It didn't fail last night-is the endpoint working?

**Comment by drewvolz** [comment]
I'm getting a gateway timeout when we try the fuseaction/nostructure endpoint. Need to see if data lives in the wp-json endpoint instead?

**Comment by hawkrives** [comment]
But our beta from two days ago was working - with data. I remember because there are like 50 CURI jobs posted right now…

**Comment by hawkrives** [comment]
Is our API returning data if we curl? Isn't our API calling the wp-json route?

**Comment by drewvolz** [comment]
The API scrapes and parses the html from the coldfusion action iirc

**Comment by hawkrives** [comment]
It was changed to Wordpress in https://github.com/frog-pond/ccc-server/pull/638. I haven't looked at the running server yet.

**Comment by drewvolz** [comment]
Right, changed to Wordpress to parse the embedded html in the responses

**Comment by drewvolz** [comment]
This appears to now be working, we should be able to close out this issue.
