### ISSUE TITLE
Check I'm Here just rebranded to "Checkpoint by Presence"

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#677]
See http://www.presence.io/blog/check-im-here-is-now-presence for more details. 

We need to check the Student Orgs tab and update the URLs it requests. We should also submit an update to the app pretty quickly with the new URLs, because we don't know when the current ones will quit working.

**Comment by drewvolz** [comment]
Additionally, maybe now is the time to add CodePush and/or centralize where URLs are fetched from so that we don't have to scramble to update the binary when a source changes its endpoint.

**Comment by hawkrives** [comment]
I still say there's no point to having a list of URLs, as it's just (IMHO) more likely that the college will change providers for a service than that service moves its API endpoint.

**Comment by drewvolz** [comment]
This is a scenario where it benefits us with a smooth changeover. We've also suffered when trying to rename the repo but could not in one action. 

Google RSS to JSON converter bit the dust and we needed to simply change the URL. I understand that one was a code change as well but we can solve half the problem remotely without a new binary push. Not every source change involves an API change.

The mere fact we play catchup with URL changes, regardless of rebrands or not, means we are doing it poorly. We get burned by simple static data.

Our list of static URLs are these and maybe more:

Olaf SIS
Olaf apps/OleCard
Olaf directory
Presence.io
Google Calendar
BonApp
StoDevX
StreamGuys - webcams and potentially radio
RSS feeds - 4 news sources
map.stolaf.edu
Transportation links - 7 redirects

To me, it's not about quantity of sources. I see it as eliminating potential issues before they really bite us. I'm willing to put the work in to prevent this scenario. That 1/10 is worth a smooth transition to me.

**Comment by drewvolz** [comment]
CodePush would solve this.

**Comment by hawkrives** [comment]
I'm good with Codepush. I'm still :-1: on a central list of URLs that we fetch every so often.

I still vote that we ship a 2.1.2 with the presence.io URLs, then focus on implementing Codepush for 2.2.

**Comment by elijahverdoorn** [comment]
I was just notified of this change in a meeting last night, good catch.

I'm not totally against the idea of a list of URLs, that seems like a simple solution, but we've always intended to do CodePush so it might be time to just do that.

**Comment by hawkrives** [comment]
I'm going to close this, as we've updated the app for presence now.
