### ISSUE TITLE
Fix Android builds

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#6798]
## Device(s) with issues
- Google Pixel 6 (oriole) - Android 12
- Google Pixel 5 (redfin) - Android 11
- Samsung SM-G981U1 (x1q) - Android 10
- Google Pixel 2 (Pixel2Emulator) - Android 12
- Google Redfin 64-bit only (redfin_64) - Android 13
- Google Pixel 2 (Pixel2Emulator) - Android 9
- Google Pixel 2 (Pixel2Emulator) - Android 13

## Exceptions
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
- java.lang.IllegalStateException: Native module RNDatePickerAndroid tried to override RNDatePickerDialogModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.

**Comment by drewvolz** [comment]
Our first step could be trying to cherry-pick https://github.com/StoDevX/AAO-React-Native/pull/6719/commits/e7f48ab45ff11878d13edc6eaaf902975b6e1fdb out of the rn-71 feature branch. It removes the manual linkage of date picker.

**Comment by drewvolz** [comment]
Next step should be locking down our android dependencies. We can add gradle dependency locking to the android side to prevent headaches of upstream updates (in particular, androidx) from bumping beta versions and causing build breakages across builds.

- https://docs.gradle.org/current/userguide/dependency_locking.html
- https://plugins.gradle.org/plugin/nebula.dependency-lock
- https://developer.vonage.com/en/blog/the-right-way-of-using-gradle-dynamic-dependencies
- https://medium.com/codex/upgrading-dependencies-doesnt-have-to-suck-8d5b2b767d58

**Comment by drewvolz** [comment]
Option 1: Locking down android dependencies with a gradle lockfile
- #6806

If that does not pan out as a good enough approach for us, we have other tools to fall back upon. 

- https://github.com/facebook/react-native/issues/35979

Option 2: We could try something like this (make sure the versions are correct, I pulled this as an example)
```
dependencies {
     constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}
```

Option 3: There's also an opportunity to try out BOM (software bill of materials)

- https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import
- https://medium.com/@gabrielshanahan/a-deep-dive-into-an-initial-kotlin-build-gradle-kts-8950b81b214

```
implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
```

**Comment by hawkrives** [comment]
from https://github.com/StoDevX/AAO-React-Native/actions/runs/4026063585/jobs/6920228703

> **Task `:react-native-gradle-plugin:compileKotlin`**
>
> `compileJava` task (current target is 1.8) and `compileKotlin` task (current target is 11) jvm target compatibility should be set to the same Java version.

**Comment by hawkrives** [comment]
from https://github.com/StoDevX/AAO-React-Native/actions/runs/4026063585/jobs/6920228703


> **Configure project `:@react-native-community_datetimepicker`**
>
> Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: `org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated`.
