### ISSUE TITLE
Remove distributionSha256Sum from gradle-wrapper.properties?

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6805]
Introduced in b32563e, I'm seeing `distributionSha256Sum` isn't supported in `gradle-wrapper.properties`
> It is not fully supported to define distributionSha256Sum in gradle/wrapper/gradle-wrapper.properties.
> Using an incorrect value may freeze or crash Android Studio.
> Please manually verify or remove this property from all of included projects if applicable.
> For more details, see https://github.com/gradle/gradle/issues/9361.

Options available to resolve
> - Use "c9490e938..." as checksum for https://services.gradle.org/distributions/gradle-7.3.3-all.zip and sync project
> - Remove distributionSha256Sum and sync project

**Comment by hawkrives** [comment]
Huh. I put it in there because one of the gradle experiments I was doing for Android detox complained that it _wasn't_ there! Ah well. Let's take it out!

**Comment by drewvolz** [comment]
I'm uncertain. On Dolphin, I was getting this warning. After upgrading to Eel (2022.1.1) I do not see this warning any longer.

**Comment by hawkrives** [comment]
I'd like to keep this around and close this issue. We can reopen it if we encounter any problems with having it?
