### ISSUE TITLE
Change the privacy policy to meet the play store's guidelines

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6890]
- We're not meeting some guidelines
- We need to do this by Feb 13 or else Google will get more angry and subject "additional enforcement"?
<img width="681" alt="Screenshot 2023-01-30 at 5 21 14 PM" src="https://user-images.githubusercontent.com/5240843/215635179-a13d7c65-e2b2-47e2-8d15-1680fb30c308.png">
<img width="664" alt="Screenshot 2023-01-30 at 5 21 26 PM" src="https://user-images.githubusercontent.com/5240843/215635187-cd7cad3c-9476-4ab7-a0dc-de51f05f586a.png">

**Comment by hawkrives** [comment]
Apparently we haven't given them a published copy of the policy anywhere. Can we give them a GitHub pernambuco?

**Comment by drewvolz** [comment]
I've filled this out now and it's pending submission, but I do not know of a way to submit the data safety questionnaire separately from the 2.8.0-pre full rollout for alpha closed testing for review.

We can leave this open until we push the submit button under "publishing overview" in the play store console.
