### ISSUE TITLE
Change icons for the iOS tab bars

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#69]
Each tab needs a different icon. We need to pick them, and figure out how to use them.

Picking them first, I think.

We've been using the icons from entypo.com for the rest of the app, so ideally all the icons would come from there.

If we need special icons for some tabs – maybe logos for the news orgs – then we'll have to figure out how to do those.
## Tabs that need icons
- Menus
  - [ ] Stav
  - [ ] Cage
- Streaming Media
  - [ ] Ksto
  - [ ] Webcams
  - [ ] Weekly movie
- Calendar
  - [ ] Master calendar
  - [ ] Oleville
- News
  - [ ] St. Olaf
  - [ ] Mess
  - [ ] PoliticOle

**Comment by drewvolz** [comment]
This was fixed in #105
