### ISSUE TITLE
Cannot delete last character from username login field

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#696]
**Problem**
I'm playing with the St. Olaf login form in Settings. I can delete all but the first character of my username or password. Further investigation by @hawkrives reports that no redux action is fired when one tries to remove the last character.

We should investigate why no action is fired when the last character is removed. 

**Impact**
Login form in settings

**Comment by hawkrives** [comment]
Alternate issue title: "Cannot delete last character from username login field". 

Because we have no idea where the issue lies.

**Comment by drewvolz** [comment]
In `login-credentials.js` looking at the `LoginField`, I noticed if I remove the first text check I can delete the remaining characters

old:   `onChangeText={text => text && this.props.onChangeUsername(text)}`
new: `onChangeText={text => this.props.onChangeUsername(text)}`

... and the same for password.

**Comment by hawkrives** [comment]
I'm thinking we might want to investigate moving the test field state into the LoginField component, and out of redux. 

And only fire the save whatever action when the fields are submitted / logged out.

**Comment by hawkrives** [comment]
Wait. Did I actually have that check? Because yes, that would be the entire problem. 

It won't fire if the string isnt truthy.

**Comment by drewvolz** [comment]
Yep that check is there and looks to be the issue.
