### ISSUE TITLE
Android building hours shows a red screen with `borderColor`

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6990]
This looks self induced by the changes in #6989 (PlatformColor changes)

- ❌  If we try to use an android `PlatformColor`, we get a red screen in the `<OutllineBadge />` where `borderColor: c.separator` is used in the building hours row.
- ✅ If we use a hex string (which breaks types), the screen renders without error.

Prerequisites:
1. Overlay the changes from #6989 to prevent crashing
2. Tap building hours

```
Error while updating prop borderColor
java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.Integer
```

**Comment by rye** [comment]
Took a crack at this. With some debugging prints, I was able to track this down to the `skippingStop` style, defined in `ProgressChunk.tsx`. Today, Wednesday, this only crashed on the Red Line view. The Red Line schedule was also the only one that included a skipped stop today.

I'll have a patch shortly.

**Comment by drewvolz** [comment]
I'm kind of surprised that saying "closes #..." didn't close this issue in a task list for issue #6989. We can recheck, but is this still an issue?

**Comment by rye** [comment]
Yes, this was still crashing.

**Comment by drewvolz** [comment]
Nice, good catch! I missed this one on the transportation tabs, but I see it impacting the red line tab now.
