### ISSUE TITLE
Can we add Pause events to the Calendar?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#70]
It should be possible, no? I think they have their own Google Calendar feed with id `stolaf.edu_qkrej5rm8c8582dlnc28nreboc@group.calendar.google.com`. 

(pulled from http://oleville.com/pause/calendar/)

**Comment by elijahverdoorn** [comment]
Totally possible, but I need to talk to the other SGA execs and decide if I want to pull those into the SGA calendar or not. I'm guessing that we'll keep it separate, but let's hold off for now until I come back with a formal decision.

**Comment by hawkrives** [comment]
We could also just add a third tab. I know the Pause callendar is kinda … screwy. 

Taiko had a knack for hittting the bumps in their calendar.

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Pause-Events-on-Calendar).

**Comment by hawkrives** [comment]
Given that we're looking at adding some other calendar views (cough #482), I'd like to revisit the idea of the Pause calendar.

@drewvolz and I were also looking at adding a calendar with events provided by the CheckImHere API, which will ideally get more content as clubs start to use it more.
