### ISSUE TITLE
TES View

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#74]
Given that we are already storing user's usernames and passwords, can we make it easy for students to input their hours into TES?

**Comment by hawkrives** [comment]
Whoo boy.

See https://www.stolaf.edu/people/rives/cgi-bin/get-tes.py/, when it's working, and https://github.com/StoDevX/sto-tes-calculator

I've actually built this once, in Pythonista for iOS.

It's doable.

**Comment by hawkrives** [comment]
https://www.stolaf.edu/people/rives/cgi-bin/get-tes.py/, when it's working, and https://github.com/StoDevX/sto-tes-calculator

**Comment by hawkrives** [comment]
I've actually built this once, in Pythonista for iOS.

**Comment by hawkrives** [comment]
It's doable.

**Comment by hawkrives** [comment]
I'd like to split this into two phases: one, taken from my TES calculator, that shows you
- your jobs
- you pick your work award
- the amount you've earned overall
- the number of hours you've worked overall
- the number of hours you can still work
- the number of weeks until work ends
- the number of hours you need to work per week to make your award

and then, phase 2, which lets you edit and submit your TES timecards.

Dan Beach is/was working on integrating the above information into the TES somewhere.

**Comment by hawkrives** [comment]
Actually, as soon as I finish the SIS view (mainly the networking) I'll be able to do part 1 of this view.

I've built it twice before, once in react and once as a server-side python cgi script.

**Comment by elijahverdoorn** [comment]
Cool, but that's not going in v1. We don't have time to test that the way that I'd want to, not to mention the fact that I don't have a timecard to fill out, since it's summer. We can look to 1.1 for that feature, when I'll have a timecard to do.

**Comment by hawkrives** [comment]
I have a timecard actually!

**Comment by drewvolz** [comment]
I had an interesting idea for this. To prevent timecards from being filled out at the end of each month (we are probably all guilty of this), what if we approached this with the mindset of: filling out the time card is a hassle. How can we make this more convenient?

We could _eventually_ develop a timer that would keep track of time worked. You open the TES portion of the app, and the view that greets you is a timer, ready to track hours. The worker starts the timer and continues to go about their work. At the end of their shift, they open the app again and hit stop. This process has now collected the shift length as well as starting and stopping times. At this point, we can do a few things.
- Present a final timer interface to allow adjustment of the starting/stopping times in a flexible way.
- Move this data into the appropriate table cells on the TES WebView.

Once the worker gives it their final approval and is satisfied with the times they are submitting, they save their time into the TES. I think we should avoid auto-submission at all costs... we do not want to mess with St. Olaf payroll and have fingers pointed at us. It is purely up to the worker to hit save on their data.

This is trying to eliminate dealing with the table cells as much as possible, as well as prevent the need to enter in data in one swoop before a pay period, hopefully making for a more pleasant experience working with the TES.

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/TES).

**Comment by hawkrives** [comment]
I'm just going to go ahead and limit this feature: we have no interest in allowing TES _submissions_. This will strictly be a TES _viewer_.

**Comment by OmarShehata** [comment]
Why do we have no interest in allowing TES submissions @hawkrives ? Do you mean this just for now or forever?

I really like @drewvolz 's idea of thinking of ways to make it more convenient to change the submission behavior. One thought I had reading this is to try to limit the amount of extra work people have to do. So, one other feature could be an integration with google calendars. If you assume most (or some?) people already fill out a timeslot on their calendars for their work, maybe the app could just pick that up and insert it. 

Of course you'd want to avoid it being completely passive (in case you have a work shift automatically repeat every work but you missed one or didn't work the full time etc..?) so after each shift it could just pop up asking you to confirm if the times are correct, and either decline, or tweak the times and accept.

**Comment by hawkrives** [comment]
If you were going to interest me in TES submission, we'd need to get IT on board with making it an official integration. There are just too many little details about timecards and hours worked that the TES handles – usually – and that HR cares about, that we might miss or break subtly, and wind up with either HR mad at us, or IT, or …

I'd like to experiment with ways to improve the input process, as well, but whatever we do I would like someone official from the school to look it over / think about it before we ship it.

(Which is very different from my stated point above. I don't remember why I wrote that, but I had a sudden realization while I was doing my TES parsing, and wrote that note. I no longer recall why.)

**Comment by elijahverdoorn** [comment]
I'm going to agree with @hawkrives that the safer method of just reading the data for now is better. There are a ton of things that could go wrong, and I'm really not in the mood to have a fight with HR/Business Office/IT. If we develop something and can show them verifiable results, I'll bring it to the relevant groups.

**Comment by OmarShehata** [comment]
Ah, right. I hadn't realized the relevant authorities weren't on board with this yet.
