### ISSUE TITLE
Crash caused by submitting form in news

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#744]
Hitting submit on a form that rendered in a KSTO news story view causes the application to crash.

**Comment by hawkrives** [comment]
We could ... um. Hide `<form>` elements in the rendered story? Check for `<form>` elements in the article contents and remove them from the list?

**Comment by drewvolz** [comment]
I am okay with that idea. I cannot imagine another scenario where a submit button exists outside of a form.
