### ISSUE TITLE
Add webview for Mobile PrintRelease website

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#78]
https://papercut.stolaf.edu:9192 (only available on-campus)

**Comment by hawkrives** [comment]
(this could also be done with a native view the just scrapes the webview, because the webview is s-l-o-w.)

[the native view could also be a subsequent addition, after the webview.]

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Print-release-mobile).

**Comment by hawkrives** [comment]
Hawken Rives, [Aug 3, 2017, 5:09 PM]:
omg I found a papercut rest api

and it's enabled

https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=rives

(on-campus only)

(and it's internal/undocumented, but we really only upgrade papercut once/twice a year, so … I want to keep it at least until it breaks once)

… hmm. my … command line explorations … which have no session … are only working for _my_ username

this is odd

wtf. the _server_ seems to be keeping track of what IP you are logged in with, and authorizing all requests from that IP as you

until you log out

(which it does automatically after a bit)

(but still)

and I think that it's just the mobile print release stuff that behaves that way, … but c'mon, papercut
