### ISSUE TITLE
[RFC] Revisit location permissions

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#798]
[Let's revisit this](https://github.com/StoDevX/AAO-React-Native/commit/e0f24df2eeee4d7871ca307da9fc6a2f6abb153f#diff-020edf1fd6d483b0e2c8f5a5734ea1f2R6). Notifications are not being utilized, so we should remove access to fine location. I am unsure if Google Analytics uses location data (coarse or fine) or if it gathers the information from the network itself. In the case it is not being used, let's get that out of the app. 

One additional approach is to not solicit their location to decide which users to deliver a notification to. It could be within Settings and we would leave it up to the user on whether they would like notices. I would even advocate to go as far as providing a few distinct channels to opt-in/out of... if and when notifications become something this app uses.

**Comment by hawkrives** [comment]
I will need fine location data for the wifi reporting. In light of that, I'd like to close this issue.
