### ISSUE TITLE
Building hours fails to automatically update

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#831]
The building hours ListView does not update the status badges. The detail view updates fine.

**Comment by hawkrives** [comment]
If I had to guess, I'd guess that this is related to SimpleListView, and we just haven't noticed it.

**Comment by hawkrives** [comment]
It is.

It's in `rowHasChanged`, in SimpleListView's DataSource.

I still don't know _why_ DataSource was re-rendering the rows before? Assuming that was its job? (TBH, I still don't understand DataSource at all. [and rn@0.42 will let us remove it, I think; both FlatList and SectionedList have docs now.])

Anyway. If I change rowHasChanged to `return true`, every row renders, every time. Which makes sense, I guess.
