### ISSUE TITLE
New org badge applied to all rows

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#832]
In a last second effort to **optimize** labeling a student org as new or not, we slipped-in a way to label orgs in a more efficient way. Testing the app now reveals that every org was labeled as new... the correct behavior would be to only label new orgs as new. Additionally, the style for the new dots are not being applied.

**Comment by drewvolz** [comment]
The second issue concerning the dot style results from this error:

```bash
Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `View`.
Bad object: {
  "fontSize": 24,
  "color": "transparent"
}
```

**Comment by drewvolz** [comment]
This is fixed by changing the badge `<View/>` to a `<Text/>`

```Js
<Row alignItems="flex-start">
  <Text style={[styles.badge, styles.badgeContainer]}>
    <Text style={[item.newOrg && styles.newOrgBadge]}>
      •
    </Text>
  </Text>
```

**Comment by hawkrives** [comment]
I introduced this while I was fixing linter errors in #830.
