### ISSUE TITLE
Investigate a solution to getDetailedBuildingStatus test failing

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#853]
in `source/views/building-hours/__tests__/get-detailed-building-status.test.js:53:16`

```diff
- Expected
+ Received
 @@ -1,7 +1,7 @@
     Array [
       Object {
         "isActive": true,
         "label": "Hours",
-        "status": "10:30am — 2:00am",
+        "status": "10:30am — 3:00am",
       },
     ]
```

see also https://travis-ci.org/StoDevX/AAO-React-Native/jobs/210368527#L1781-L1789

something something dst? will it start working tomorrow? who knows.

**Comment by drewvolz** [comment]
It does smell like a DST issue

**Comment by drewvolz** [comment]
I've noticed that from 12:00am - 1:59am CT, any building that closes at 2am (pause, library) will display a closing time of 3:00am. After the time strikes 2:00am, the closing time reverts back to 2:00am.

**Comment by hawkrives** [comment]
Is that any day, or just yesterday / this morning?

If it says just yesterday/this morning, I'm still going to lump it under "DST", because 3am this morning is ~24 hours after the jump

**Comment by drewvolz** [comment]
This was from this morning.

**Comment by drewvolz** [comment]
I think this is fixed just as you predicted.

**Comment by hawkrives** [comment]
I'd like to keep the issue open to remind me about it.

**Comment by hawkrives** [comment]
… I should have written a note to myself about how to fix this.

**Comment by hawkrives** [comment]
@drewvolz: https://github.com/StoDevX/AAO-React-Native/issues/853#issuecomment-286102686

> I've noticed that from 12:00am - 1:59am CT, any building that closes at 2am (pause, library) will display a closing time of 3:00am. After the time strikes 2:00am, the closing time reverts back to 2:00am.

Given that the skipped hour is from 12:59am to 2:00am, we should attempt to figure out how to continue showing "2:00am" as the close label, as the offices will _technically_ close an hour before they normally do (if you measure by the duration they were open).
