### ISSUE TITLE
Home screen editing idea

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#88]
Currently, there is no way to edit the icons on the home screen. I would _love_ the ability to rearrange and disable some options there, especially as we add new sections.

Here's my proposal:
- We make the Edit button pull up a screen with two lists. 
- You can drag items between the lists, and rearrange them within the top list. (The bottom list is always alphabetical.)
- Items in the bottom list are `disabled` and hidden from the home screen.
- The order of the items in the top list is the order of the icons on the home screen.
- These settings are stored in the `AsyncStorage('homescreen:order')` and `AsyncStorage('homescreen:disabled')` stores.
- When we add a new screen, it is automatically appended to the end of the enabled list.

**Comment by elijahverdoorn** [comment]
Removing first change, I think that this wouldn't be easy for my team members on their first go. It's a great idea otherwise.

**Comment by hawkrives** [comment]
Good point 😆 It's probably about at our level right now, I guess.

**Comment by drewvolz** [comment]
- [react-native-sortable-listview](https://www.npmjs.com/package/react-native-sortable-listview)
- [react-native-SortableList](https://github.com/hayeah/react-native-SortableList)

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Home-screen-editing).

**Comment by drewvolz** [comment]
Completed in #378
