### ISSUE TITLE
Calendar won't load on android

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#89]
The loading screen never goes away, both tabs.

**Comment by hawkrives** [comment]
frick. i'll look at it.

**Comment by hawkrives** [comment]
<img width="543" alt="screen shot 2016-08-19 at 9 02 40 pm" src="https://cloud.githubusercontent.com/assets/464441/17809259/4723600a-6650-11e6-9cbc-892816b80139.png">

Latest `master` for me. I love these issues.

**Comment by elijahverdoorn** [comment]
I'll add some debugging log calls and get more information tonight. It's possible that I just didn't wait long enough, but even if that's the case we should have some sort of message to the user that says "we're not broken, the request is just taking a while". Maybe turning the loading screen into the spinning thing would communicate that? Implement that for v1.next?

**Comment by drewvolz** [comment]
A good one for your team _after that_ is the loading spinner  2.0 -- which could be the Ole The Lion SVG!

**Comment by hawkrives** [comment]
We could also actually make the "error" state change something, so you know when it's error – at least for us

**Comment by elijahverdoorn** [comment]
I like both ideas.

**Comment by elijahverdoorn** [comment]
This is still happening to me, even with a reinstall of the app from master. Maybe it's just me, or it could be my calendar key?

**Comment by hawkrives** [comment]
Shouldn't be your key – I'm using your key too

**Comment by elijahverdoorn** [comment]
Not reproducible, I re-copied my key and it works fine. Closing.
