### ISSUE TITLE
Streaming Media

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#9]
> - Streaming Media PRs Welcome
>   - Implementation unclear
>   - Reading Flash media might not be easy, all streaming at olaf is currently through ShockWave Flash

It is, but the webcams at least are also available as a raw MP4 stream, IIRC. I'll look around for the URL again.

This is being developed in the [streaming-media](https://github.com/StoDevX/AAO-React-Native/tree/streaming-media) branch.

**Comment by hawkrives** [comment]
Here we go: from `https://www.stolaf.edu/multimedia/webcams/webcams.js`,

```
{file: 'http://stolaf-flash.streamguys.net/webcams/' + cam + '.stream/playlist.m3u8'}
```

So each camera feed lives at `http://stolaf-flash.streamguys.net/webcams/$cam.stream/playlist.m3u8`.

`.m3u8` is an mp4 playlist file. IIRC most things can read them and load the implied media automatically.

It might be worth seeing how easy it would be to use these.

**Comment by hawkrives** [comment]
Camera names:

```
himom
bcplaza
eastquad
tomsonwest
tomsoneast
alumniwest
```

**Comment by hawkrives** [comment]
so one example URL would be `http://stolaf-flash.streamguys.net/webcams/himom.stream/playlist.m3u8`. 

In VLC:

![image](https://cloud.githubusercontent.com/assets/464441/17282582/4ba20d42-57e2-11e6-89cb-abbc334b0261.png)

**Comment by elijahverdoorn** [comment]
I dug into this earlier in the summer, and I found the same thing, but VLC wouldn't open them for me. (and if VLC doesn't open it, I assume that nothing can!) Given that, feel like coding something basic up?

**Comment by drewvolz** [comment]
From only a minute of research, I have not found anything that can stream the `m3u8` streams in React Native. Needs more research?

**Comment by hawkrives** [comment]
Hmm. Lemme try some things.

**Comment by hawkrives** [comment]
I'm going to try https://github.com/react-native-community/react-native-video first. It's in my history as something I've visited before.

**Comment by drewvolz** [comment]
[Check out the issues](https://github.com/react-native-community/react-native-video/issues?utf8=%E2%9C%93&q=m3u8) related to the keyword `m3u8` on that one. It might work as is?

Otherwise, see [this particular thread](https://github.com/react-native-community/react-native-video/issues/122).

**Comment by hawkrives** [comment]
yeah, it's just not doing much of anything for me at the moment. thanks for the links!

**Comment by hawkrives** [comment]
So. Current status:
- You can play the video by opening the m3u8 URL directly in Safari on both iOS and macOS.

<img src='https://cloud.githubusercontent.com/assets/464441/17438398/9427c5ce-5b5d-11e6-80a1-fb49e9a90c5f.jpg' width='400px' />
<img src='https://cloud.githubusercontent.com/assets/464441/17438403/972712ac-5b5d-11e6-81d8-b40cbfdc6b00.jpg' width='400px' />
- but loading the URL directly in a `<WebView>` doesn't work.So. Current status:
- You can play the video by opening the m3u8 URL directly in Safari on both iOS and macOS.

<img src='https://cloud.githubusercontent.com/assets/464441/17438398/9427c5ce-5b5d-11e6-80a1-fb49e9a90c5f.jpg' width='400px' />
<img src='https://cloud.githubusercontent.com/assets/464441/17438403/972712ac-5b5d-11e6-81d8-b40cbfdc6b00.jpg' width='400px' />
- but loading the URL directly in a `<WebView>` doesn't work.

<img src='https://cloud.githubusercontent.com/assets/464441/17438450/dc4ced5c-5b5d-11e6-8631-31ed56a348df.jpg' width='400px' />

Then I remembered that you can put custom html into the web view, so I tried building a little html snippet to load the video:

``` html
<video autoplay muted>
    <source src="$url/playlist.m3u8" type="application/x-mpegURL">
</video>
```

Which worked in desktop Safari!

<img src='https://cloud.githubusercontent.com/assets/464441/17438488/08e3926c-5b5e-11e6-9912-56eae91e4b5a.jpg' width='400px' />

And … partially worked in the app.

<img src='https://cloud.githubusercontent.com/assets/464441/17438498/1546f2f6-5b5e-11e6-9080-e19e3d3dc57a.jpg' width='400px' />

So that's current status.

**Comment by drewvolz** [comment]
Nice work! Webviews seem to handle it well (from what I can see)

**Comment by hawkrives** [comment]
Current status: ![830932941_7088475972866689906](https://cloud.githubusercontent.com/assets/464441/17439424/fef1faf0-5b62-11e6-9f25-55628a73f992.jpg)

Problems: um, they all load at once. Do we want a list of the webcams and then push on a new screen just for the video? (neé AAO 1.0)

**Comment by hawkrives** [comment]
https://github.com/StoDevX/AAO-React-Native/tree/streaming-media

**Comment by hawkrives** [comment]
Or we could load a static thumbnail of each video from the feed and show that in the list.

**Comment by hawkrives** [comment]
It's bedtime for me now. 😴

**Comment by drewvolz** [comment]
Is it possible to display them all on this screen, full width and normal height, and then allow rotation to put it in full screen? Or tapping?

**Comment by hawkrives** [comment]
Maybe. I was tired of fighting the layout system 😂

**Comment by drewvolz** [comment]
I recognize we are getting closer to having these display in a Webview. If we do ever decide to render these another way, here are a couple possibilities.
- [rnwbnr](https://github.com/rogozhnikoff/rnwbnr/blob/3470f9b5835a4df56a37c766b66360cda0122267/src/view/components/viewer.js)
- [videoPlayer](https://github.com/xiDaiDai/Practice_in_ReactNative/blob/c755cb59d961b0b093c9a9c933cadd4bd8716ebe/src/tests/videoPlayer.js#L34)

**Comment by drewvolz** [comment]
With our current implementation of separate webviews, one can play the stream multiple times if they pinch out of a stream instead of hitting the "Done" button. That's not entirely ideal, so we should most likely move forward with passing the stream url onwards to a separate view... and be sure that the "Done" button on the stream does not prevent us from opening the view again.

Also, rotation only works in the simulator but not on the actual device. I am now testing on iOS 10. 

See #123

**Comment by drewvolz** [comment]
Another thought for Streaming media is the potential to provide access [(with rss/json)](https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=-1&q=https://www.stolaf.edu/multimedia/streams/rss/rss.cfm) to the events via [the streams up on multimedia](https://www.stolaf.edu/multimedia/)

**Comment by elijahverdoorn** [comment]
That's a good plan, something for another version. Maybe make an issue to track it?

**Comment by elijahverdoorn** [comment]
oops

**Comment by drewvolz** [comment]
Sure. That child story now lives at #127.

**Comment by elijahverdoorn** [comment]
Closing this one, see #137

**Comment by hawkrives** [comment]
We still need Weekly Movie info (#141) and a non-silly webcams view (#142).
