### ISSUE TITLE
Map location tracking data

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#90]
Is anyone familiar with the life cycle of permissions in regards to location data and WebViews? We are using a WebView which has requested specific permission to track our location. Do we know if it ever stops tracking, if it requests every time we open the app -> view, etc. We should look into this one... it could be a battery killer at some point?

**Update**
It appears that the location is requested twice at init, once for the app and once for the website. Thereafter, the website requests the location each time.

**Comment by hawkrives** [comment]
I know that once you grant it permission, the web view asks for permission …

which makes me think that, as long as the web view isn't using it, neither are we.
