### ISSUE TITLE
Dictionary v1.1

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#91]
[Enhanced dictionary list rendering](https://medium.com/@spencer_carli/react-native-basics-how-to-use-the-listview-component-a0ec44cf1fe8#.der6qokx5)
- [ ] Search
- [ ] Alphabetical section headers

**Comment by hawkrives** [comment]
Section headers shouldn't be hard if we just use a normal listview

**Comment by elijahverdoorn** [comment]
All our views will need an update at some point, I like that article. Adding good first change.

**Comment by hawkrives** [comment]
We should also use the renderSeparator prop in our other ListViews, instead of the current borderBottom method.
