### ISSUE TITLE
Moving away from presence

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/AAO-React-Native#932]
I was informed recently by Kris Vatter that St. Olaf will not be renewing their contract with presence for another year. The contract expires in May, and due to issues with the company not keeping some of their promises it is looking like we will not be continuing with them. Given this, we will have to refactor or remove the student orgs view (and anything else that uses presence)

**Comment by hawkrives** [comment]
Duly noted :-)

Let's go ahead and remove the Student Orgs calendar from the next release, then. I'll ask Dan about adding a simple API to stolaf.edu/orgs/list, but it won't be ready for a bit.
