### ISSUE TITLE
Add a "Report a WiFi Problem" quick-access button

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#934]
> - https://github.com/mastermoo/react-native-action-button
> - https://github.com/maxs15/react-native-modalbox

I'm envisioning a FAB on the homescreen, in the bottom-right, that gives you two options when you tap it:

- Report a WiFi Problem
- [and maybe] Make a Helpdesk Ticket

This issue is about the framework of the button and the Report WiFi button, though.

---

I think that when you tap the Wifi option, it should pop open the modal and say "Collecting data…".

We need to submit the user's device info, as well as the current location (lat/long/alt).

I am making an endpoint to store the data: we'll be able to POST a json blob to www.stolaf.edu/apps/all-about-olaf/wifi when I'm done there (nothing exists yet.)

**Comment by elijahverdoorn** [comment]
I had a chat with Kurtis (IT Network Manager) regarding this too, and I'm looking forward to getting this in the app.
I'm wondering if a FAB is the right way to go about this - FABs are not really in the iOS pattern, and material design says that "A floating action button represents the primary action in an application." (A floating action button represents the primary action in an application.), and I don't see reporting wifi issues as the primary action of our application. I suggest that we make another section, something like "technology help" or "contact IT" or something that would have the wifi problem report, as well as easy ways to email helpdesk, get info about StoPrint and access IT produced documentation.

**Comment by hawkrives** [comment]
So I had that thought too, but I came back to the FAB as the fastest / lowest-friction way to submit a wifi problem report…

Here's what I have so far, UI-wise:

iOS | Android
--- | ---
![ios](https://cloud.githubusercontent.com/assets/464441/24925087/c080f5e6-1ebc-11e7-83d7-c30edd9ce526.jpg) | ![android](https://cloud.githubusercontent.com/assets/464441/24925093/c58f9038-1ebc-11e7-99e2-6eb72ea49225.jpg)

**Comment by hawkrives** [comment]
After talking with Eli, I'm going to take a different tack here: I'm going to try adding a 13th button to the homescreen, which takes you to a screen with the three options.
