### ISSUE TITLE
Call codePush.sync in the root component

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#966]
In order to achieve the workflow we desire, we need to specify the deployment key we want the current user to synchronize with when calling the codePush method. When specified, this key will override the "default" one that was provided in the app's Info.plist (iOS) or MainActivity.java (Android) files. This allows us to produce a build for staging or production, that is also capable of being dynamically "redirected" as needed. ([more info](https://github.com/Microsoft/react-native-code-push#dynamic-deployment-assignment))

```js
// Imagine that "userProfile" is a prop that this component received
// which includes the deployment key that the current user should use.
codePush.sync({ deploymentKey: userProfile.CODEPUSH_KEY });
```

<hr>

Hint [from the docs](url)

> **Update not being displayed after restart**
> If you're not calling sync on app start (e.g. within componentDidMount of your root component), then you need to explicitly call notifyApplicationReady on app start, otherwise, the plugin will think your update failed and roll it back.

**Comment by hawkrives** [comment]
We could import the key from the package.json file, since we store them in there.
